demisto/demisto-sdk

- CHANGELOG.md
- demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
add a condition to avoid cases without entities.
> run-test-playbooks - add a condition to avoid cases without entities

- conftest.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py
> fixed tests

- conftest.py
- demisto_sdk/__main__.py
- demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py
- demisto_sdk/tests/integration_tests/secrets_integration_test.py
fixes: https://github.com/demisto/etc/issues/45168
> Change import location to local in main

- demisto_sdk/commands/common/hook_validations/incident_field.py
> Remove WhiteList For Incident Field Validation

- CHANGELOG.md
- demisto_sdk/commands/doc_reviewer/rn_checker.py
> Added deprecated templates for release notes

- CHANGELOG.md
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_playbook.py
- demisto_sdk/tests/test_files/format_new_playbook_copy.yml
fixes: https://github.com/demisto/etc/issues/45276
Format TPB ID to be equal to name (if file is new) like Playbook format.
Moved the format functions of the ID to name to the subclass of both TPB and PB
> TPB Format Name Like PB

- demisto_sdk/commands/test_content/TestContentClasses.py
fixes: [link to the issue](https://github.com/demisto/etc/issues/32236)
Created an artifact with the names of all successful tpbs
> Added successful tests artifacts

- docs/release_guide.md
Fixed the release guide change from circle token to GitLab token
> sdk release guide: update gitlab as CI 

- demisto_sdk/commands/split/tests/ymlsplitter_test.py
- demisto_sdk/commands/split/ymlsplitter.py
- demisto_sdk/commands/unify/tests/yml_unifier_test.py
- demisto_sdk/tests/test_files/integration-Zoom.yml
fixes: https://code.pan.run/xsoar/content/-/jobs/10015493
remove the auto-generated section headers in the download command.
> remove section headers when extracting code in the download command

- demisto_sdk/__main__.py
- demisto_sdk/commands/common/git_util.py
- demisto_sdk/commands/common/hook_validations/content_entity_validator.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/doc_reviewer/doc_reviewer.py
- demisto_sdk/commands/secrets/secrets.py
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/update_release_notes_integration_test.py
Reverts demisto/demisto-sdk#1758
> Revert "primary branch can be main"

- demisto_sdk/commands/common/schemas/incidentfield.yml
- demisto_sdk/commands/common/schemas/incidentfields.yml
- demisto_sdk/commands/common/tests/structure_test.py
fixes: https://github.com/demisto/etc/issues/45640
Added the Aliases field and its schema to the incident field and incident fields schemas.
> MarketplaceV2: Add Aliases to inc fields schemas.

- demisto_sdk/commands/common/schemas/incidentfield.yml
relates: https://github.com/demisto/content/pull/17176/files
Added "x2_fields" to the incident fields schema
> Added to fields_x2 to schema

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/readme.py
- demisto_sdk/commands/common/tests/readme_test.py
fixes: https://github.com/demisto/etc/issues/46177
- Added a retry mechanism to the validation that checks remote images.
- Only checking for http status code without downloading the image checked (thanks @ilaner for the idea)
> improve image tests

- demisto_sdk/__main__.py
- demisto_sdk/commands/common/hook_validations/field_base_validator.py
- demisto_sdk/commands/common/hook_validations/id.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/create_id_set/create_id_set.py
Added CoreAlertFields to ignore prefix validation since it is only present  in marketplacev2
> Added CoreAlertFields to ignore prefix validation

- .circleci/config.yml
- CHANGELOG.md
> remove fail duplicates

- CHANGELOG.md
- demisto_sdk/commands/common/content/objects/pack_objects/pack.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tests/update_id_set_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py
fixes: https://github.com/demisto/etc/issues/46241
Consider the marketplace values when checking for duplicate IDs in the ID set.
> IDSet: Update duplicate IDs check

- CHANGELOG.md
- demisto_sdk/commands/init/initiator.py
> Fixed typo in initiator

- demisto_sdk/commands/common/git_util.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: unstable coverage lines in PRs
ignore coverage of some lines.
> ignore coverage lines

- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/common/schemas/script.yml
fixes: https://github.com/demisto/etc/issues/45852
update script schema
> update script schema

- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_integration.py
fixes: https://github.com/demisto/etc/issues/46263
Validate fetch params acording marketplace values
> Validate fetch params acording marketplace values

- demisto_sdk/commands/coverage_analyze/tests/tools_test.py
- demisto_sdk/commands/coverage_analyze/tools.py
related: https://github.com/demisto/etc/issues/45703
Some general coverage helpers (not really related to the `coverage-analyze` command).
> added coverage tools

- .circleci/config.yml
revert  --fail-duplicates in config yml when creating and merging ID set
> revert fail duplicates

- demisto_sdk/commands/common/schemas/integration.yml
enable alternative values for the mirroring fields and parameters in integration
> Integration Schema: enable alternative values for the mirroring fields and parameters

- demisto_sdk/commands/common/tests/update_id_set_test.py
- demisto_sdk/commands/common/update_id_set.py
fixes: https://jira-hq.paloaltonetworks.local/browse/XDR-48849
enable indicator layouts in marketplace v2
> IDSet: enable indicator layouts in marketplace v2

- CHANGELOG.md
- demisto_sdk/commands/format/update_indicatorfields.py
fixes: https://github.com/demisto/etc/issues/46089
fix format of indicator fields
> fix format of indicator field

- demisto_sdk/commands/create_artifacts/content_artifacts_creator.py
fixes: https://jira-hq.paloaltonetworks.local/browse/XDR-48849
Enable layouts in create-content-artifacts for MPv2
> Enable layouts in create-content-artifacts for MPv2 

- .pre-commit-config.yaml
> update pre-commit features

- demisto_sdk/__main__.py
- demisto_sdk/commands/common/tests/update_id_set_test.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/create_id_set/tests/test_data/incidentfield-to-test.json
- demisto_sdk/commands/find_dependencies/find_dependencies.py
- demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py
- demisto_sdk/tests/integration_tests/create_id_set_integration_test.py
fixes: https://github.com/demisto/etc/issues/46570
* Added dependencies filtering by the supported marketplace.
* Added field aliasing support in dependencies calculations.
> support marketplace and field aliasing in dependencies calculations

- CHANGELOG.md
- demisto_sdk/__main__.py
fixes: https://github.com/demisto/demisto-sdk/issues/1912
> fixed .env didnt load currectly

- CHANGELOG.md
https://github.com/demisto/demisto-sdk/pull/1921
https://github.com/demisto/demisto-sdk/pull/1868
added changes i did in the sdk to the CHANGELOG.md
> added to changelog

- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/hook_validations/readme.py
added ignore option for pack README.md file (currently, it was supporting inside integrations and scripts ...
> added ignore option for pack README.md file

- CHANGELOG.md
fixes: https://github.com/demisto/demisto-sdk/pull/1887
added a changelog for the pack readme - [dev - bug] #1887 PR
> added a changelog for the pack readme validation

- demisto_sdk/commands/generate_unit_tests/README.md
- demisto_sdk/commands/generate_unit_tests/generate_unit_tests.py
- demisto_sdk/commands/generate_unit_tests/test_case_builder.py
- demisto_sdk/commands/generate_unit_tests/test_module_builder.py
> paramtrize added

- setup.py
fixes: https://code.pan.run/xsoar/content/-/jobs/11292433
This is a temporary fix
> include TestSuite in the setup

- demisto_sdk/commands/lint/docker_helper.py
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/resources/installation_scripts/powershell_image.sh
- demisto_sdk/commands/lint/resources/installation_scripts/python_image.sh
> speed up lint by using mount when posible

- demisto_sdk/commands/lint/docker_helper.py
> remove read only from lint mount

- .github/CODEOWNERS
> add codeowners of vscode. fix some others

- CHANGELOG.md
- demisto_sdk/commands/validate/tests/validators_test.py
Updated the CHANGELOG.md file with the 1.6.2 version header.
> 1.6.2 Release

- demisto_sdk/__main__.py
fixes: https://github.com/demisto/etc/issues/47221
Changed the description of **xsoar-config-file-update** to give more accurate information.
> changed the description of xsoar-config-file-update commands

- .pre-commit-config.yaml
Ready
removed: 
- pyyaml
- requirements.txt fixer
upgraded:
- pyupgrade.
- mypy
> update pre-commit, remove pyyaml

- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/secrets/secrets.py
fixes: [demisto/etc/issues/47326](https://github.com/demisto/etc/issues/47326)
Fixed an edge case where yml secrets files failed with duplication error.
> Allow duplicate keys for secrets

- .circleci/config.yml
Fixed lint on build. Changed to new docker image.
Passed build: https://app.circleci.com/pipelines/github/demisto/demisto-sdk/15102/workflows/f35c1767-fd4a-4aee-b4b7-0e4f7ee7a143/jobs/87153
> build: fix lint step

- TestSuite/integration.py
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/content/objects/pack_objects/abstract_pack_objects/yaml_unify_content_object.py
- demisto_sdk/commands/common/hook_validations/id.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py
- demisto_sdk/commands/split/ymlsplitter.py
- demisto_sdk/commands/unify/integration_script_unifier.py
- demisto_sdk/commands/unify/tests/yml_unifier_test.py
- demisto_sdk/commands/unify/yaml_unifier.py
- demisto_sdk/commands/validate/tests/validators_test.py
groundwork for https://github.com/demisto/etc/issues/47159
Implemented the `YAMLUnifier` interface
Did not make any actual code changes, just rearranging the existing code before implementing the fix for https://github.com/demisto/etc/issues/47159
> Unify - YAML Unifier Interface

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/hook_validations/field_base_validator.py
- demisto_sdk/commands/common/hook_validations/incident_type.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/mapper.py
- demisto_sdk/commands/common/hook_validations/script.py
- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/commands/common/tests/classifier_test.py
- demisto_sdk/commands/common/tests/field_validator_test.py
- demisto_sdk/commands/common/tests/generic_field_test.py
- demisto_sdk/commands/common/tests/incident_type_test.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/common/tests/lists_test.py
- demisto_sdk/commands/common/tests/script_test.py
- demisto_sdk/commands/common/tests/widget_test.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
https://github.com/demisto/demisto-sdk/pull/1976 continued
> quite -> quiet typo 

- CHANGELOG.md
- demisto_sdk/commands/test_content/TestContentClasses.py
related: https://github.com/demisto/etc/issues/44364
Added logging in case of typo in the values of configuration.
> Testing pb inputs

- demisto_sdk/commands/common/content/objects/abstract_objects/yaml_object.py
- demisto_sdk/commands/common/content/tests/objects/abstract_objects/yaml_object_test.py
- demisto_sdk/commands/common/handlers/yaml/ruamel_handler.py
> fix: removed type from yaml object

- .circleci/config.yml
> update test-lint docker image to 3.0.0.27979

- .circleci/config.yml
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/test_content/tests/timestamp_replacer_test.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
Unit tests can be run in parallel
> Parallelizing SDK UT

- CHANGELOG.md
- demisto_sdk/commands/update_xsoar_config_file/tests/update_xsoar_config_file_test.py
- demisto_sdk/commands/update_xsoar_config_file/update_xsoar_config_file.py
https://panw-global.slack.com/archives/C02G1GQK7SM/p1648760645016729.
> XSOAR config bug fix

- demisto_sdk/commands/lint/docker_helper.py
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/resources/installation_scripts/python_image.sh
fixes some container build exceptions.
- code design looks better :sunglasses:.
- we can now build docker images in the circleCI environment.
circle-build: https://app.circleci.com/pipelines/github/demisto/content/152793/workflows/49ed8318-ae3f-42fe-93c5-ffa950b13cae/jobs/498050
gitlab-build: https://code.pan.run/xsoar/content/-/jobs/11719406
> docker helper improve

- demisto_sdk/commands/generate_docs/generate_script_doc.py
- demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
fixed a flaky test failure in master of `test_missing_data_sections_when_generating_table_section`
> flaky test fix testing

- CHANGELOG.md
Updated the CHANGELOG.md according to the new sdk version - 1.6.3.
> Updated the CHANGELOG.md according to the new sdk version - 1.6.3

- .pre-commit-config.yaml
- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/zip_packs/packs_zipper.py
- pyproject.toml
> build: added vulture

- CHANGELOG.md
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/47939
Added validation for deleted non-content items
> dev-bug - Added validation for deleted non-content items

- CHANGELOG.md
- docs/release_guide.md
- pyproject.toml
> 1.6.4 Release

- .github/workflows/validate-changelog-update.yml
fixes: https://github.com/demisto/etc/issues/48041
In error msg CHNGLOG.md was changed to CHANGELOG.md
> Error msg was updated

- CHANGELOG.md
- demisto_sdk/commands/test_content/timestamp_replacer.py
> build: 🧙🏿‍♂️ timestamp_replacer

- demisto_sdk/commands/common/logger.py
- demisto_sdk/commands/lint/docker_helper.py
- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/lint_manager.py
- demisto_sdk/commands/lint/linter.py
> added more logs to lint

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/readme.py
- demisto_sdk/commands/common/tests/integration_test.py
fixes: https://github.com/demisto/etc/issues/48091
Added a condition to make sure the REAdME file exist before trying to open it
Before
After
> Fix README validation

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/correlation_rule.py
- demisto_sdk/commands/common/hook_validations/modeling_rule.py
- demisto_sdk/commands/common/hook_validations/parsing_rule.py
- demisto_sdk/commands/common/hook_validations/triggers.py
- demisto_sdk/commands/common/hook_validations/xsiam_dashboard.py
- demisto_sdk/commands/common/hook_validations/xsiam_report.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: [link to the issue](https://github.com/demisto/etc/issues/48151)
related: https://github.com/demisto/content/pull/18740
Added new XSIAM items into the sdk-validate. For now, all validations will pass with no checking.
> SDK - XSIAM items into validate

- CHANGELOG.md
- demisto_sdk/commands/common/logger.py
- demisto_sdk/commands/coverage_analyze/tests/helpers_test.py
> fix: -vvv log level now print logs

- demisto_sdk/commands/common/logger.py
- demisto_sdk/commands/coverage_analyze/tests/helpers_test.py
* Make demisto-sdk logs work again (with verbosity level)
> Fix demisto-sdk logger

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/common/tests/integration_test.py
Changing `isFetchEvents` to `isfetchevents`.
> Lowercase isfetchevents

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/readme.py
> fix: mdx server not closing

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
fixes: [CIAC-415](https://jira-hq.paloaltonetworks.local/browse/CIAC-415)
Added more commands to ignore in the case of the **verify_yml_commands_match_readme** validation.
> Added more commands to ignore list

- CHANGELOG.md
- demisto_sdk/commands/common/logger.py
change default log level to warning
> change default log level to warning

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/integration.py
Correct error msg checkbox validation.
> Correct error msg checkbox validation

- .pre-commit-config.yaml
- demisto_sdk/commands/lint/linter.py
- poetry.lock
- pyproject.toml
* putting filelock on the packmetada file as shared resource between packages
* Added `types-filelock` as a req for mypy
> File Lock on packmetada.json

- CHANGELOG.md
- poetry.lock
- pyproject.toml
added the **types-Markdown** to the types dependencies.
> feat: add types-markdown to dependencies

- demisto_sdk/commands/common/errors.py
> Update bc validation

- poetry.lock
- pyproject.toml
Add the `types-futures` dependency to the poetry.lock file
**Added due to bugs with mypy error on concurrent.futures import.**
> Added the `types-futures` dependency

- demisto_sdk/commands/format/update_layout.py
- demisto_sdk/commands/format/update_mapper.py
fixed a bug that if id_set_file was not provided the mapper format would fail.
> fix non-existent-field issue

- CHANGELOG.md
- demisto_sdk/commands/test_content/TestContentClasses.py
add the tpb id to the log line when it's run
> improve tpb logging

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
- demisto_sdk/tests/integration_tests/update_release_notes_integration_test.py
Reverted release notes to old format
> Reverted release notes to old format

- CHANGELOG.md
- pyproject.toml
- [ X In Hold - (Reason for hold)
> update to 1.6.7

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
> feat: removed subtype backwards compatability validation

- CHANGELOG.md
- demisto_sdk/commands/format/update_generic.py
fixes: https://github.com/demisto/demisto-sdk/issues/2137
> fix default fromversion prompt on download

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/format/format_module.py
fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-2646)
> Dont fail xsiam format

- demisto_sdk/__main__.py
- demisto_sdk/commands/lint/docker_helper.py
- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/tests/helper_test.py
> adding timeout and more logs to get python version

- demisto_sdk/commands/lint/commands_builder.py
- demisto_sdk/commands/lint/tests/command_builder_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3033
Add a flag to ignore site-packages to mypy
> Ignore site packages when running mypy

- .circleci/config.yml
- demisto_sdk/commands/coverage_analyze/coverage_report.py
- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/linter.py
> Fix coverage of unit tests

- demisto_sdk/commands/common/schemas/wizard.yml
Added the `incident_type` as an optional field (no validation were added).
> Add incident_type to wizard integration schema

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/classifier.py
- demisto_sdk/commands/common/tests/classifier_test.py
- demisto_sdk/commands/format/update_classifier.py
- demisto_sdk/tests/test_files/validate_integration_test_valid_types.py
fixes: CIAC-3218
* Added a validation that classifier's id and name are matching. Updated the format of classifier to include update_id too.
> Id name validate format

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/content/objects/pack_objects/readme/readme.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/create_artifacts/content_artifacts_creator.py
- demisto_sdk/commands/unify/generic_module_unifier.py
- demisto_sdk/commands/unify/integration_script_unifier.py
- demisto_sdk/commands/unify/yaml_unifier.py
- demisto_sdk/tests/integration_tests/content_create_artifacts_integration_test.py
- demisto_sdk/tests/integration_tests/unify_integration_test.py
- demisto_sdk/tests/integration_tests/upload_integration_test.py
Reverts demisto/demisto-sdk#2180
> Revert "Add Global Marketplace Env"

- demisto_sdk/commands/common/content/objects/pack_objects/pack.py
Ignore test scripts in ID set filtering in create-content-artifacts
> Ignore test scripts in ID set filtering in create-content-artifacts

- demisto_sdk/commands/common/content/objects/pack_objects/script/script.py
related to: https://github.com/demisto/demisto-sdk/pull/2185
> differ scripts and test scripts in the content object

- demisto_sdk/commands/split/ymlsplitter.py
> Fix split to contain the empty schema and rules obj

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/description.py
- demisto_sdk/commands/common/hook_validations/image.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/description_test.py
- demisto_sdk/commands/common/tests/image_test.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
- demisto_sdk/tests/workflow_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-1871
Validating that the following files have the right prefix:
- yml
- png
- py
- md
> Verify package directory name is the same as the files contained in the package

- CHANGELOG.md
- poetry.lock
- pyproject.toml
> update to 1.6.9

- demisto_sdk/commands/validate/README.md
- [ x] Ready
https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/__main__.py#L465
there is a typo in the manual 
> quite-bc-validation typo fix

- demisto_sdk/commands/common/tools.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3472i
added missing edge-cases to item searches in the ID set.
internal command: not adding release notes
> create-content-artifact: fix item searching in id set

- poetry.lock
> z3 solver update

- .circleci/config.yml
> upload unit test results

- CHANGELOG.md
- demisto_sdk/commands/common/content/objects/pack_objects/pack.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
Added translation to beta-integration file type
This [content PR](https://github.com/demisto/content/pull/20110) proves that the fix worked.
> Added beta to dict

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/tools.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3603
Being able to override existing env vars with dotenv
> dotenv to override existing environment variables

- demisto_sdk/commands/test_content/TestContentClasses.py
fixing logs error in xsiam build
> fixing logs error in xsiam build

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/tests/errors_test.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
[CIAC-3671](https://jira-hq.paloaltonetworks.local/browse/CIAC-3671)
> add file type to error message when it is not supported

- CHANGELOG.md
- demisto_sdk/commands/format/tests/test_formatting_readme_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3574)
> update docker - modules not available

- CHANGELOG.md
- demisto_sdk/commands/doc_reviewer/rn_checker.py
> added `Added a`, `Added an ` RN templates

- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/tests/deprecation_test.py
Fixed a typo in the IN155 error message
> fix a typo in error message

- demisto_sdk/commands/upload/README.md
No one knows that the base URL is not the same as UI URL!!!!
> Update README.md - BASE URL for XSIAM should be taken from the instance.

- CHANGELOG.md
- demisto_sdk/commands/common/content/objects/pack_objects/corrlation_rule/correlation_rule.py
- demisto_sdk/commands/common/content/objects/pack_objects/modeling_rule/modeling_rule.py
- demisto_sdk/commands/common/content/objects/pack_objects/parsing_rule/parsing_rule.py
- demisto_sdk/commands/common/content/objects/pack_objects/xsiam_dashboard/xsiam_dashboard.py
- demisto_sdk/commands/common/content/objects/pack_objects/xsiam_report/xsiam_report.py
- demisto_sdk/commands/common/content/tests/objects/pack_objects/correlation_rule/correlation_rule_test.py
- demisto_sdk/commands/common/content/tests/objects/pack_objects/modeling_rule/modeling_rule_test.py
- demisto_sdk/commands/common/content/tests/objects/pack_objects/parsing_rule/parsing_rule_test.py
- demisto_sdk/commands/common/content/tests/objects/pack_objects/xsiam_dashboard/xsiam_dashboard_test.py
- demisto_sdk/commands/common/content/tests/objects/pack_objects/xsiam_report/xsiam_report_test.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- poetry.lock
> Added normlize name function to xsiam pack objects

- CHANGELOG.md
- demisto_sdk/commands/validate/validate_manager.py
closes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3852
> filter meta files

- demisto_sdk/commands/common/content/objects/abstract_objects/dictionary_based_object.py
- demisto_sdk/commands/common/content/objects/abstract_objects/general_object.py
- demisto_sdk/commands/common/content/objects/abstract_objects/json_object.py
- demisto_sdk/commands/common/content/objects/abstract_objects/text_object.py
- demisto_sdk/commands/common/content/objects/abstract_objects/yaml_object.py
- demisto_sdk/commands/common/content/objects/pack_objects/tool/agent_tool.py
Use the correct term "deserialize" in place of the incorrect "unserialize".
> Replace "unserialize" with "deserialize"

- tests_end_to_end/test_e2e_demisto_sdk_flow_playbook.py
> sdk git branch typo

- demisto_sdk/commands/test_content/TestContentClasses.py
Adding build number to incident name (useful in XSIAM)
> Adding build number to incident name (useful in XSIAM)

- CHANGELOG.md
- demisto_sdk/commands/common/content/objects/pack_objects/corrlation_rule/correlation_rule.py
- demisto_sdk/commands/common/content/objects/pack_objects/modeling_rule/modeling_rule.py
- demisto_sdk/commands/common/content/objects/pack_objects/parsing_rule/parsing_rule.py
- demisto_sdk/commands/common/content/objects/pack_objects/trigger/trigger.py
- demisto_sdk/commands/common/content/objects/pack_objects/xsiam_dashboard/xsiam_dashboard.py
- demisto_sdk/commands/common/content/objects/pack_objects/xsiam_report/xsiam_report.py
- demisto_sdk/commands/common/content/tests/objects/pack_objects/trigger/trigger_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/upload/tests/uploader_test.py
> Build hotfix

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/script.py
> removed subtype validation

- CHANGELOG.md
- demisto_sdk/commands/common/content/objects/pack_objects/trigger/trigger.py
- demisto_sdk/commands/common/content/objects/pack_objects/xsiam_dashboard/xsiam_dashboard.py
- demisto_sdk/commands/common/content/objects/pack_objects/xsiam_report/xsiam_report.py
> Fix trigger

- CHANGELOG.md
- demisto_sdk/commands/common/content/objects/pack_objects/corrlation_rule/correlation_rule.py
- demisto_sdk/commands/common/content/objects/pack_objects/modeling_rule/modeling_rule.py
- demisto_sdk/commands/common/content/objects/pack_objects/parsing_rule/parsing_rule.py
- demisto_sdk/commands/common/content/objects/pack_objects/xsiam_dashboard/xsiam_dashboard.py
- demisto_sdk/commands/common/content/objects/pack_objects/xsiam_report/xsiam_report.py
> Fix build for all XSIAM items

- .circleci/config.yml
- demisto_sdk/commands/create_artifacts/content_artifacts_creator.py
- demisto_sdk/tests/integration_tests/content_create_artifacts_integration_test.py
- poetry.lock
- pyproject.toml
> Poetry v1.2 support

- demisto_sdk/commands/common/hook_validations/content_entity_validator.py
- demisto_sdk/commands/common/hook_validations/field_base_validator.py
- demisto_sdk/commands/common/hook_validations/incident_type.py
- demisto_sdk/commands/common/hook_validations/mapper.py
- demisto_sdk/commands/common/hook_validations/script.py
- demisto_sdk/commands/common/tests/content_entity_validator_test.py
fixes: https://panw-global.slack.com/archives/G011E63JXPB/p1662618065155439
fix reversed BC validation logic bug
Before:
After:
> fix reversed BC validation logic bug

- demisto_sdk/commands/common/schemas/integration.yml
related: https://jira-hq.paloaltonetworks.local/browse/CRTX-57734
Added schema fields for new data onboarding flow in XSIAM
> Update integration schema

- CHANGELOG.md
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
find scripts properly
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4064
> find type fix - script

- CHANGELOG.md
- demisto_sdk/__main__.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4121
This will create a tempdir for zip file and cleanup afterwards in upload instead of getting the same tempdir which cause problems with reusing it.
> fix upload with zips

- demisto_sdk/__main__.py
- demisto_sdk/commands/upload/tests/uploader_test.py
Fixes this PR: https://github.com/demisto/demisto-sdk/pull/2358
> hotfix to upload zips

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/download/downloader.py
- demisto_sdk/commands/split/ymlsplitter.py
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-16533
> Download `--no-code-formatting`

- CHANGELOG.md
- demisto_sdk/commands/download/downloader.py
> download fix

- demisto_sdk/commands/secrets/secrets.py
- demisto_sdk/commands/validate/validate_manager.py
> ignore vscode and devcontainer from validate and secrets

- demisto_sdk/commands/common/hook_validations/integration.py
fixes error IN148 in https://app.circleci.com/pipelines/github/demisto/content/193897/workflows/639c857d-a9a4-4c0c-b8a8-0605a507ebce/jobs/574481
> ignore optional fields in fetch parameter check

- .github/workflows/validate-changelog-update.yml
see [here](https://github.com/demisto/demisto-sdk/actions/runs/3144149686/jobs/5109788118), following [this PR](https://github.com/demisto/demisto-sdk/pull/2377)
> fix changelog check

- demisto_sdk/commands/test_content/TestContentClasses.py
solve access before assignment issue
> change try except order

- .github/dependabot.yml
> dependabot - weekly

- demisto_sdk/commands/test_content/TestContentClasses.py
> Add xsiam version

- CHANGELOG.md
- demisto_sdk/commands/generate_unit_tests/generate_unit_tests.py
- demisto_sdk/commands/generate_unit_tests/test_case_builder.py
fixes: [link to the issue](https://github.com/demisto/demisto-sdk/issues/2343)
Bug fix 
> bug fix generate unit tests

- demisto_sdk/commands/lint/lint_manager.py
> remove mypy from report

- demisto_sdk/commands/common/schemas/integration.yml
> Update integration schema video

- .circleci/config.yml
> fixing neo4 install

- .circleci/config.yml
> fix neo4j installation

- demisto_sdk/commands/content_graph/objects/content_item.py
- demisto_sdk/commands/content_graph/objects/pack.py
- demisto_sdk/commands/content_graph/objects/relationship.py
> docstrings for methods

- CHANGELOG.md
- demisto_sdk/commands/split/ymlsplitter.py
fixes an issue where ymlsplitter failed due to an unexpected __init__ argument
> allow unexpected arguments to ymlsplitter

- CHANGELOG.md
- README.md
- demisto_sdk/commands/common/tools.py
> ignore content repo warning

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4574)
it fixed we can see here https://app.circleci.com/pipelines/github/demisto/content/206809/workflows/db3f3364-48fc-4041-893d-bda01424955f/jobs/597651 from this pr https://github.com/demisto/content/pull/22225
> added handling for json images

- demisto_sdk/commands/common/docker_helper.py
- demisto_sdk/tests/constants_test.py
> refactor path

- demisto_sdk/commands/common/tools.py
> save parsing rules to get type from path

- CHANGELOG.md
- demisto_sdk/commands/zip_packs/packs_zipper.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4134
> Upload failed without explaining the reason

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/integration.yml
Removed the possible values from the category enum in **integration.yml** as there's a particular validation for it.
> Update integration.yml schema

- CHANGELOG.md
- demisto_sdk/commands/content_graph/common.py
- demisto_sdk/commands/content_graph/objects/__init__.py
- demisto_sdk/commands/content_graph/objects/pack.py
- demisto_sdk/commands/content_graph/objects/xdrc_template.py
- demisto_sdk/commands/content_graph/parsers/__init__.py
- demisto_sdk/commands/content_graph/parsers/pack.py
- demisto_sdk/commands/content_graph/parsers/xdrc_template.py
- demisto_sdk/commands/create_artifacts/content_artifacts_creator.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4495
Added support for xdrctemplate to content graph.
> Added support for xdrctemplate to content graph.

- CHANGELOG.md
- demisto_sdk/commands/common/MDXServer.py
- demisto_sdk/commands/common/docker_helper.py
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/tests/test_linter/docker_runner_test.py
fixes: [(#2487)](https://github.com/demisto/demisto-sdk/issues/2487)
> lazy load the docker helper

- .circleci/config.yml
https://github.com/actions/runner-images/issues/1983
> neo4j installation fixed

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
> Fixed docker rn update fix suggestion

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/cpu_count.py
- demisto_sdk/commands/common/tests/cpu_count_test.py
- demisto_sdk/commands/common/update_id_set.py
fixes: build resources issues
since we are running in a single machine we can’t use "all" the available cpus so we need to be able to decrease it.
> added cpu_count function

- demisto_sdk/commands/content_graph/parsers/repository.py
fixes: build resources issues
related: https://github.com/demisto/demisto-sdk/pull/2519
> added cpu limitation

- CHANGELOG.md
- demisto_sdk/commands/validate/validate_manager.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4731)
Update release notes on modeling rules failed when changing only xif file. 
The bug created after changing modeling rules xif file type from: FileType.XIF_FILE to: FileType.MODELING_RULE_XIF
> Update release notes fix

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/tests_data/modeling_rules_yml_mock.yml
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: [CIAC-4561](https://jira-hq.paloaltonetworks.local/browse/CIAC-4561)
The issue was that the description wasn't extracted because the file wasn't related to any of the options in *get_file_description*.
> fixes for RN with modeling rules

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/modeling_rule.py
- demisto_sdk/commands/common/tests/modeling_rules_test.py
Fixed an issue where the validtion passed although it found the error MR103
> Fix MR103 validation bug

- CHANGELOG.md
- demisto_sdk/commands/validate/validate_manager.py
The validation on modeling rules xif file failed since there is no validations for xif files. 
> Validate modeling rules fix

- CHANGELOG.md
- demisto_sdk/commands/common/content/objects/pack_objects/trigger/trigger.py
- demisto_sdk/commands/common/content/objects/pack_objects/xsiam_dashboard/xsiam_dashboard.py
- demisto_sdk/commands/common/content/objects/pack_objects/xsiam_report/xsiam_report.py
> Support from/to version in XSIAM triggers

- demisto_sdk/commands/content_graph/objects/content_item.py
> fix modeling rule prepare for upload

- demisto_sdk/commands/content_graph/interface/neo4j/import_utils.py
#2451 was merged between the CI step of #2561 and its merging.
> fix pyupgrade

- demisto_sdk/commands/content_graph/interface/neo4j/queries/constraints.py
- demisto_sdk/commands/content_graph/parsers/classifier.py
- demisto_sdk/commands/content_graph/parsers/mapper.py
- demisto_sdk/commands/content_graph/parsers/playbook.py
> graph - set fields/types as optional deps

- demisto_sdk/commands/content_graph/interface/neo4j/queries/dependencies.py
- demisto_sdk/commands/content_graph/parsers/incident_type.py
- demisto_sdk/commands/content_graph/parsers/indicator_type.py
> graph - set more dependencies as optional

- demisto_sdk/__main__.py
- demisto_sdk/commands/content_graph/content_graph_builder.py
- demisto_sdk/commands/content_graph/content_graph_commands.py
- demisto_sdk/commands/content_graph/interface/graph.py
- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
> graph - create graph with dependencies

- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
- demisto_sdk/commands/content_graph/objects/content_item.py
- demisto_sdk/commands/content_graph/objects/pack.py
This is for perfomance, figures that it really slow in search
> graph - handle fix for marketplace in summary 

- demisto_sdk/commands/content_graph/parsers/mapper.py
> mapper parser fix

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/tools.py
fix for the cases where the validations are tested from external repos
> categories validations fix

- demisto_sdk/commands/content_graph/interface/neo4j/queries/import_export.py
> fix in import export

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/download/downloader.py
- demisto_sdk/commands/download/tests/downloader_test.py
- demisto_sdk/commands/download/tests/tests_data/custom_content/automation-TestScript.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-18812
fixed an issue where custom scripts names were replaced with uuids.
> Custom Scripts in IncidentFields and Layouts

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/content_item.py
- demisto_sdk/commands/create_artifacts/tests/content_artifacts_creator_test.py
Revert https://github.com/demisto/demisto-sdk/pull/2568
> Revert x2 fields

- demisto_sdk/commands/content_graph/interface/neo4j/queries/common.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/dependencies.py
> graph - fix in deps calc

- demisto_sdk/commands/content_graph/common.py
> fix mapper server name

- demisto_sdk/commands/content_graph/common.py
> add mapper to server_names

- demisto_sdk/commands/content_graph/common.py
- demisto_sdk/commands/content_graph/objects/generic_field.py
- demisto_sdk/commands/content_graph/objects/generic_type.py
- demisto_sdk/commands/content_graph/parsers/content_item.py
- demisto_sdk/commands/content_graph/parsers/generic_field.py
- demisto_sdk/commands/content_graph/parsers/pack.py
> fixed TIR issues in graph

- poetry.lock
- pyproject.toml
orjson was used, but missing from pyproject.toml
> add missing orjson dependency

- demisto_sdk/commands/content_graph/objects/generic_field.py
- demisto_sdk/commands/content_graph/objects/generic_type.py
- demisto_sdk/commands/content_graph/objects/script.py
- demisto_sdk/commands/content_graph/objects/xsiam_dashboard.py
> fix dump methods in graph

- demisto_sdk/commands/content_graph/objects/content_item.py
> fix normalizename in models

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/content_graph/objects/integration.py
- demisto_sdk/commands/content_graph/objects/script.py
- demisto_sdk/commands/prepare_content/README.md
- demisto_sdk/tests/integration_tests/unify_integration_test.py
change nativeImage to nativeimage (lowercase)
> change nativeImage to nativeimage (lowercase)

- demisto_sdk/commands/content_graph/neo4j_service.py
* Check if APOC is installed. If installed properly, proceed.
* If APOC is not installed, download it to the plugins folder before starting the service.
> APOC installation improvements

- demisto_sdk/commands/content_graph/parsers/integration.py
> Fix get_code of integration in IntegrationParser

- CHANGELOG.md
- demisto_sdk/commands/download/downloader.py
- demisto_sdk/commands/download/tests/downloader_test.py
fixes: https://github.com/demisto/demisto-sdk/issues/2622
> fix download layout bug

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/integration_test.py
Changed the **validate** command to fail on the IN145 error code only when the parameter with type 4 is not hidden.
> Update the IN145 error

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4903)
Updated validate and update-release_notes to skip Triggers
> Remove Trigger recommendation from RN

- demisto_sdk/commands/content_graph/neo4j_service.py
> Health check in neo4j start with docker

- demisto_sdk/commands/common/hook_validations/release_notes.py
- demisto_sdk/commands/common/tests/test_files/rn_header_test_data
> Updated the RN regex to support 'New' in special forms

- .git-blame-ignore-revs
> Update .git-blame-ignore-revs - black

- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/release_notes.py
- demisto_sdk/commands/common/tools.py
> Fix RN headers issue

- CHANGELOG.md
> Fix CHANGELOG.

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/integration_test.py
As a result of [this PR](https://github.com/demisto/demisto-sdk/pull/2637), I later realized that it should support other types of hidden parameters (not just type 4).
> Update the IN124 error

- demisto_sdk/commands/content_graph/objects/base_content.py
- demisto_sdk/commands/content_graph/objects/integration.py
- demisto_sdk/commands/content_graph/parsers/integration.py
- demisto_sdk/commands/lint/tests/helper_test.py
> [content models] fix integrationparser to have commands

- CHANGELOG.md
- poetry.lock
- pyproject.toml
> 1.8.3 release

- demisto_sdk/commands/common/git_util.py
> fix get all changed pack ids

- demisto_sdk/commands/test_content/TestContentClasses.py
> fix sdk get identifier

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/content_item.py
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-20075
> YAML width of content items

- demisto_sdk/__main__.py
> Content graph - convert packs to list

- CHANGELOG.md
- demisto_sdk/__main__.py
> Fixed native images description typos

- CHANGELOG.md
- demisto_sdk/commands/common/tools.py
fixes: [CIAC-5009](https://jira-hq.paloaltonetworks.local/browse/CIAC-5009)
added warning to **get_demisto_version** to inform users the version parsing didn't work.
> added warning to **get_demisto_version**

- docs/release_guide.md
> Add push branch step to Pre-release

- demisto_sdk/commands/content_graph/interface/neo4j/queries/dependencies.py
- demisto_sdk/commands/content_graph/objects/relationship.py
- demisto_sdk/commands/content_graph/tests/create_content_graph_test.py
related: https://jira-hq.paloaltonetworks.local/browse/CIAC-5194
> content graph - add is_test property to DEPENDS_ON

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/classifier.yml
- demisto_sdk/commands/common/schemas/dashboard.yml
- demisto_sdk/commands/common/schemas/incidentfield.yml
- demisto_sdk/commands/common/schemas/incidenttype.yml
- demisto_sdk/commands/common/schemas/indicatorfield.yml
- demisto_sdk/commands/common/schemas/layoutscontainer.yml
- demisto_sdk/commands/common/schemas/mapper.yml
- demisto_sdk/commands/common/schemas/reputation.yml
> added marketplace tag to to schema

- demisto_sdk/commands/common/errors.py
Reverts demisto/demisto-sdk#2645
> Revert "Added BA114 to ignore list"

- CHANGELOG.md
- poetry.lock
- pyproject.toml
> sdk 1.9.0 release

- CHANGELOG.md
- demisto_sdk/commands/validate/validate_manager.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5382)
> bug - renamed files returnes a tuple

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/content_item.py
Explicitly specifying the argument (fix to https://github.com/demisto/demisto-sdk/pull/2675)
> Fix YAML_width 50000

- CHANGELOG.md
- demisto_sdk/commands/content_graph/interface/neo4j/queries/dependencies.py
Skip collecting test dependencies in all level packs
> skip test dependencies in all level

- .pre-commit-config.yaml
https://github.com/PyCQA/isort/issues/2077 reproduced [on CircleCI](https://app.circleci.com/pipelines/github/demisto/demisto-sdk/21094/workflows/49209d38-afdf-4b3e-a213-4b0b8fe44dd7/jobs/158473)
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5455
> fix isort installation error

- CHANGELOG.md
- demisto_sdk/commands/upload/uploader.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5458
The overwriting message will ask about XSOAR when uploading a pack to XSIAM
Before the fix:
After the fix:
> fixed the upload overwrite message

- demisto_sdk/commands/content_graph/interface/neo4j/queries/nodes.py
> make update graph faster

- demisto_sdk/commands/content_graph/tests/graph_validator_test.py
> graph validator testfix

- .circleci/config.yml
- demisto_sdk/commands/content_graph/content_graph_commands.py
- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/dependencies.py
* Removed marketplace property of relationships
* Fix validate all with graph
* Don't import graph when not needed.
> graph import fix

- .circleci/config.yml
> update graph CI

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/content_item.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5669
> handle marketplace in dumping content objects

- CHANGELOG.md
- demisto_sdk/commands/generate_docs/generate_integration_doc.py
> Add "version" to README

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/graph_validator.py
- demisto_sdk/commands/content_graph/interface/graph.py
- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/validations.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5616
* GR100 will now run on all content items of changed packs.
* GR101 and GR102 will now catch invalid fromversion/toversion of files **using** the changed items.
> Fix graph validator

- CHANGELOG.md
- demisto_sdk/commands/common/MDXServer.py
- demisto_sdk/commands/common/hook_validations/readme.py
not being able to run server locally shouldnt be a warning, it should be reccomended to run with docker
dont print npm modules to secho
always set NODE_PATH variable in format as well as validate
> always use module

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/graph_validator.py
- demisto_sdk/commands/content_graph/tests/graph_validator_test.py
Relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-5641
Make GR103 fail when running validate with `-i` or `-g`.
> fail GR103 on modified files

- .github/pull_request_template.md
> pull_request_template trailing whitespace

- demisto_sdk/commands/content_graph/objects/content_item.py
- demisto_sdk/commands/prepare_content/preparers/marketplace_suffix_preparer.py
Fixing [this error](https://code.pan.run/xsoar/content/-/jobs/22055253#L5164) (found in the [1.10.3 release content PR](https://github.com/demisto/content/pull/24745))
[test run](https://code.pan.run/xsoar/content/-/pipelines/4653448)
> Fix MarketplaceSuffixReplacer boolean key error

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/lint/README.md
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/tests/test_linter/gather_facts_test.py
> add_support_for_multiple_dockers_in_lint

- CONTRIBUTION.md
- demisto_sdk/commands/generate_yml_from_python/README.md
> Fix broken links

- .circleci/config.yml
- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
Adding the graph zips to the artifacts to debug easier on failures
fixes:
> add graph zip to artifacts

- CHANGELOG.md
- demisto_sdk/commands/doc_reviewer/rn_checker.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5762
> RN checker: Do not require dot for new items

- CHANGELOG.md
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5720
fixes: https://github.com/demisto/demisto-sdk/issues/2782
> fix kebab case

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/layout.py
Added support for new supported section in XSIAM layouts.
> validation fix

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/integration_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5481
Fixed the Feed Integration validation for the Collect/Connect section
> Fixed validation in feeds integration for collect/connect sections

- .github/CODEOWNERS
> Add myself as validations code owner.

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/download/downloader.py
- demisto_sdk/commands/generate_outputs/json_to_outputs/json_to_outputs.py
- demisto_sdk/commands/run_cmd/runner.py
- demisto_sdk/commands/update_xsoar_config_file/update_xsoar_config_file.py
- demisto_sdk/tests/integration_tests/generate_docs_integration_test.py
- demisto_sdk/tests/integration_tests/run_integration_test.py
- demisto_sdk/tests/integration_tests/unify_integration_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6075
fixes: https://github.com/demisto/demisto-sdk/pull/2850
> Undisable logging

- demisto_sdk/commands/upload/README.md
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5436
> Update upload command docs

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/pack.py
- demisto_sdk/commands/content_graph/parsers/pack.py
This PR fixes the fix that was merged [here](https://github.com/demisto/demisto-sdk/pull/2858) because it breaks for other packs that does have content items.
> Fix server_min_version in metadata

- CHANGELOG.md
- demisto_sdk/__main__.py
fixes:https://jira-hq.paloaltonetworks.local/browse/CIAC-6120
> Fix Logging Color

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/playbook.py
- demisto_sdk/tests/test_files/playbook_valid_inputs.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5940
- Updated the regex value in **collect_all_inputs_in_use** method to `inputs\.[-\W|\w ].*` in order to get all the text after `inputs.` include special characters.
- Added to **playbook_valid_inputs.yml** the input `Is automated blocking activated ?` for testing.
> Fix PB validation for inputs

- CHANGELOG.md
- demisto_sdk/commands/upload/uploader.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6130
> Logging Input Prompt

- .sourcery.yaml
Mostly for limiting the python version
> add sourcery config

- .pre-commit-config.yaml
- demisto_sdk/__main__.py
- demisto_sdk/commands/pre_commit/.pre-commit-config_template.yaml
- demisto_sdk/commands/pre_commit/pre_commit_command.py
> Fix main pre commit

- CHANGELOG.md
- demisto_sdk/commands/common/docker_helper.py
- demisto_sdk/commands/lint/resources/installation_scripts/python_image.sh
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6164
remove progress bar from installation when installing test-requirements in containers.
> [lint] - remove progress bar when installing packs inside containers

- demisto_sdk/__main__.py
- demisto_sdk/commands/lint/linter.py
> Fix run unit tests command

- demisto_sdk/__main__.py
- demisto_sdk/commands/pre_commit/hooks/run_unit_tests.py
- demisto_sdk/commands/pre_commit/pre_commit_command.py
fixes:
In addtion, delete for now the native image flag
> Fix validate and format in pre-commit

- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5215
> git add correctly in update-rn

- demisto_sdk/commands/common/tools.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-537
> get yaml - clear cache

- CHANGELOG.md
- pyproject.toml
> SDK Release 1.13.0

- CHANGELOG.md
- demisto_sdk/commands/secrets/secrets.py
- demisto_sdk/commands/secrets/tests/secrets_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4845
> add xif to secrets detection

- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4661
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4701
> get file fix

- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_integration.py
- demisto_sdk/commands/format/update_playbook.py
- demisto_sdk/commands/format/update_script.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5707
> fix format fromversion bug

- demisto_sdk/__main__.py
- demisto_sdk/commands/common/tools.py
> check last remote version even if CI

- CHANGELOG.md
- demisto_sdk/commands/lint/linter.py
> Run Linter on Docker

- CHANGELOG.md
- demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
- demisto_sdk/commands/test_content/xsiam_tools/xsiam_client.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6333
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6318
Change logs not to spam us with requests failure that are by design. 
Added types comparison to test data validation.
> Improve test modeling rules logs

- demisto_sdk/commands/pre_commit/.pre-commit-config_template.yaml
- demisto_sdk/commands/pre_commit/pre_commit_command.py
fixes:
* Mypy does not support "site-packages" imports in the import
> fix MYPYPATH in demisto-sdk precommit

- demisto_sdk/commands/common/legacy_git_tools.py
instead of calling `git` every time, keep a cache
> lru cache for git_path()

- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6360
> Fix log error - master unreachable

- README.md
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22935
> [README] Doc internet conection

- demisto_sdk/commands/run_cmd/runner.py
- demisto_sdk/commands/run_cmd/tests/runner_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-23185
fixes: https://github.com/demisto/demisto-sdk/issues/2885
Added a fix for the playground search so we will review all the playgrounds, not just the first page.
> Added paging to playground search in run command

- CHANGELOG.md
- demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6355
Fail modeling rules test command if no testdata
https://github.com/demisto/content/pull/26111
> Fail modeling rules if no testdata

- demisto_sdk/commands/test_content/TestContentClasses.py
Added servers 6.10, 6.11 to update build machines
> added 6.10 to servers

- CHANGELOG.md
- pyproject.toml
> SDK Release

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6439
> Fix rn command on deprecated integrations not containing commands

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/playbook.py
- demisto_sdk/commands/validate/README.md
- demisto_sdk/tests/test_files/playbook_valid_inputs.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6344
- Updated the regex value in collect_all_inputs_in_use method to `inputs\.[-\w ?!():]+`
- Added to playbook_valid_inputs.yml 3 cases
> Fix pb inputs validation

- CHANGELOG.md
- demisto_sdk/commands/pre_commit/pre_commit_command.py
> fix mypypath in precommit

- CONTRIBUTION.md
added pre commits installation docs
> Update CONTRIBUTION - `pre-commit` instructions

- demisto_sdk/commands/test_content/timestamp_replacer.py
removed demisto_sdk import from timestamp_replacer.py
> removed demisto_sdk import from timestamp_replacer.py

- demisto_sdk/commands/content_graph/interface/neo4j/queries/nodes.py
- demisto_sdk/commands/content_graph/tests/update_content_graph_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5733?filter=-1
This fixes the inconsistnecy problems when we return the perserved relationships
This will make sure that the source id we preserved is the same node we want to preservere.
> fix update issues

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/layout.py
https://github.com/demisto/demisto-sdk/pull/2899
```
"indicatorsDetails": {
"tabs": null
},
```
val.get("tabs", []) returns None here
> validation error

- demisto_sdk/commands/pre_commit/pre_commit_command.py
> support running precommit from subdir

- demisto_sdk/commands/content_graph/content_graph_commands.py
- demisto_sdk/commands/content_graph/interface/graph.py
- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6521
Marshalling the graph validates the graph in bucket is in the same schema of the SDK models.
> marshal graph before update the graph

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/pre_commit/pre_commit_command.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6523?filter=-2
fixes: https://github.com/demisto/demisto-sdk/issues/2985
> add staged only flag in pre-commit

- CHANGELOG.md
- demisto_sdk/commands/run_unit_tests/unit_tests_runner.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6537
> support test data in unit-test-runner

- CHANGELOG.md
- demisto_sdk/commands/common/git_util.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6540
> fix get all changed files gitutil

- CHANGELOG.md
- demisto_sdk/commands/pre_commit/.pre-commit-config_template.yaml
> no flake8 in precommit

- demisto_sdk/commands/run_unit_tests/pytest_runner.sh
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6555
Add hypothesis module (advanced testing tools) to run-unit-test runner
> add hypothesis module to run-unit-tests command

- CHANGELOG.md
- demisto_sdk/commands/run_unit_tests/pytest_runner.sh
> remove pytest pretty from run-unit-tests

- CHANGELOG.md
- demisto_sdk/commands/format/update_generic.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6623?filter=-2
> fix format logger issue

- demisto_sdk/commands/format/update_generic.py
> update generic fix v2

- CHANGELOG.md
- demisto_sdk/commands/common/docker_helper.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/import_export.py
> remove gitlab prefix when query to API

- CHANGELOG.md
- demisto_sdk/commands/run_unit_tests/pytest_runner.sh
> run-unit-tests python2 support

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/pre_commit/pre_commit_command.py
- demisto_sdk/commands/pre_commit/tests/pre_commit_test.py
- pytest.ini
fixes:
Filter the input files with the git files, so we will not validate and fix code which is in gitignore
> fix input flag in pre-commit

- CHANGELOG.md
- demisto_sdk/commands/content_graph/interface/neo4j/queries/nodes.py
- demisto_sdk/commands/content_graph/tests/create_content_graph_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6671
test before fix fails:
after the fix, it passes.
> fix create nodes query

- CHANGELOG.md
> moved changelog note

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/pack.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6733
> fix `upload -z`

- demisto_sdk/commands/content_graph/parsers/pack.py
> remove xpanse from default marketplaces

- CHANGELOG.md
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_integration.py
fixes: [link](https://jira-hq.paloaltonetworks.local/browse/CIAC-4665) to issue
> Fix: format sets default reputation command wrong

- CHANGELOG.md
- demisto_sdk/commands/format/update_generic.py
Fixed an issue where **format** not working properly using the `-y`/`--assume-yes` flag on the json file.
> [format] Fix issue using the '-y' flag

- .github/workflows/link_edited_pr_to_jira_issue.yml
> link pr to jira fix

- CHANGELOG.md
- demisto_sdk/commands/content_graph/parsers/mapper.py
fixes: https://github.com/demisto/demisto-sdk/issues/3066
> none type error

- CHANGELOG.md
- demisto_sdk/commands/validate/validate_manager.py
> Fix all files from git in validate_graph

- demisto_sdk/commands/run_unit_tests/unit_tests_runner.py
> better error handling coverage report

- CHANGELOG.md
- demisto_sdk/commands/pre_commit/.pre-commit-config_template.yaml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6744
> add markdownlint to precommit

- CHANGELOG.md
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/content_graph/objects/exceptions.py
- demisto_sdk/commands/content_graph/objects/pack.py
- demisto_sdk/commands/upload/exceptions.py
- demisto_sdk/commands/upload/uploader.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6781
> Fix upload on packs without -z

- demisto_sdk/commands/pre_commit/pre_commit_command.py
- demisto_sdk/commands/run_unit_tests/unit_tests_runner.py
> Run unit tests: keep .coverage files

- .pre-commit-hooks.yaml
- demisto_sdk/commands/pre_commit/.pre-commit-config_template.yaml
fixes:
Make validate, format to run on all content items
> fix format, validate hooks files

- CHANGELOG.md
- demisto_sdk/commands/common/logger.py
- demisto_sdk/commands/generate_outputs/generate_outputs_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6813
> Log File Notification

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/classifier.py
- demisto_sdk/commands/common/hook_validations/mapper.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/format/update_mapper.py
- demisto_sdk/commands/lint/linter.py
fixes: https://github.com/demisto/demisto-sdk/pull/2899
> internalMapping or {}

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/base_content.py
- demisto_sdk/commands/content_graph/parsers/content_item.py
- demisto_sdk/commands/content_graph/parsers/pack.py
- demisto_sdk/commands/validate/validate_manager.py
> exception handling in content item parser

- CHANGELOG.md
- demisto_sdk/commands/upload/tests/uploader_test.py
- demisto_sdk/commands/upload/upload.py
> Upload: fix using the same directory for uploadable_packs.zip

- CHANGELOG.md
- demisto_sdk/commands/common/logger.py
Remove an extra levelname.
fixes:
> Remove Extra levelname

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/pack.py
- demisto_sdk/commands/upload/uploader.py
> Upload: Skip version check in XSIAM

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/pack.py
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24593?filter=-1
> Upload: fix missing version in metadata.json

- demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
remove un-relevant log statement
> Modeling-Rules - remove unused statement

- CHANGELOG.md
- demisto_sdk/commands/init/contribution_converter.py
- demisto_sdk/commands/init/tests/contribution_converter_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6855
> Contribution Release Notes replace bug fix

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/tests/base_validator_test.py
- demisto_sdk/commands/common/tests/field_validator_test.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/common/tests/structure_test.py
- demisto_sdk/commands/content_graph/tests/graph_validator_test.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
> Duplicate Levelname

- demisto_sdk/commands/lint/linter.py
> moved removing container to finally

- demisto_sdk/commands/common/MDXServer.py
> Silence MDX Server logs

- CHANGELOG.md
- demisto_sdk/commands/lint/commands_builder.py
- demisto_sdk/commands/lint/tests/command_builder_test.py
- demisto_sdk/commands/run_unit_tests/.pytest.ini
- demisto_sdk/commands/run_unit_tests/pytest_runner.sh
- demisto_sdk/commands/run_unit_tests/unit_tests_runner.py
fixes:https://jira-hq.paloaltonetworks.local/browse/CIAC-6788
Fixed pytest async io deprecation warning
> Fixed pytest async io deprecation warning

- CHANGELOG.md
- demisto_sdk/commands/content_graph/neo4j_service.py
- demisto_sdk/commands/run_unit_tests/unit_tests_runner.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6956
Docker default will run on root users. Change it to run on default
> Fix permissions issues in Docker

- Packs/FeedAzureValid/ReleaseNotes/1_0_1.md
- demisto_sdk/commands/common/tests/update_id_set_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/content_graph/objects/base_content.py
- demisto_sdk/commands/content_graph/objects/content_item.py
- demisto_sdk/commands/content_graph/parsers/pack.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24892?filter=-1
> Graph objects: safer loading 

- CHANGELOG.md
- demisto_sdk/commands/common/logger.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6965
> Add timestamp to logging mesages when running in CI

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/correlation_rule.py
- demisto_sdk/commands/common/hook_validations/xsiam_dashboard.py
- demisto_sdk/commands/validate/tests/validators_test.py
fixes:
fixed an issue where validate always returned files of type xsiam dashboards and correlation rules as valid files
> fix validate xsiam entities bug 

- demisto_sdk/scripts/update_additional_dependencies.py
> Fix update additional dependencies script

- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/tests/test_files/test_playbook_value_starting_with_equal_sign.yaml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7117
> Tools: fix get file or remote file function in tools

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/pre_process_rule.py
- demisto_sdk/commands/upload/exceptions.py
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25549
> Fix preprpocess rule upload error message

- CHANGELOG.md
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/upload/tests/uploader_test.py
- demisto_sdk/commands/upload/uploader.py
- demisto_sdk/tests/integration_tests/upload_integration_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6663
before the change:
after the change:
> fix error message when API key is invalid

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/content_graph/objects/integration.py
- demisto_sdk/commands/content_graph/parsers/integration.py
- demisto_sdk/commands/content_graph/tests/parsers_and_models_test.py
- demisto_sdk/commands/content_graph/tests/test_data/integration.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7176
- Added support to `isfetcheventsandassets` flag in content graph.
> added support to fetch assets flag in content graph

- demisto_sdk/commands/test_content/Docker.py
- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/constants.py
- demisto_sdk/commands/test_content/execute_test_content.py
- demisto_sdk/commands/test_content/tests/build_context_test.py
related: https://github.com/demisto/content/pull/23690
change the logic to disable the tunnel usage.
> migrate to gcloud

- CHANGELOG.md
- pyproject.toml
> release 1.17.1

- .circleci/config.yml
- CHANGELOG.md
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/content_graph/content_graph_builder.py
- demisto_sdk/commands/content_graph/parsers/repository.py
- demisto_sdk/commands/content_graph/tests/create_content_graph_test.py
- demisto_sdk/commands/content_graph/tests/graph_validator_test.py
- demisto_sdk/commands/content_graph/tests/parsers_and_models_test.py
- demisto_sdk/commands/content_graph/tests/prepare_content_graph_test.py
- demisto_sdk/commands/content_graph/tests/update_content_graph_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7283
This PR should consume less memory when parsing the content graph
> make create/update content graph more memory efficient

- .pre-commit-config.yaml
- .pre-commit-hooks.yaml
- demisto_sdk/scripts/update_additional_dependencies.py
> use update additional dependencies hook

- .circleci/config.yml
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/coverage_analyze/tests/helpers_test.py
- demisto_sdk/commands/create_artifacts/tests/content_artifacts_creator_test.py
- demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7355
> Removed paralelism of unit tests and skipped tests

- .circleci/config.yml
fixes:https://jira-hq.paloaltonetworks.local/browse/CIAC-7359
> remove empty lines from TEST_FILES

- CHANGELOG.md
- demisto_sdk/commands/content_graph/parsers/list.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-87354
Add support for List content item for the Xpanse marketplace
> Added support for list in Xpanse marketplace

- CHANGELOG.md
- demisto_sdk/commands/run_unit_tests/unit_tests_runner.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7395
> Fix run unit-tests in powershell

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/docker_helper.py
- demisto_sdk/commands/common/hook_validations/docker.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7400
Before pulling from remote, we check that the Docker Image does not exist locally.
> Run on local docker if exist

- CHANGELOG.md
- TestSuite/yml.py
- demisto_sdk/commands/common/handlers/yaml/ruamel_handler.py
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/hook_validations/correlation_rule.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/content_graph/objects/content_item.py
- demisto_sdk/commands/content_graph/parsers/yaml_content_item.py
- demisto_sdk/commands/format/update_generic.py
- demisto_sdk/commands/prepare_content/integration_script_unifier.py
- demisto_sdk/commands/prepare_content/tests/yml_unifier_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7455
Don't use round trip YAML loading in content parser and in `find_type`
https://code.pan.run/xsoar/content/-/pipelines/5785943
> faster yaml loading

- CHANGELOG.md
- demisto_sdk/commands/split/tests/ymlsplitter_test.py
- demisto_sdk/commands/split/ymlsplitter.py
- demisto_sdk/tests/test_files/integration-Zoom-no-trailing-newline.yml
- demisto_sdk/tests/test_files/integration-Zoom.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7464
> Regex fix to remove all types of pack versions

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7189
Run pack's validations on marketplaces change
Was checked locally:
Run on a pack_metadata change that was not marketplaces: not validated pack's files
Run on a pack_metadata change that was marketplaces: validated all pack's files
Run on a pack_metadata change and integration change: validated all pack's files and the integration only once.
> Run pack's validations on marketplaces change

- CHANGELOG.md
- demisto_sdk/commands/common/tests/dependencies_test.py
- tests_end_to_end/test_e2e_demisto_sdk_flow_playbook.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7085
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-3905
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-7487
Tests are now deterministic.
> Remove Random Chaos from Tests

- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7203
> Added indentation to the BC RN notes

- demisto_sdk/commands/generate_yml_from_python/tests/generate_yml_from_python_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6954
> replaced `load_module` -> `exec_module` to remove deprecation warning

- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/content_graph/tests/create_content_graph_test.py
- demisto_sdk/commands/content_graph/tests/graph_validator_test.py
- demisto_sdk/commands/content_graph/tests/prepare_content_graph_test.py
- demisto_sdk/commands/content_graph/tests/update_content_graph_test.py
- demisto_sdk/commands/create_id_set/tests/create_id_set_test.py
- demisto_sdk/commands/download/tests/downloader_test.py
- demisto_sdk/commands/prepare_content/tests/yml_unifier_test.py
- demisto_sdk/commands/test_content/tests/timestamp_replacer_test.py
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7087
> fixed tests format to remove old deprecated nose format

- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/pre_commit/pre_commit_command.py
- demisto_sdk/commands/upload/uploader.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7050
changed the logic in `string_to_bool` to be more simple.
removed `str2bool` calls.
> added a single `string_to_bool` function for all the relevant places in sdk

- CHANGELOG.md
- demisto_sdk/__main__.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6676
Make the pack known words file default to true
> doc review run with pack known words as desault true

- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/download/downloader.py
> remove type file arg from get_file

- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/download/tests/downloader_test.py
- demisto_sdk/commands/upload/uploader.py
- demisto_sdk/commands/validate/validate_manager.py
fixes:
Regarding [this](https://github.com/demisto/demisto-sdk/pull/3363) PR  we should remove the all places we called the get_file function.
> remove file type in get_file

- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/classifier.py
- demisto_sdk/commands/common/hook_validations/content_entity_validator.py
- demisto_sdk/commands/common/hook_validations/field_base_validator.py
- demisto_sdk/commands/common/hook_validations/id.py
- demisto_sdk/commands/common/hook_validations/incident_type.py
- demisto_sdk/commands/common/hook_validations/indicator_field.py
- demisto_sdk/commands/common/hook_validations/job.py
- demisto_sdk/commands/common/hook_validations/layout.py
- demisto_sdk/commands/common/hook_validations/lists.py
- demisto_sdk/commands/common/hook_validations/mapper.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/hook_validations/pre_process_rule.py
- demisto_sdk/commands/common/hook_validations/reputation.py
- demisto_sdk/commands/common/hook_validations/widget.py
- demisto_sdk/commands/common/tests/field_validator_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/format/update_generic_json.py
- demisto_sdk/commands/format/update_widget.py
- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/update_release_notes/update_rn.py
fix LooseVersion DeprecationWarning
> fix LooseVersion DeprecationWarning

- CHANGELOG.md
- demisto_sdk/commands/common/native_image.py
- demisto_sdk/commands/common/tests/native_image_test.py
- demisto_sdk/tests/integration_tests/unify_integration_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7531
> Remove candidate from nativeimage key

- demisto_sdk/commands/test_content/tests/timestamp_replacer_test.py
- demisto_sdk/commands/test_content/timestamp_replacer.py
> fix the mock process

- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/validate/validate_manager.py
following https://github.com/demisto/demisto-sdk/pull/3402
> remove unused code

- demisto_sdk/commands/content_graph/interface/neo4j/import_utils.py
- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/dependencies.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/nodes.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/relationships.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/validations.py
- demisto_sdk/commands/content_graph/objects/base_content.py
- demisto_sdk/commands/content_graph/objects/relationship.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6953
> fixed deprecation warning for graph test

- CHANGELOG.md
- demisto_sdk/commands/format/update_genericdefinition.py
- demisto_sdk/commands/format/update_indicatorfields.py
- demisto_sdk/commands/format/update_pack_metadata.py
- demisto_sdk/commands/format/update_report.py
- demisto_sdk/commands/prepare_content/integration_script_unifier.py
> Fix logging colors

- CHANGELOG.md
https://github.com/demisto/demisto-sdk/pull/3422
> added a change log

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/doc_reviewer/tests/doc_reviewer_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6521
Fix the behavior of the --use-pack-known-words parameter
> fixed the pack_known_words_functionality

- CHANGELOG.md
move unreleased feature to unreleased section in CHANGELOG
> move to unreleased section

- demisto_sdk/__main__.py
- demisto_sdk/commands/content_graph/commands/update.py
fixes: https://code.pan.run/xsoar/content/-/jobs/30570915
> graph cmds invoke fix

- demisto_sdk/commands/content_graph/commands/update.py
fixed an issue where an exception was raised in logging setup in case of graph update invoking graph create.
change passes against content https://code.pan.run/xsoar/content/-/pipelines/5978089
> fix graph update invoking create

- CHANGELOG.md
- demisto_sdk/commands/format/update_layout.py
- demisto_sdk/commands/format/update_mapper.py
fixes:
* Change the "raise ValueError" in case of unexpected result of graph.search() to logger.error.
* Added a check if the result of graph.search() is [].
> Updated the Handling of the Search Results in format

- demisto_sdk/commands/common/tools.py
Added logs to validate we are retrying fetch url when running get_url_with_retries.
> added logs to get_url_with_retries

- demisto_sdk/commands/generate_docs/generate_script_doc.py
fixes:
Removed unnecessary line from demisto_sdk/commands/generate_docs/generate_script_doc.py .
> Removed Unnecessary Line

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/content_graph/interface/graph.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7936?filter=-2
> ignore pycache in sha1 calculation

- .circleci/config.yml
- CHANGELOG.md
- demisto_sdk/commands/content_graph/interface/neo4j/queries/common.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/indexes.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/relationships.py
> removed chunks from relationships

- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/relationships.py
> Increase timeout in create relationships transaction

- .circleci/config.yml
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-7959
> increase machine type for graph generation

- tests_end_to_end/test_e2e_demisto_sdk_flow_playbook.py
fixes:
Use the `ChangeCWD` class in the tests:
- test_e2e_demisto_sdk_flow_playbook_testsuite
- test_e2e_demisto_sdk_flow_playbook_client
> Fix nightly tests

- .github/workflows/test_precommit.yml
- demisto_sdk/tests/workflow_test.py
npm install running without fund or audit.
> npm install running without fund or audit.

- demisto_sdk/__main__.py
related: https://jira-hq.paloaltonetworks.local/browse/CIAC-7707
> remove 3.8 warning

- CHANGELOG.md
- demisto_sdk/commands/lint/helpers.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8203
Fixes the following parsing issue:
https://code.pan.run/xsoar/content/-/jobs/32016112
> Logs parsing fix

- CHANGELOG.md
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8256
Fixed an issue where the **validate -g** failed when updating an empty `.pack-ignore` file when trying to retrieve its content from the local default branch.
> [validate] - fixed an issue with validate -g

- CHANGELOG.md
- demisto_sdk/commands/content_graph/content_graph_builder.py
- demisto_sdk/commands/content_graph/parsers/pack.py
- demisto_sdk/commands/content_graph/parsers/repository.py
fixes:
This will use TQDM to show status of content parasing, and move `logger.info` to `logger.debug`.
> Use TQDM in content parsing

- CHANGELOG.md
- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/relationships.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8251
successful test against content:
https://code.pan.run/xsoar/content/-/jobs/32334338
```
[2023-09-04 17:51:11,775] [ERROR] /builds/xsoar/content/Packs/QRadar/Classifiers/classifier-mapper-incoming-QRadar.json: [GR103] - Content item 'QRadar - Incoming Mapper' using content items: Dest NT DomainThisIsAVeryNiceTest which cannot be found in the repository.
```
> ensure unknown content names is not null

- .circleci/config.yml
- demisto_sdk/commands/lint/helpers.py
fixing the log file rotation in build system
> fixing the log file rotation in build system

- CHANGELOG.md
> moved changelog note under Unreleased

- CHANGELOG.md
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/common/tools.py
fixes: [CIAC-8281](https://jira-hq.paloaltonetworks.local/browse/CIAC-8281)
Fixed an issue where sentence end with period validation failed in case of multi-lines descriptions.
> Fixed an issue where sentence end with period validation failed in case of multi-lines descriptions.

- demisto_sdk/commands/common/tests/docker_test.py
- demisto_sdk/commands/test_content/TestContentClasses.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8264
> Mock deprecated images url

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/xsiamdashboard.yml
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-8214
> XSIAM Dashboards Lazy Load

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/content_entity_validator.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/script.py
- demisto_sdk/commands/common/tests/docker_test.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/common/tests/script_test.py
fixes:
Fixed an issue where **validate** falsly failed with error `DS108` on empty descriptions.
> Fixed an issue where **validate** falsly failed with error `DS108` on empty descriptions.

- CHANGELOG.md
- Packs/TestXSIAMPack/XSIAMDashboards/MyDashboard.json
- TestSuite/xsiam_dashboard.py
- demisto_sdk/commands/common/schemas/xsiamdashboard.yml
- demisto_sdk/commands/content_graph/tests/test_data/xsiam_dashboard.json
- demisto_sdk/commands/format/update_pythonfile.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8328
Added metadata field to xsiam dashboard
> added metadata to xsiam dashboard

- .circleci/config.yml
> decrease waiter time & resource_class

- .pre-commit-config.yaml
Use pyc black hook, ~2x faster
https://github.com/psf/black/pull/3828
> improve black performance

- CHANGELOG.md
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8355
> [validate] - Fixed an issue with empty .pack-ignore with newlines

- CHANGELOG.md
- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
Fix modeling rule type comparison
> Fix modeling rule type comparison

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/script.yml
- demisto_sdk/tests/test_files/script-valid.yml
https://github.com/demisto/demisto-sdk/pull/3601
https://code.pan.run/xsoar/content-internal-dist/-/jobs/32707488#L712
Fixed the engineinfo key format in the script eschema.
> Fixed the engineinfo key format in the script eschema.

- CHANGELOG.md
fixing changelog moving to unreleased
> fixing changelog moving to unreleased

- CHANGELOG.md
- Packs/TestXSIAMPack/XSIAMDashboards/MyDashboard.json
- TestSuite/xsiam_dashboard.py
- demisto_sdk/commands/common/schemas/xsiamdashboard.yml
- demisto_sdk/commands/content_graph/tests/test_data/xsiam_dashboard.json
Fixed the metadata type to map.
> Change metadata in XSIAM dashboard type to map

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/xsiamdashboard.yml
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-8214
> XSIAM Dashboards Cache TTL

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/content_entity_validator.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/common/tests/script_test.py
- demisto_sdk/commands/common/tools.py
fixes: [CIAC-8403](https://jira-hq.paloaltonetworks.local/browse/CIAC-8403)
Fixed an issue where **validate** falsely failed with error `DS108` on descriptions ending with question mark and exclamation mark.
> fix description ends with question / exclamation mark validation edge case

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/format/tests/test_formatting_generic_test.py
- demisto_sdk/commands/format/update_generic.py
fixes: issue [CIAC-8403](https://jira-hq.paloaltonetworks.local/browse/CIAC-8403)
#3656 
Fix an issue were format added a dot at end of the description that already ends  with question mark and exclamation mark.
> [Format] Fix CIAC-8403

- CHANGELOG.md
> re arrange changelog

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/content_graph/objects/integration.py
- demisto_sdk/commands/content_graph/parsers/integration.py
- demisto_sdk/commands/content_graph/tests/parsers_and_models_test.py
- demisto_sdk/commands/content_graph/tests/test_data/integration.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7176
This pr replaces this [pr](https://github.com/demisto/demisto-sdk/pull/3189), to support the "isfetchassets" flag instead of "isfetcheventsandassets".
> added support to "isfetchassets" instead of "isfetcheventsandassets" flag

- CHANGELOG.md
> Changelog Fix

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/common/tests/script_test.py
fixes: [CIAC-8510](https://jira-hq.paloaltonetworks.local/browse/CIAC-8510)
* Fixed an issue where **validate** falsely failed with error `DS108` on descriptions ending with json examples.
> added handling for json suffixes

- .circleci/config.yml
- demisto_sdk/commands/content_graph/neo4j_service.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8571
> [graph] increase graph memory

- CHANGELOG.md
> moving to unreleased

- CHANGELOG.md
- demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8624
> Catch test-modeling-rule Exception

- CHANGELOG.md
- demisto_sdk/commands/common/docker_helper.py
- demisto_sdk/commands/run_unit_tests/unit_tests_runner.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8294
Updated the **run-unit-tests** command to skip on JavaScript items.
> [run-unit-tests] Updated to skip on JavaScript items

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/integration.yml
related: https://jira-hq.paloaltonetworks.local/browse/CIAC-8452
see issue's description
> add supportlevelheader to schema

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/integration_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4008
> Validate reputation outputs

- .circleci/config.yml
- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/execute_test_content.py
- demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
- demisto_sdk/commands/test_content/tests/DemistoClientMock.py
- demisto_sdk/commands/test_content/tests/build_context_test.py
- demisto_sdk/commands/test_content/tests/integration_test.py
- demisto_sdk/commands/test_content/tests/test_context_test.py
- demisto_sdk/commands/test_content/tests/testplaybook_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8574
Adding junit output support for test-content command
Content: https://github.com/demisto/content/pull/29906
> Adding junit output support for test-content command

- CHANGELOG.md
- demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
Changed the table print for **modeling-rules test** command.
> Changed the table print for **modeling-rules test** command

- CHANGELOG.md
- demisto_sdk/commands/content_graph/common.py
relates: https://jira-dc.paloaltonetworks.com/browse/CRTX-78979
> Added tow scripts to SERVER_CONTENT_ITEMS

- CHANGELOG.md
- Utils/github_workflow_scripts/jira_integration_scripts/link_pr_to_jira_issue.py
- Utils/github_workflow_scripts_tests/link_pr_to_jira_issue_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8719
Added regex to catch issues in the new Jira instance.
> Fixed the flow to match Jira-DC

- demisto_sdk/commands/common/tests/dependencies_test.py
- demisto_sdk/commands/pre_commit/pre_commit_command.py
- demisto_sdk/commands/pre_commit/tests/pre_commit_test.py
fixes:
When running the pre-commit command with only a yml file as input, we want to collect the python file as well. Before we do that we want to make sure that it exists.
> In preprocess_files function check that the py file exists.

- demisto_sdk/commands/content_graph/parsers/layout_rule.py
- demisto_sdk/commands/content_graph/parsers/playbook.py
fixes: https://panw-global.slack.com/archives/G011E63JXPB/p1699196879190289
Fixing false positives in graph validations:
- non-existing items, e.g. deleteEmptyField, which are actually arguments of setIncident.
- LayoutRules should be supported only in marketplacev2
> fixed graph false positives

- CHANGELOG.md
> revert changelog comment

- demisto_sdk/commands/common/clients/__init__.py
- demisto_sdk/commands/common/clients/errors.py
- demisto_sdk/commands/common/clients/tests/get_client_test.py
- demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py
* add doc-strings
* re-order code
* handle invalid authenitcation
> clients: handle unauthorized & reorder code

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/pack_metadata.py
Don't add dependencies that are in `excluded_dependencies` or that are hidden.
> Fix pack dependencies calculation

- demisto_sdk/commands/common/git_util.py
- demisto_sdk/commands/common/legacy_git_tools.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/secrets/secrets.py
Added caching for some git commands.
> added lru_cache for some git functions

- demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py
Add additional common xsoar-endpoints
> [clients] - add additional common xsoar endpoints

- CHANGELOG.md
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/setup_env/setup_environment.py
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)
**The Pull Request will be reviewed only after the contribution registration form is filled.**
> [setup-env] fix issue with GSM and virtualenv

- CHANGELOG.md
- demisto_sdk/commands/common/files/json5_file.py
- demisto_sdk/commands/common/files/tests/file_test.py
- demisto_sdk/commands/common/files/tests/json5_file_test.py
- demisto_sdk/commands/common/files/tests/json_file_test.py
Add json5 support for files package
> Add json5 to files

- .pre-commit-config.yaml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9108
> precommit - add show-fixes to ruff config

- demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py
fixes:
Add to the `RunTimeException` a log that indicates what's the reason that playbook failed if it reached a failed state.
> [clients] - log out the reason of failed-playbook in case of error

- demisto_sdk/commands/common/tests/pack_unique_files_test.py
- demisto_sdk/commands/common/tests/readme_test.py
> Mock tests using sleep

- CHANGELOG.md
- demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/integration_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9243
Support the following syntax in the fetch
```
display: Fetch incidents
name: isFetch
type: 8
<extrakey>:<markeptlace>: <value>
```
see failure here: https://github.com/demisto/content/actions/runs/7275424612/job/19823298735?pr=31582
> validate: fix in148 in specific values for marketplace

- CHANGELOG.md
- demisto_sdk/commands/generate_docs/generate_integration_doc.py
Check if descrption exists before appending "." to it.
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8942
> [Generate docs] safe update description

- demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py
fixes:
* align the error messages to fit both for a command executed in a playground and a command executed in a playbook's task, use the same code for both cases.
> [clients] - improve error entries messages

- demisto_sdk/commands/setup_env/setup_environment.py
Fix clean repo in `setup-env` to correctly delete all the temp files in the repo.
fixes:
> [setup-env] clean repo fix

- CHANGELOG.md
- demisto_sdk/commands/pre_commit/hooks/docker.py
Change some chatty `info` logs to `debug`
> dockerhook: lower log level

- demisto_sdk/commands/common/logger.py
- demisto_sdk/commands/content_graph/commands/update.py
- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
- demisto_sdk/commands/content_graph/neo4j_service.py
clean graph between imports
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9321
> [Graph] clean after failed import

- TestSuite/assets/default_playbook/playbook-sample.yml
- demisto_sdk/commands/common/schemas/playbook.yml
> PB input/output sections - align field names with backend

- demisto_sdk/commands/common/handlers/json/json5_handler.py
- demisto_sdk/commands/common/handlers/json/ujson_handler.py
- demisto_sdk/commands/common/handlers/tests/json_test.py
- demisto_sdk/commands/common/handlers/tests/yml_test.py
- demisto_sdk/commands/common/handlers/xsoar_handler.py
- demisto_sdk/commands/common/handlers/yaml/ruamel_handler.py
> add `indent` arg to JSONHandler and RUAMLHandler constructors

- demisto_sdk/commands/content_graph/parsers/pack.py
- demisto_sdk/commands/validate/initializer.py
> refactor fixes

- CHANGELOG.md
- demisto_sdk/commands/content_graph/objects/integration_script.py
relates: [CIAC-9381](https://jira-dc.paloaltonetworks.com/browse/CIAC-9381)
Fix an issue where `nativeimage` tags were not uploaded due to recent changes in buckets.
> [Native Image] nativeimage tags are not uploaded to the buckets

- demisto_sdk/commands/validate/validators/base_validator.py
remove `graph_initialized` property as its redundant
> [validate] - refactor graph property

- .github/workflows/run-content-infrastructure-tests.yml
> Fix typo in infra test workflow name

- demisto_sdk/commands/validate/validators/DO_validators/DO105_docker_image_is_not_deprecated.py
- demisto_sdk/commands/validate/validators/DO_validators/DO106_docker_image_is_latest_tag.py
* DO105 is not auto-fixable (even though I wish it would!)
> DO105 - not fixable in new format

- .changelog/3950.yml
- README.md
- demisto_sdk/__main__.py
related: [XSUP-32254](https://jira-dc.paloaltonetworks.com/browse/XSUP-32254)
- Add a warning log when running on Windows machines
- Update README.md
> Warn when running on Windows

- .github/workflows/on-push.yml
Works on commit: https://github.com/demisto/demisto-sdk/pull/3969/commits/44d58220ea487793ab49a8a0e5a8f96860b97985
> validate changelog job - skip when running CI on master

- .changelog/3970.yml
fixes:
Fixing the description of the changelog from my my [previous](https://github.com/demisto/demisto-sdk/pull/3970) merge.
> fix description

- .changelog/3977.yml
- .github/workflows/on-push.yml
- demisto_sdk/commands/common/schemas/pre-process-rule.yml
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/scripts/changelog/tests/changelog_test.py
- demisto_sdk/tests/constants_test.py
- demisto_sdk/tests/test_files/preprocessrule-test_rule.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32502
Fixed a bug where validate command did not work with pre processing rules.
> fixed a bug where validate did not work with pre processing rules

- demisto_sdk/commands/format/update_generic.py
fixes: 
I have added spaces between the words in the text.
> [Format] Message Improvement

- .changelog/4037.yml
- demisto_sdk/commands/content_graph/commands/update.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9707
Added a check if `DEMISTO_SDK_GRAPH_FORCE_CREATE` environment variable is set to true in update content graph.
> Check if DEMISTO_SDK_GRAPH_FORCE_CREATE is set in update-content-graph

- .changelog/4052.yml
- demisto_sdk/commands/common/git_util.py
* Fixes an issue when trying to fetch files with commit that only exist in remote, but not locally fails. The fix is just to fetch the remote, and then the commit will be fetched too and we would be able to load the commit object.
> [GitUtil] - get commit enhancements

- demisto_sdk/commands/content_graph/objects/content_item.py
- demisto_sdk/commands/content_graph/objects/pack.py
> [validate] - get_ignored_errors to debug from error

- demisto_sdk/commands/common/files/file.py
* Fixed issue where git_util isn't initialized correctly for tests.
> [File] - fix git_util changes for tests

- .changelog/4077.yml
- demisto_sdk/commands/common/schemas/script.yml
https://jira-dc.paloaltonetworks.com/browse/CRTX-104969
> Add marketplacev2 to comment schema in scripts

- .changelog/4078.yml
- demisto_sdk/commands/common/schemas/assetsmodelingrule.yml
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/common/schemas/modelingrule.yml
- demisto_sdk/commands/common/schemas/parsingrule.yml
- demisto_sdk/commands/common/schemas/playbook.yml
- demisto_sdk/commands/common/schemas/script.yml
- demisto_sdk/commands/common/schemas/wizard.yml
- demisto_sdk/scripts/add_marketplace_to_schemas.py
related: https://jira-dc.paloaltonetworks.com/browse/CIAC-9816
Add the ability to deprecate content in a specific marketplace.
> support deprecate by marketplace in schema

- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/tests/test_context_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9788
Changes the way we send update playbook inputs POST request in XSOAM NG version 8.5.
> Add support update inputs playbook for XSOAR 8.5

- .github/workflows/release-to-pypi.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-7034
> [CI] - release SDK to pypi github action

- demisto_sdk/commands/common/clients/__init__.py
- demisto_sdk/commands/common/clients/errors.py
- demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py
* Allow checking if server is healthy
* Add PollTimeout exception when polling fails to get incident / playbook state.
> [clients] - allow checking if server is healthy

- .changelog/4087.yml
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/content_graph/objects/pack_metadata.py
- demisto_sdk/commands/content_graph/parsers/pack.py
- demisto_sdk/tests/integration_tests/prepare_content_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9616
> add hybrid flag to pack metadata object

- .changelog/4098.yml
- demisto_sdk/commands/common/docker_images_metadata.py
- demisto_sdk/commands/common/files/file.py
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-34151
> [lint] - fixed an issue where lint would crash without internet connectivity

- demisto_sdk/commands/validate/tests/IM_validators_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9797
fix IM_validators
> fix validation

- .changelog/4110.yml
- demisto_sdk/commands/upload/README.md
> fix upload readme

- demisto_sdk/scripts/init_validation_script.py
related: https://jira-dc.paloaltonetworks.com/browse/CIAC-9744
> [init_validation_script] Added `rationale`

- demisto_sdk/commands/validate/tests/PA_validators_test.py
- demisto_sdk/commands/validate/validators/PA_validators/PA102_should_pack_be_deprecated.py
> added a fix for pa102 validation

- .github/actions/upload_artifacts/action.yml
- .github/actions/validate/action.yml
- .github/workflows/on-push.yml
The SDK produces logs / cache / neo4j config under `.demisto-sdk`, upload everything to the artifacts.
> [CI] - upload everything under .demisto-sdk home-folder

- demisto_sdk/commands/validate/initializer.py
- demisto_sdk/commands/validate/validators/IM_validators/IM108_author_image_is_empty.py
- demisto_sdk/commands/validate/validators/IM_validators/IM109_author_image_exists_validation.py
- demisto_sdk/commands/validate/validators/base_validator.py
> multiple minor validate refactor fixes

- demisto_sdk/commands/common/errors.py
> added IN101 to ignorable error list

- package-lock.json
- package.json
> [nodejs] - update ip package

- package-lock.json
- package.json
Reverts demisto/demisto-sdk#4146
> Revert "[nodejs] - update ip package"

- .changelog/4151.yml
- demisto_sdk/commands/prepare_content/integration_script_unifier.py
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-35095
Fix issue with the description of Developer support where by mistake a message was added as if it was supported by PANW.
> [prepare-content] Fix issue with the description of Developer support

- .changelog/4166.yml
- demisto_sdk/commands/common/content_constant_paths.py
- demisto_sdk/commands/setup_env/setup_environment.py
We need to reparse the pack again since the pack doesn't contain all the content items to upload.
in addition fixed an issue where debugging locally failed
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10024?filter=-1
> [setup env] fix pack upload

- .github/workflows/on-push.yml
- demisto_sdk/scripts/validate_content_path.py
1. only run if the validation/its test is modified
2. fail `validate-all` if there are failured
3. use `fetch-depth=1` for content
> Improve path validation CI

- .github/workflows/on-push.yml
> [CI] - coveralls update on coverage job

- .github/workflows/on-push.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9918
Add the `--ci` mode flag.
> [CI] - run pre-commit with ci mode

- .github/workflows/release-to-pypi.yml
fixes:
Release the SDK to Pypi from the release tag and not from the release branch
> [deploy-to-pypi] - checkout to release tag

- .changelog/4203.yml
- demisto_sdk/__main__.py
> Fix an issue where validate spammed logs when running.

- demisto_sdk/scripts/validate_content_path.py
- demisto_sdk/tests/validate_content_path_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10156
> XR100 - Path validation

- demisto_sdk/commands/validate/validators/IN_validators/IN150_is_valid_display_for_siem_integration.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10341
Change the link to the xsoar pan dev to the valid one.
> [Validate] Updated The link In IN150 Rationale

- demisto_sdk/commands/validate/validators/DO_validators/DO106_docker_image_is_latest_tag.py
- demisto_sdk/commands/validate/validators/IF_validators/IF105_is_cli_name_field_alphanumeric.py
- demisto_sdk/commands/validate/validators/IM_validators/IM100_image_exists_validation.py
- demisto_sdk/commands/validate/validators/IN_validators/IN100_is_valid_proxy_and_insecure.py
- demisto_sdk/commands/validate/validators/PA_validators/PA104_is_valid_modules.py
Added dots at the end of the `rationale` variable.
> [Validate] Rationale Typo

- .changelog/4235.yml
- demisto_sdk/commands/content_graph/interface/neo4j/queries/validations.py
- demisto_sdk/commands/content_graph/tests/graph_validator_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10304
Remove the Trigger content item type from the GR101 from_version validation in old validator
> exclude Trigger from query

- .changelog/4251.yml
- demisto_sdk/commands/common/git_util.py
> prettier gitutil debug prints

- demisto_sdk/__main__.py
- demisto_sdk/commands/pre_commit/README.md
- demisto_sdk/commands/pre_commit/pre_commit_command.py
- demisto_sdk/commands/validate/README.md
fixes: [CIAC-10010](https://jira-dc.paloaltonetworks.com/browse/CIAC-10010)
> pre-commit code document

- .changelog/4286.yml
- .github/workflows/on-push.yml
- demisto_sdk/__main__.py
- demisto_sdk/commands/lint/README.md
- demisto_sdk/commands/lint/lint_manager.py
related to: https://jira-dc.paloaltonetworks.com/browse/CIAC-10009
Add a deprecation message to the **demisto-sdk lint** command.
Remove lint from all flows mentioned in sdk.
> add lint deprecation message.

- .github/workflows/on-push.yml
fixes:
Disable test-content-infrastructure phase due to transfer of infrastructure files to Infra repo
> disable_test-content-infrastructure_step

- demisto_sdk/commands/content_graph/objects/incident_field.py
- demisto_sdk/commands/content_graph/objects/indicator_field.py
Fixed an issue when running secret detection on test data file with int id it failed with:
`AttributeError: 'int' object has no attribute 'lower'
`
> Fixed Int ID File Issue

- demisto_sdk/__main__.py
- demisto_sdk/commands/setup_env/README.md
- Update the README file, change the flag option list to table
- Update the `-i` flag description
[link](https://confluence-dc.paloaltonetworks.com/display/DemistoContent/demisto-sdk+setup-env)
> [setup-env] Improve README

- .changelog/4336.yml
- .github/workflows/on-push.yml
fixes: [CIAC-10783](https://jira-dc.paloaltonetworks.com/browse/CIAC-10783)
> make test-pre-commit-command validate use only BA100 validation

- .changelog/4343.yml
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/content_graph/objects/base_playbook.py
- demisto_sdk/commands/content_graph/objects/playbook.py
- demisto_sdk/commands/content_graph/parsers/base_playbook.py
- demisto_sdk/commands/content_graph/parsers/playbook.py
- demisto_sdk/commands/validate/tests/PB_validators_test.py
- demisto_sdk/commands/validate/tests/tools_test.py
- demisto_sdk/commands/validate/validators/PB_validators/PB101_is_playbook_has_unreachable_condition.py
- demisto_sdk/commands/validate/validators/PB_validators/PB118_is_input_key_not_in_tasks.py
- demisto_sdk/commands/validate/validators/PB_validators/PB123_is_conditional_task_has_unhandled_reply_options.py
fixes: [CIAC-10864](https://jira-dc.paloaltonetworks.com/browse/CIAC-10864)
Modelized playbook tasks into objects.
> added tasks objects

- demisto_sdk/commands/validate/tests/BC_validators_test.py
- demisto_sdk/commands/validate/validators/BC_validators/BC112_no_removed_integration_parameters.py
> Fix no_removed_integration_parameters unit-tests

- .changelog/4380.yml
- demisto_sdk/__main__.py
- demisto_sdk/commands/validate/README.md
- demisto_sdk/commands/validate/config_reader.py
- demisto_sdk/commands/validate/tests/validators_test.py
fixes: [CIAC-10893](https://jira-dc.paloaltonetworks.com/browse/CIAC-10893)
Added support for run-specific-validations in new validate.
> Added support for run-specific-validations in new validate

- .changelog/4376.yml
- demisto_sdk/scripts/validate_content_path.py
- demisto_sdk/tests/validate_content_path_test.py
relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-7814
Converted the MR103 validation to path validation.
> Convert validation MR103

- .changelog/4383.yml
- demisto_sdk/commands/validate/tests/RN_validators_test.py
- demisto_sdk/commands/validate/validators/RN_validators/RN103_is_release_notes_filled_out.py
fixes: [CIAC-10923](https://jira-dc.paloaltonetworks.com/browse/CIAC-10923)
Fixed an issue where RN103 failed on newly added packs due to missing release notes.
> fix an issue where RN103 failed on new packs

- .changelog/4382.yml
- demisto_sdk/commands/pre_commit/hooks/docker.py
Make IMAGES_BATCH var configurable
> Make IMAGES_BATCH var configurable

- demisto_sdk/commands/common/hook_validations/incident_type.py
- demisto_sdk/commands/common/tests/incident_type_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/content_graph/tests/create_content_graph_test.py
- demisto_sdk/commands/content_graph/tests/pack_metadata_graph_test.py
- demisto_sdk/commands/prepare_content/markdown_images_handler.py
- demisto_sdk/commands/prepare_content/tests/markdown_images_handler_test.py
- demisto_sdk/commands/prepare_content/tests/yml_unifier_test.py
- demisto_sdk/commands/upload/tests/uploader_test.py
- demisto_sdk/commands/validate/validators/BA_validators/BA124_is_have_unit_test_file.py
- demisto_sdk/tests/integration_tests/content_create_artifacts_integration_test.py
- demisto_sdk/tests/integration_tests/prepare_content_test.py
- demisto_sdk/tests/integration_tests/unify_integration_test.py
- demisto_sdk/tests/integration_tests/upload_integration_test.py
> Fix non initialized json files issue

- .changelog/4397.yml
- demisto_sdk/commands/prepare_content/markdown_images_handler.py
> fix run sync error

- .changelog/4396.yml
- demisto_sdk/commands/common/schemas/widget.yml
fixes:
https://jira-dc.paloaltonetworks.com/browse/CRTX-111306
Added the marketplaces field to the widget schema.
> Add marketplaces to widget schema

- .changelog/4394.yml
- demisto_sdk/commands/pre_commit/pre_commit_command.py
- demisto_sdk/commands/pre_commit/tests/pre_commit_test.py
- demisto_sdk/commands/validate/initializer.py
- demisto_sdk/commands/validate/tests/validators_test.py
relates: [CIAC-10968](https://jira-dc.paloaltonetworks.com/browse/CIAC-10968)
Hotfix for untracked file collection in `pre-commit` and `validate`.
> [Contributions] Update untracked files collection in external PR usecase

- .changelog/4408.yml
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/hook_validations/readme.py
- demisto_sdk/commands/common/tests/pack_unique_files_test.py
- demisto_sdk/commands/common/tests/readme_test.py
- demisto_sdk/commands/validate/tests/old_validators_test.py
- demisto_sdk/commands/validate/validators/DO_validators/DO106_docker_image_is_latest_tag.py
> remove rm108 relative image validation from old validate

- .changelog/4416.yml
- demisto_sdk/commands/content_graph/objects/base_content.py
- demisto_sdk/commands/content_graph/objects/base_playbook.py
- demisto_sdk/commands/content_graph/objects/content_item.py
- demisto_sdk/commands/content_graph/objects/integration.py
fixes: [CIAC-11111](https://jira-dc.paloaltonetworks.com/browse/CIAC-11111)
Fixed an issue where playbook saved due to a failed attempt to dump task object.
> fixed an issue with playbook save

- .changelog/4440.yml
- demisto_sdk/commands/content_graph/objects/base_script.py
- demisto_sdk/commands/prepare_content/tests/marketplace_incident_to_alert_scripts_preparer_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-121316
Replace incident to alert also for deprecated content.
> Replace incident to alert for deprecated content

- .changelog/4467.yml
- demisto_sdk/commands/content_graph/parsers/dashboard.py
- demisto_sdk/commands/content_graph/strict_objects/common.py
- demisto_sdk/commands/content_graph/strict_objects/dashboard.py
- demisto_sdk/commands/validate/validators/ST_validators/ST110_is_valid_scheme.py
Added a StrictDashboard object of Pydantic for ST110 validation
> ST110 - Dashboards

- .changelog/4469.yml
- demisto_sdk/commands/content_graph/strict_objects/common.py
- demisto_sdk/commands/content_graph/strict_objects/dashboard.py
- demisto_sdk/commands/content_graph/strict_objects/generic_definition.py
- demisto_sdk/commands/validate/validators/ST_validators/ST110_is_valid_scheme.py
Added a StrictGenericDefinition object of Pydantic for ST110 validation
> ST110 - Generic Definition

- demisto_sdk/commands/test_content/TestContentClasses.py
[TestContext] Fix the Investigation URL in XSOAR SAAS
> [TestContext] Fix the Investigation URL in XSOAR SAAS

- .changelog/4478.yml
- demisto_sdk/commands/content_graph/strict_objects/base_strict_model.py
- demisto_sdk/commands/content_graph/strict_objects/common.py
- demisto_sdk/commands/content_graph/strict_objects/layout_rule.py
- demisto_sdk/commands/content_graph/strict_objects/report.py
- demisto_sdk/commands/content_graph/strict_objects/trigger.py
- demisto_sdk/commands/content_graph/strict_objects/widget.py
- demisto_sdk/commands/content_graph/strict_objects/wizard.py
- demisto_sdk/commands/content_graph/strict_objects/xdrc_template.py
- demisto_sdk/commands/content_graph/strict_objects/xsiam_dashboard.py
- demisto_sdk/commands/validate/validators/ST_validators/ST110_is_valid_scheme.py
Added Report, Trigger, Widget, Wizard, XDRCTemplate and XSIAMDashboard objects of Pydantic for ST110 validation.
> ST110 - Report, Trigger, Widget, Wizard, XDRCTemplate and XSIAMDashboard

- .changelog/4484.yml
- demisto_sdk/commands/content_graph/strict_objects/xsiam_report.py
- demisto_sdk/commands/validate/validators/ST_validators/ST110_is_valid_scheme.py
Added XSIAMReport object of Pydantic for ST110 validation.
> ST110 - XSIAMReport

- .changelog/4485.yml
- demisto_sdk/commands/content_graph/strict_objects/common.py
- demisto_sdk/commands/content_graph/strict_objects/indicator_type.py
- demisto_sdk/commands/validate/validators/ST_validators/ST110_is_valid_scheme.py
Added IndicatorType object of Pydantic for ST110 validation.
> ST110 - IndicatorType

- .changelog/4479.yml
- demisto_sdk/commands/content_graph/objects/conf_json.py
Related: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-11453) to the issue
https://github.com/demisto/content/pull/35770
> [Validate Conf] Added `native_nightly_packs`

- .changelog/4486.yml
- demisto_sdk/commands/content_graph/strict_objects/assets_modeling_rule.py
- demisto_sdk/commands/validate/validators/ST_validators/ST110_is_valid_scheme.py
Added AssetsModelingRule object of Pydantic for ST110 validation.
> ST110 - AssetsModelingRule

- .changelog/4488.yml
- demisto_sdk/commands/content_graph/strict_objects/case_field.py
- demisto_sdk/commands/validate/validators/ST_validators/ST110_is_valid_scheme.py
Added CaseField object of Pydantic for ST110 validation.
> ST110 - CaseField

- .changelog/4489.yml
- demisto_sdk/commands/content_graph/strict_objects/case_layout.py
- demisto_sdk/commands/validate/validators/ST_validators/ST110_is_valid_scheme.py
Added CaseLayout object of Pydantic for ST110 validation.
> ST110- CaseLayout

- .changelog/4491.yml
- demisto_sdk/commands/content_graph/strict_objects/case_layout_rule.py
- demisto_sdk/commands/validate/validators/ST_validators/ST110_is_valid_scheme.py
Added 'CaseLayoutRule' object of Pydantic for ST110 validation.
> ST110 - CaseLayoutRule

- demisto_sdk/commands/prepare_content/integration_script_unifier.py
- demisto_sdk/commands/prepare_content/tests/yml_unifier_test.py
Related: [CIAC-10484](https://jira-dc.paloaltonetworks.com/browse/CIAC-10484)
In this PR we added the pack version https://github.com/demisto/demisto-sdk/pull/4437
add pack name to the debug log
> [unify] Add pack name

- CHANGELOG.md
fixes:
fix incorrect PR number
> 4470 > 4482

- .changelog/4515.yml
- demisto_sdk/commands/pre_commit/hooks/docker.py
fixes:https://jira-dc.paloaltonetworks.com/browse/CIAC-11590
> Add authentication for pull dockers in pre-commit

- .changelog/4509.yml
- demisto_sdk/__main__.py
- demisto_sdk/commands/validate/README.md
- demisto_sdk/commands/validate/config_reader.py
- demisto_sdk/commands/validate/tests/validators_test.py
> remove check_ignored_are_ignorable

- .changelog/4517.yml
- demisto_sdk/commands/validate/validators/DS_validators/DS107_is_description_contains_demisto_word.py
fixes:
[CIAC-11619](https://jira-dc.paloaltonetworks.com/browse/CIAC-11619)
Fixing an error that was found [here](https://github.com/demisto/content/pull/35989)
> add Demisto Bot to exceptionally_allowed_substrings

- .changelog/4525.yml
- demisto_sdk/commands/content_graph/strict_objects/common.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11622
> allow none `default_template_id`

- .changelog/4534.yml
- .github/actions/upload_artifacts/action.yml
fix coverage workflow - include hidden files to upload to artifact
> fix coverage workflow - include hidden files to upload to artifact

- .changelog/4532.yml
- demisto_sdk/commands/validate/default_config.toml
fixes:
Reverting changes made [here](https://github.com/demisto/demisto-sdk/pull/4348/files)
> revert default config changes

- .changelog/4543.yml
- demisto_sdk/scripts/init_validation_script.py
fixes:
The main class is missing the `ABC` and the fix is ... `self.initialize_using_graph()` should called before generating the class.
Also, fix the `expected_execution_mode` with the correct mode
> [init-validation] Fix generate graph validation

- .changelog/4550.yml
- demisto_sdk/commands/common/schemas/script.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11782
Added the option to give a specific value for xsiam hidden attribute in script arguments.
> Added support for hidden by mp in script arguments

- demisto_sdk/commands/common/errors.py
Related: https://jira-dc.paloaltonetworks.com/browse/CIAC-11781
- https://github.com/demisto/content/pull/36330
- https://github.com/demisto/demisto-sdk/pull/4561
Add GR107 to the ALLOWED_IGNORE_ERRORS
> [validate] Add GR107 to the ALLOWED_IGNORE_ERRORS

- .github/CODEOWNERS
> Add `default_config.toml` CODEOWNERS

- demisto_sdk/commands/common/errors.py
Related: https://jira-dc.paloaltonetworks.com/browse/CIAC-11780
https://github.com/demisto/demisto-sdk/pull/4564
Add GR101 to the ALLOWED_IGNORE_ERRORS
> [validate] Add GR101 to the ALLOWED_IGNORE_ERRORS 

- .changelog/4571.yml
- demisto_sdk/commands/common/constants.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11696
> Bump Neo4j version - locally

- .changelog/4579.yml
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8808
Fixed an issue in `update-release-notes` command where existing items in release notes were not properly detected.
> [update-release-notes] Fix issue in existing items in release notes

- .changelog/4581.yml
- demisto_sdk/commands/pre_commit/pre_commit_context.py
fixes: [CIAC-10869](https://jira-dc.paloaltonetworks.com/browse/CIAC-10869)
Add pre-commit hooks logs in CI.
> Add pre-commit logs in CI

- .changelog/4576.yml
- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-11638
Enhanced the Graph interface to support multi-threaded environments.
This PR will be merged, and after the release, we will merge the following one in Infra:
https://gitlab.xdr.pan.local/xdr/cortex-content/infra/-/merge_requests/495
The nightly that shows it worked:
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/8757831/raw
> Singleton Interface / CIAC-11638

- .changelog/4582.yml
- demisto_sdk/commands/lint/lint_manager.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11874
fix lint log failure
> fix lint logging

- demisto_sdk/commands/upload/uploader.py
fixes:
Fixes a bug with incorrect closing tags in logging that prevents uploading of content packs.
> Fixed incorrect closing tags

- .changelog/4591.yml
- demisto_sdk/commands/upload/tools.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11885
Fixing an issue where debug-logging in **upload** failed
> fix upload debug logging

- .changelog/4584.yml
- demisto_sdk/commands/common/schemas/script.yml
- demisto_sdk/scripts/add_marketplace_to_schemas.py
> added the hidden to the schemna argument of the script.yml schema

- .changelog/4602.yml
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_playbook.py
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-42298
> remove playbook task name formatting

- .changelog/4603.yml
- demisto_sdk/commands/validate/validators/DO_validators/docker_validator.py
> fix docker validator

- .changelog/4604.yml
- demisto_sdk/commands/validate/tests/RM_validators_test.py
- demisto_sdk/commands/validate/validators/RM_validators/RM106_is_contain_demisto_word.py
Enhance message of validation RM106
> Enhance message of validation RM106

- .changelog/4615.yml
- demisto_sdk/commands/content_graph/strict_objects/base_strict_model.py
- demisto_sdk/commands/content_graph/strict_objects/script.py
relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-11383
Added just for Argument in script the new field  'hidden:marketplacev2' and removed it from the other places.
> Fix the StrictScript with the new field  'hidden:marketplacev2'

- demisto_sdk/tests/integration_tests/xsoar_linter_pre_commit_integration_test.py
relates: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-12008)
> Skipping Failing UT "xsoar_linter_pre_commit_integration_test"

- demisto_sdk/commands/content_graph/parsers/integration.py
> remove long_running_duplication

- .changelog/4627.yml
- .changelog/4628.yml
- demisto_sdk/commands/common/docker/dockerhub_client.py
- demisto_sdk/commands/common/docker_helper.py
fixes: [revert](https://github.com/demisto/demisto-sdk/pull/4628/commits/51aee059d5a2ae4c2ffa7bed08cc2273f6b77cdf) https://github.com/demisto/demisto-sdk/pull/4528
> Revert4528

- .changelog/4640.yml
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/release_notes.py
- demisto_sdk/commands/common/tests/release_notes_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/validate/sdk_validation_config.toml
- demisto_sdk/commands/validate/tests/RN_validators_test.py
- demisto_sdk/commands/validate/tools.py
- demisto_sdk/commands/validate/validators/RN_validators/RN113_is_valid_content_type_header.py
- demisto_sdk/commands/validate/validators/RN_validators/RN115_is_valid_rn_headers_format.py
> convert RN 115

- demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
fixes:
This PR was created in order to understand the problem described in CIAC-12144. 
line number 735 build status.
> replace-debug-logs-to-info

- .changelog/4680.yml
- demisto_sdk/__main__.py
- demisto_sdk/commands/merge_id_sets/merge_id_sets_setup.py
Fix the nightly SDK failure after the Typer change:
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/10920111
Added back the `merge-id-sets` command (hidden)
> Added merge-id-sets to typer (hidden command)

- .changelog/4689.yml
- demisto_sdk/commands/common/schemas/playbook.yml
- demisto_sdk/commands/common/schemas/trigger.yml
https://jira-dc.paloaltonetworks.com/browse/CIAC-11986
> added isSilent to Playbook and Trigger schema

- demisto_sdk/tests/integration_tests/xsoar_linter_pre_commit_integration_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12008
> restore test 'test_xsoar_linter_errors'

- .changelog/4691.yml
- .changelog/6847.yml
- demisto_sdk/commands/update_release_notes/update_release_notes_setup.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12292
Packs Release notes - Text flag not working
> Packs Release notes - Text flag not working

- .changelog/4686.yml
- demisto_sdk/commands/test_content/content_test_setup.py
- tests_end_to_end/xsoar/test_e2e_demisto_sdk_flow_playbook_xsoar.py
fixes: https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1705777
Fixing SDK nightly End2End test
> Fix end2end

- .changelog/4694.yml
- demisto_sdk/commands/setup_env/setup_env_setup.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12290
Fixed the error for missing file_paths
> setup-env file_paths fix

- .changelog/4695.yml
- demisto_sdk/__init__.py
fixes: Fixing logger setup which was adapted at https://github.com/demisto/demisto-sdk/pull/4657.
Original solution did not consider all use cases.
This solution will allow toggling logger setup from the executing environment (containerized integrations/scripts using 'demisto-sdk').
> fix logger setup on module init

- demisto_sdk/commands/setup_env/setup_env_setup.py
- demisto_sdk/commands/setup_env/setup_environment.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12339
Fixed the CONTENT_PATH for the ide flag.
> Setup env fix2

- .changelog/4700.yml
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/content_graph/parsers/pack.py
- demisto_sdk/commands/content_graph/parsers/related_files.py
- demisto_sdk/commands/validate/initializer.py
> git sha fix

- demisto_sdk/commands/lint/lint_setup.py
fixes: https://gitlab.xdr.pan.local/xdr/cortex-content/content-internal-dist/-/jobs/11606132
Added back the files logs options to Lint Command
> Added missing options to Lint command

- .changelog/4454.yml
- demisto_sdk/commands/lint/resources/python3_requirements/dev-requirements.txt
Reverts demisto/demisto-sdk#4454
> Revert "Monkeytype SDK"

- .changelog/4710.yml
- demisto_sdk/commands/validate/tests/BA_validators_test.py
- demisto_sdk/commands/validate/tests/PA_validators_test.py
- demisto_sdk/commands/validate/tests/RN_validators_test.py
- demisto_sdk/commands/validate/tests/test_tools.py
- demisto_sdk/commands/validate/tools.py
- demisto_sdk/commands/validate/validators/PA_validators/PA114_pack_metadata_version_should_be_raised.py
- demisto_sdk/commands/validate/validators/RN_validators/RN106_missing_release_notes_for_pack.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12384
- Fixed PA114 and RN106 failures for new packs
- Fixed create_pack_object and its callers to use `currentVersion` instead of `version`
> fix rn106 and pa114

- .changelog/4711.yml
- demisto_sdk/commands/content_graph/common.py
- demisto_sdk/commands/content_graph/tests/parsers_and_models_test.py
- demisto_sdk/commands/validate/tests/RN_validators_test.py
- demisto_sdk/commands/validate/tools.py
- demisto_sdk/commands/validate/validators/RN_validators/RN107_missing_release_notes_entry.py
- demisto_sdk/commands/validate/validators/RN_validators/RN114_validate_release_notes_header.py
- demisto_sdk/commands/validate/validators/RN_validators/RN115_is_valid_rn_headers_format.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12388
Fixed an issue where *RN107* validation would fail on new content items and for specific content types.
> remove prefixes

- .changelog/4706.yml
- demisto_sdk/scripts/validate_content_path.py
- demisto_sdk/tests/validate_content_path_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12430
Added the `CaseLayouts` & `CaseFields` to the `validate-content-paths` for this PR https://github.com/demisto/content/pull/37625
> [validate-content-paths] Add the Case Folders 

- .changelog/4747.yml
- demisto_sdk/commands/setup_env/README.md
- demisto_sdk/commands/setup_env/setup_env_setup.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12495
> Fix for file_paths default

- .changelog/4750.yml
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/commands/validate/validate_setup.py
- demisto_sdk/commands/validate/validators/RM_validators/RM116_missing_playbook_image.py
> Minor validate changes

- .changelog/4755.yml
- demisto_sdk/commands/validate/tests/RN_validators_test.py
- demisto_sdk/commands/validate/validators/RN_validators/RN114_validate_release_notes_header.py
> CaseLayouts & RN114

- .changelog/4751.yml
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_release_notes_setup.py
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12202
> update-release-notes --text special chars

- .changelog/4756.yml
- .github/actions/setup_environment/action.yml
- pyproject.toml
fixes: [CIAC-12544](https://jira-dc.paloaltonetworks.com/browse/CIAC-12544)
Limiting poetry version in `setup-environment` step - untill v2.0.0 support is added.
> limit poetry version

- .changelog/4758.yml
- demisto_sdk/commands/validate/initializer.py
> fix initializer

- demisto_sdk/commands/validate/tests/RN_validators_test.py
- demisto_sdk/commands/validate/validators/RN_validators/RN111_is_docker_entry_match_yml.py
fixed an issue where RN111 it would update your old rn if you hadnt added new
> only fix for new rn

- .changelog/4767.yml
- demisto_sdk/commands/pre_commit/hooks/ruff.py
- demisto_sdk/commands/pre_commit/tests/pre_commit_test.py
- poetry.lock
fixes:
As a result of this ticket https://github.com/astral-sh/ruff/issues/7990 "format should be updated to "output-format". 
Link to ruff documentation https://docs.astral.sh/ruff/settings/#namespace-packages.
> Update the Ruff hook to use output-format

- demisto_sdk/__main__.py
> Reintroduce `generate-test-playbook` command to demisto-sdk

- .changelog/4809.yml
- demisto_sdk/commands/validate/tests/RN_validators_test.py
- demisto_sdk/commands/validate/validators/RN_validators/RN116_first_level_header_missing.py
> Remove dot from RN116 error message.

- .changelog/4822.yml
- demisto_sdk/commands/pre_commit/pre_commit_command.py
- demisto_sdk/commands/pre_commit/pre_commit_setup.py
Fixed an issue with the pre-commit command where debug level logs were not appearing in the log file.
> [pre-commit] Fix issue with logs

- .changelog/4826.yml
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12940
> Fixed update RN command when updating docker image

- .changelog/4835.yml
- demisto_sdk/commands/common/docker_helper.py
on-call issue.
Increase container timeout.
> [docker] Increase container timeout

- .changelog/4838.yml
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validation_results.py
> enhance validate summary msg

- .changelog/4840.yml
- .changelog/4846.yml
- demisto_sdk/commands/upload/tests/uploader_test.py
- demisto_sdk/commands/upload/tools.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12983
Added error handling for when no error is available.
> add to uploader better handling of errors

- .changelog/4851.yml
- .github/workflows/on-push.yml
- demisto_sdk/commands/common/docker_helper.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13027
> Changed the place docker client is taken from.

- demisto_sdk/commands/validate/validators/IM_validators/IM111_invalid_image_dimensions.py
> Fix IM111 validation

- .changelog/4856.yml
- .github/workflows/on-push.yml
- .github/workflows/release-to-pypi.yml
fixes: tj-actions/changed-files@v46.0.1
tj-actions/changed-files@v46.0.1
> tj-actions/changed-files@v46.0.1

- .changelog/4872.yml
- demisto_sdk/commands/content_graph/parsers/related_files.py
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-47757
Update `TextFile` class logic to use the local branch if no remote is available.
> Update branch selection logic in `TextFile` class

- .changelog/4862.yml
- .github/workflows/on-push.yml
fixes: [CIAC-12658](https://jira-dc.paloaltonetworks.com/browse/CIAC-12658)
> remove old validate from build

- .changelog/4878.yml
- .github/workflows/on-push.yml
- demisto_sdk/commands/validate/config_reader.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_setup.py
fixes: [CIAC-13207](https://jira-dc.paloaltonetworks.com/browse/CIAC-13207)
> added additional-ignorable-errors flag

- .changelog/4883.yml
- demisto_sdk/commands/content_graph/objects/content_item.py
This log line should be debug level instead of info.
> change log level to dump-file-path line

- .changelog/4885.yml
- demisto_sdk/commands/content_graph/strict_objects/modeling_rule.py
- demisto_sdk/commands/content_graph/strict_objects/parsing_rule.py
Adapt strict objects for Modeling Rules and ParsingRules to support new platform marketplace `supportedModules` field.
> Fix parsing rule and modeling rule strict objects

- .changelog/4890.yml
- demisto_sdk/commands/init/templates/HelloWorld/HelloWorld.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13334
> Add section order to the integration YML file

- .changelog/4912.yml
- demisto_sdk/commands/download/download_setup.py
- demisto_sdk/commands/download/downloader.py
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-49343
Added support for local custom command configuration file - `.demisto-sdk-conf` to ***download*** command.
> download command - add support to demisto-sdk-conf

- .changelog/4911.yml
- demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py
fixes: [link to issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13078)
Fix a timeout-related issue in `XsoarClient.pull_playbook_tasks_by_state`.
> Fix a timeout-related issue with XsoarClient.pull_playbook_tasks_by_state

- .changelog/4913.yml
- demisto_sdk/commands/content_graph/objects/base_playbook.py
- demisto_sdk/commands/content_graph/objects/base_script.py
- demisto_sdk/commands/content_graph/objects/content_item.py
- demisto_sdk/commands/content_graph/objects/pack_metadata.py
- demisto_sdk/commands/prepare_content/preparers/incident_to_alert.py
- demisto_sdk/commands/prepare_content/preparers/marketplace_incident_to_alert_playbooks_prepare.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-167534
Add `incident_to_alert` mechanism for Platform Marketplace
> Add `incident to alert` for Platform Marketplace

- .changelog/4924.yml
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/prepare_content/markdown_images_handler.py
fixes: [CRTX-170244](https://jira-dc.paloaltonetworks.com/browse/CRTX-170244)
> Byosi/crtx 170244/fix readme images url replacement

- .changelog/4934.yml
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/format/format_module.py
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13643
modified the integration schema used in the SDK format command to include the 'triggers' section.
> Modified the integration schema used in the SDK format command to include the 'triggers' section.

- .changelog/4930.yml
- demisto_sdk/commands/content_graph/strict_objects/integration.py
- demisto_sdk/commands/validate/tests/ST_validators_test.py
- demisto_sdk/commands/validate/validators/ST_validators/ST111_no_exclusions_schema.py
relates: [CIAC-13644](https://jira-dc.paloaltonetworks.com/browse/CIAC-13644)
Add the 'Result' section to SectionOrderValues and updated related validations.
> Add the 'Result' section to SectionOrderValues and updated related validations.

- .changelog/4940.yml
- demisto_sdk/commands/content_graph/objects/integration.py
- demisto_sdk/commands/prepare_content/preparers/marketplace_commands_availability_preparer.py
- demisto_sdk/commands/prepare_content/tests/marketplace_command_availability_preparer_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13779
> Added MarketplaceCommandsAvailabilityPreparer for Integration.prepare_for_upload

- .changelog/4941.yml
- demisto_sdk/commands/pre_commit/pre_commit_command.py
fixes: Fixed an issue where logging would fail when displaying pre-commit diff.
> Logging Failure During `--show-diff-on-failure` pre-commit

- .changelog/4960.yml
- demisto_sdk/commands/pre_commit/hooks/hook.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13930
> Add support to un-skip a pre-commit hook in a specific mode

- .changelog/4953.yml
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/common/schemas/script.yml
- demisto_sdk/commands/content_graph/common.py
- demisto_sdk/commands/content_graph/interface/neo4j/queries/relationships.py
- demisto_sdk/commands/content_graph/objects/base_script.py
- demisto_sdk/commands/content_graph/objects/integration.py
- demisto_sdk/commands/content_graph/parsers/base_script.py
- demisto_sdk/commands/content_graph/parsers/integration.py
- demisto_sdk/commands/content_graph/strict_objects/integration.py
- demisto_sdk/commands/content_graph/strict_objects/script.py
relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-13824
SDK branch for the Preference Center feature support.
- Add schema support for the `compliantpolicies` yml key.
- Add graph support for the `compliantpolicies` yml key.
> [feature] Preference Center

- .changelog/4963.yml
- demisto_sdk/commands/pre_commit/README.md
- demisto_sdk/commands/pre_commit/hooks/mypy.py
- demisto_sdk/commands/pre_commit/pre_commit_command.py
- demisto_sdk/commands/pre_commit/tests/test_data/.pre-commit-config_template-test.yaml
Reverts demisto/demisto-sdk#4950
> Revert "Remove mypy Hook"

- .changelog/4999.yml
- demisto_sdk/commands/content_graph/strict_objects/base_strict_model.py
> fix supportedmodules

- .github/CODEOWNERS
> added yedidya as validations owner

- .changelog/5012.yml
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/validate/tests/GR_validators_test.py
> fix st110 supported module const

- .changelog/5029.yml
- demisto_sdk/commands/common/git_content_config.py
related: https://jira-dc.paloaltonetworks.com/browse/XSUP-54434
handle demisto-sdk error requests.exceptions.JSONDecodeError
> XSUP-54434 Demisto-sdk pre-commit fails in CI pipeline

- .changelog/5026.yml
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
> improve tags filter

- .changelog/5041.yml
- demisto_sdk/commands/content_graph/parsers/json_content_item.py
> in progress

- .changelog/5070.yml
- demisto_sdk/commands/validate/validators/PA_validators/PA128_validate_pack_files.py
> Improve the error message of the pack files validator
