- demisto_sdk/common/schemas/canvas-context-connections.yml
- demisto_sdk/common/schemas/incidentfields.yml
- demisto_sdk/common/schemas/report.yml
> fixed required field in schemes

- demisto_sdk/validation/file_validator.py
> add prints everywhere

- demisto_sdk/common/tools.py
> fix os.subprocess.DEVNULL to DEVBULL

- demisto_sdk/common/constants.py
ignore regex warning on not-regex str
> suppress lgtm warning on regex

- README.md
> added pypi and lgtm badges

- demisto_sdk/common/tools.py
we must find a way to run it exactly like circle.
> os.subprocess.* to *

- demisto_sdk/common/tools.py
- demisto_sdk/core.py
- demisto_sdk/dev_tools/linter.py
- demisto_sdk/yaml_tools/content_creator.py
- requirements.txt
- tests/structure_test.py
may the build will pass with this one
> Fixing parent imports

- test-requirements.txt
- tests/conftest.py
- tests/structure_test.py
- tests/validators_test.py
conftest will suppress unverified warnings for cleaner tests.
also fixed setup/teardown in structure/validators_test
> Added conftest to tests lib

- demisto_sdk/common/configuration.py
- demisto_sdk/core.py
- demisto_sdk/dev_tools/linter.py
Add an argument to the main parser to specify a working directory, to run the command in that directory.
> Allow specifying working directory

- demisto_sdk/common/configuration.py
- demisto_sdk/core.py
- demisto_sdk/dev_tools/linter.py
- tests/linter_test.py
> fix not commonsp imports on mypy

- demisto_sdk/common/configuration.py
- demisto_sdk/dev_tools/linter.py
> fix default env_dir

- demisto_sdk/common/configuration.py
- demisto_sdk/dev_tools/linter.py
> fix dev_env_dir and mypy runner

- demisto_sdk/common/configuration.py
changed the base env to the right one
> fix envs base

- README.md
> added note for running pytest

- demisto_sdk/core.py
fixes: https://github.com/demisto/etc/issues/20441
> Handle errors in the CLI

- .pre-commit-config.yaml
- tox.ini
fixed pre-commit debug version
> added mypy to tox

- README.md
Update the arguments for the 'Unify' command to conform to the rest of the commands described.
> minor fix to readme

- README.md
- demisto_sdk/core.py
- demisto_sdk/dev_tools/linter.py
- test-requirements.txt
- tests/linter_test.py
- tests/test_files/fake_integration/fake_integration.py
fixes https://github.com/demisto/etc/issues/20567
> Add Bandit to linter

- CHANGELOG.md
- demisto_sdk/validation/file_validator.py
> Build fix - converted the script_regex argument to a list

- CHANGELOG.md
- demisto_sdk/__main__.py
Added it in __main__.py so the SDK will actually return the exit code
> sys.exit() fix

- CHANGELOG.md
> updating changelog before release

- demisto_sdk/dev_tools/linter.py
lint command does not return exit code 1 on failure - this fix should solve it
> adding return_code fix

- CHANGELOG.md
> adding changelog for release

- CHANGELOG.md
- demisto_sdk/common/constants.py
fixing CHANGELOG locating for packages
> fixing CHANGELOG locating for packages

- demisto_sdk/common/schemas/integration.yml
- demisto_sdk/common/schemas/integration_CHANGELOG.md
- tests/test_files/integration-test.yml
added also `feed` to `integration.yml` to check it.
> added feed to integration schema

- demisto_sdk/core.py
- demisto_sdk/yaml_tools/update_generic_yml.py
Fixed issues with commit hooks
> minor changes

- demisto_sdk/main.py
> fixing linter

- README.md
- docs/run_command.md
- docs/upload_command.md
* Added Run and Upload documentation files
* Rewritten Upload and Run commands description in `README.md` file
@reutshal
> Run and Upload documentation

- demisto_sdk/common/hook_validations/layout.py
- demisto_sdk/main.py
- demisto_sdk/validation/file_validator.py
Also added a small correction in layout validator.
> Layout validator was never called

- README.md
- docs/lint_command.md
- docs/unify_command.md
Updated the flags in lint command in readme.
Took the examples to the separate docs and expanded the lint examples (nothing to expand in unify...). 
@reutshal - FYI
> Docs lint and unify

- .github/pull_request_template.md
- .gitignore
- demisto_sdk/dev_tools/linter.py
add CI env var for docker running pytest and pylint
See: https://github.com/demisto/content/pull/5327/commits/d4986009e4687ddd6c2220ac3794e5e60fdb00c3
* add pr template
* ignore mypy_cache
> Lint add CI env var

- README.md
- docs/format_command.md
> Added readme for format command.

- demisto_sdk/common/schemas/integration.yml
- tests/test_files/integration-test.yml
> move feed to the right place

- requirements.txt
- test-requirements.txt
> change location of dateparser to requirements

- demisto_sdk/common/schemas/playbook.yml
- demisto_sdk/yaml_tools/update_playbook.py
Ready
`format` now adds a `description` tag to playbook.
Fixed playbook scheme
> fixed playbook scheme

- demisto_sdk/validation/file_validator.py
Ready
`Added files` was missing the `reputation` skip.
> Skipped validation for added files as well

- demisto_sdk/dev_tools/lint_manager.py
> Create file for failed packages

- CHANGELOG.md
- demisto_sdk/common/hook_validations/integration.py
- demisto_sdk/common/hook_validations/structure.py
- demisto_sdk/validation/file_validator.py
> Fix bc break and hidden

- CHANGELOG.md
- demisto_sdk/common/schemas/integration.yml
Ready
Added additionalinfo field to integration->configuration
> Added additionalinfo field to integrations

- CHANGELOG.md
- README.md
- demisto_sdk/common/templates/HelloWorld/HelloWorld.py
- demisto_sdk/dev_tools/initiator.py
- demisto_sdk/main.py
- docs/init_command.md
Ready
Fixed init bug where error would occur if no name given.
added "pack" parameter solely for clarity sake...
> init fix and adding pack param.

- demisto_sdk/validation/secrets.py
- tests/secrets_test.py
- tests/test_files/secrets_white_list.json
In Progress
fixes https://github.com/demisto/etc/issues/21172
fixes https://github.com/demisto/etc/issues/21173
Fix bug in secrets
> fix secrets

- demisto_sdk/main.py
> added the option for -h

- CHANGELOG.md
- demisto_sdk/common/hook_validations/structure.py
Ready
fixes: https://github.com/demisto/etc/issues/20868
If docker image changed this should break backwards
> fixing image validation

- .circleci/config.yml
- CHANGELOG.md
- demisto_sdk/common/hook_validations/integration.py
- demisto_sdk/common/hook_validations/structure.py
- tests/integration_test.py
- tox.ini
Ready
My build was failing because demisto-sdk validate failed. But haven't printed any specific reason for that. The problem was because `is_there_duplicate_params` returned True even there was no duplicates
> fixed - is_there_duplicate_params returned True even there was no duplicates

- CHANGELOG.md
- README.md
- demisto_sdk/common/git_tools.py
- demisto_sdk/dev_tools/lint_manager.py
- demisto_sdk/main.py
- docs/lint_command.md
Ready
fixes:https://github.com/demisto/etc/issues/21226
Added circle flag to indicate a lint run in circle
> fixing lint bug

- docs/format_command.md
Ready.
Update docs for format command about --use-git flag.
> update format command docs

- .circleci/config.yml
- .pre-commit-config.yaml
- demisto_sdk/json_to_outputs/json_to_outputs.py
- demisto_sdk/validation/secrets.py
- docs/create_command.md
- docs/format_command.md
- docs/run_command.md
- docs/run_playbook_command.md
- docs/secrets.md
- docs/split_yml_command.md
- docs/unify_command.md
- docs/upload_command.md
- docs/validate_command.md
- tests/integration_test.py
- tests/unifier_test.py
Ready
* Fix pre-commit stuff. 
* Remove mypy from pre-commit: It doesn't run it properly and we have it part of tox (not enforced).
* Add pre-commit to build step
> Pre commit

- .pre-commit-config.yaml
Ready
master broke after adding the pre-commit to the build. removing the branch check from pre-commit so it can work on master during the build.
> remove branch check from pre-commit

- demisto_sdk/yaml_tools/content_creator.py
Ready
Include doc-howto.json in content bundle. New file needed by server, following the doc migration.
Related content PR: https://github.com/demisto/content/pull/5506
> add doc-howto.json

- demisto_sdk/common/constants.py
- demisto_sdk/common/hook_validations/integration.py
- tests/integration_test.py
Ready
validation that feed integration `fromversion`field will be 5.5.0 or above.
> added validation to fromversion in feed integration

- demisto_sdk/core.py
> update version number

- demisto_sdk/common/constants.py
- demisto_sdk/common/hook_validations/integration.py
- demisto_sdk/common/hook_validations/script.py
- demisto_sdk/common/hook_validations/structure.py
Ready
fixes: https://github.com/demisto/etc/issues/21472
fixes: https://github.com/demisto/etc/issues/21229
wait with merge for @GalRabin
> Fix wrong term in dockerimage validation

- demisto_sdk/commands/format/tests/formatting_test.py
- demisto_sdk/commands/format/update_playbook.py
Ready 
fixes: https://github.com/demisto/etc/issues/21681
Check if a description already exists for a task and if so don't override it with an empty value
> update playbook format

- demisto_sdk/commands/lint/lint_manager.py
Ready
Update _check_should_run_pkg method to gets the package difference for master brach
> update _check_should_run_pkg to get changes in master

- CHANGELOG.md
> add generate-docs to CHANGELOG

- docs/release_guide.md
Ready
https://github.com/demisto/demisto-sdk/releases/tag/v0.3.7
> edit-readme release guide

- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/commands/validate/file_validator.py
Ready/In Progress/In Hold (Reason for hold)
related: https://github.com/demisto/etc/issues/21624
don't try to fetch original files in case of added file.
before:
after:
> filter no such file warning for added files

- demisto_sdk/commands/common/hook_validations/incident_field.py
- demisto_sdk/commands/common/tests/incident_field_test.py
Ready.
fixes: https://github.com/demisto/etc/issues/21682
ensure that version is -1 and from version is at least 5.0.0.
> Adding version and from version test for incident fields

- demisto_sdk/__main__.py
> Unify - Do no require outputfile

- CHANGELOG.md
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/create_artifacts/content_creator.py
- demisto_sdk/commands/create_artifacts/tests/content_creator_test.py
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzure/TestPlaybooks/just_a_test_script.yml
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzure/TestPlaybooks/playbook-FeedAzure_test_copy_no_prefix.yml
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzure/TestPlaybooks/script-prefixed_automation.yml
Ready
fixes: https://github.com/demisto/etc/issues/22420
> prefixed only needed file in TestPlaybooks repo

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/incident_field.py
- demisto_sdk/commands/common/tests/incident_field_test.py
Ready
fixes: https://github.com/demisto/etc/issues/22405
> incident_field from version BC check addition

- docs/release_guide.md
> release-guide-update

- CHANGELOG.md
- demisto_sdk/commands/init/initiator.py
Ready
fixes: demisto/etc#22459
Removed the `display` field from init script.
> Remove invalid `display` field from init script

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/script.py
Ready
fixes: https://github.com/demisto/etc/issues/22450
Changed the error message for v2 validation hook
> V2misleadingfix

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/reputation.py
- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/commands/common/schemas/reputation.yml
- demisto_sdk/commands/common/tests/reputation_test.py
- demisto_sdk/commands/common/tests/structure_test.py
- demisto_sdk/commands/validate/file_validator.py
- demisto_sdk/tests/constants_test.py
- demisto_sdk/tests/test_files/reputation-cidr-invalid.json
- demisto_sdk/tests/test_files/reputation-cidr-valid.json
- demisto_sdk/tests/test_files/reputations-invalid.json
Ready
fixes: https://github.com/demisto/etc/issues/21016
ReputationValidator and unskip reputation-*.json from the validate flow.
> Reputation validations

- demisto_sdk/commands/create_artifacts/content_creator.py
> added beta rn collector

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/tools.py
Ready
fixes: https://github.com/demisto/etc/issues/22587
Added a warning message when not running on the latest version.
> Add a warning message when not running the latest sdk version

- CHANGELOG.md
> Added RN for 0.4.1

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/structure.py
Ready
fixes: https://github.com/demisto/etc/issues/22665
> validate fails on windows \ -> /

- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/create_artifacts/content_creator.py
- demisto_sdk/commands/lint/lint_manager.py
Ready
Fix bug in non-parallel run when common is in a base pack. Add utility functions for pwsh common.
> fix non parallel run of common

- README.md
Ready
The word `detailed` was written as "detalied" in the documentation.
> Fix Spelling Error

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/split_yml/extractor.py
- demisto_sdk/commands/split_yml/split_yml_command.md
- demisto_sdk/commands/split_yml/tests/extractor_test.py
Ready
fixes: https://github.com/demisto/etc/issues/22757
code and unit tests refactor as well.
> split-yml: Removed the yml_type argument

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/reputation.py
- demisto_sdk/commands/common/tests/reputation_test.py
Ready
fixes: https://github.com/demisto/etc/issues/22816
> validator of reputation(Indicator Type) didnot check on the details field

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/generate_test_playbook/generate_test_playbook_command.md
- demisto_sdk/commands/generate_test_playbook/test_playbook_generator.py
- demisto_sdk/commands/generate_test_playbook/tests/test_playbook_generator_test.py
- demisto_sdk/commands/init/init_command.md
- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/json_to_outputs/json_to_outputs.py
- demisto_sdk/commands/json_to_outputs/json_to_outputs_command.md
- demisto_sdk/commands/run_playbook/playbook_runner.py
- demisto_sdk/commands/unify/tests/unifier_test.py
- demisto_sdk/commands/unify/unifier.py
- demisto_sdk/commands/unify/unify_command.md
- demisto_sdk/commands/upload/uploader.py
Ready
lint will be done in @GalRabin PR
format in @orhovy PR
geenereate-docs/splt-yml in my  PRs
and all the rest in the linked pr that will follow: init, generate-test-playbook, json-to-outputs, upload, unify.
all links in the issue.
fixes: https://github.com/demisto/etc/issues/22758
> Input output args standartize

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/run_playbook/playbook_runner.py
- demisto_sdk/commands/upload/uploader.py
Ready
fixes: https://github.com/demisto/etc/issues/22760
* Fixed the --insecure argument in *upload*
* Added the --insecure argument in *run-playbook*
> -k --insecure argument missing and consistency fixes

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/generate_test_playbook/test_playbook_generator.py
- demisto_sdk/commands/generate_test_playbook/tests/test_playbook_generator_test.py
Ready
fixes: https://github.com/demisto/etc/issues/22757
> rm -t, yml_type, file_type args from sdk-commands

- demisto_sdk/commands/common/tests/pack_metadata_validator_test.py
> Fix test file

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/configuration.py
Ready
fixes: https://github.com/demisto/etc/issues/22755
removed the env-dir var.
did not find usage for him throughout the code that requiered configuring him beforehand.
also consulted with fv.
@liorblob Is there anything else specific I should check?
> rm env-dir

- docs/development_guide.md
> dev guide update

- demisto_sdk/commands/create_id_set/tests/id_set_creator_test.py
- requirements.txt
Added `gitpython` to the requirements as well
> Id set - more test logic

- CHANGELOG.md
- demisto_sdk/commands/generate_docs/generate_integration_doc.py
- demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
Ready
fixes: https://github.com/demisto/etc/issues/22989
> general section was not being generated correctly

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/incident_type.py
Ready
fixes: https://github.com/demisto/etc/issues/23024
> Incident type validation failed

- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/release_notes.py
Ready
fixes: https://github.com/demisto/etc/issues/23005
gone over the repo, found only 2 references and fixed them.
> github content docs -> xsoar.pan.dev

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/playbook.yml
Ready
fixes: https://github.com/demisto/etc/issues/23035
@liorblob Please release only after this is merged.
> Added the *slareminder* field to the Playbook schema.

- demisto_sdk/commands/common/schemas/playbook.yml
Ready
will cause playbook be shown as disabled.
> added hidden key to playbook schema

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/playbook.py
- demisto_sdk/commands/common/tests/playbook_test.py
Ready
Validation of condition branches compares the declared vs. used branches using a case sensitive comparison. After reviewing this with @idovandijk it was decided this behavior is not the intended validation, and as such, it was removed.
Validated with playbook from https://github.com/demisto/content/pull/6132
> [Fix] Added case insensitivity to playbook condition validation

- CONTRIBUTION.md
Ready
Table of contents links were not set properly
> fix table of contents

- demisto_sdk/__main__.py
Ready
fixes: https://github.com/demisto/etc/issues/22551
> hide id-set, add decorators

- demisto_sdk/commands/generate_docs/common.py
- demisto_sdk/commands/generate_docs/generate_integration_doc.py
- demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
Ready
Small fixes to the generate integration docs so there are better compliant with mdx requirements of our docs site.
> Mdx compliant docs

- .github/pull_request_template.md
- .pre-commit-config.yaml
- CONTRIBUTION.md
Ready
Updated docs & pr template
> Contribution guide update, PR template update

- demisto_sdk/__main__.py
added a product prefix to the version print (similar to python):
instead of:
> improve version print

- CHANGELOG.md
> changelog for fix get_remote_file for md files

- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/init/tests/initiator_test.py
Added tests for `init`:
- `get_created_dir_name`
- `get_object_id`
- `create_metadata`
- `get_valid_user_input`
- `create_new_directory`
> Initiator - tests

- CHANGELOG.md
- demisto_sdk/commands/secrets/README.md
- demisto_sdk/commands/secrets/secrets.py
- demisto_sdk/commands/secrets/tests/secrets_test.py
- demisto_sdk/tests/test_files/fake_pack/.secrets-ignore
fixes: https://github.com/demisto/etc/issues/23580
> Check pack secrets against provided whitelist as well

- demisto_sdk/commands/secrets/secrets.py
- demisto_sdk/commands/secrets/tests/secrets_test.py
Change from regex replace to string replace for cleaning whitelist items from scanned file
> Change regex replace to string replace in whitelisted items replace

- demisto_sdk/commands/create_artifacts/content_creator.py
Fixed `content_packs.zip` creation with packs that include old format unified files, mostly located in `Legacy` pack.
> Fixed pack content creation with unified format script/integration files

- CHANGELOG.md
> added new rn section

- demisto_sdk/commands/lint/helpers.py
Corrected typo in a warning message
> Corrected typo in warning message

- demisto_sdk/commands/secrets/secrets.py
- demisto_sdk/commands/secrets/tests/secrets_test.py
handling escape characters from whitelist.json.
> Fix bug secrets escape

- CHANGELOG.md
- demisto_sdk/commands/format/README.md
- demisto_sdk/commands/format/format_module.py
- demisto_sdk/commands/format/tests/test_formatting_json_test.py
- demisto_sdk/tests/constants_test.py
fixes: https://github.com/demisto/etc/issues/23683
Added an exeption when the output given is not a file path
wrong directory:
correct directory:
> Output error msg

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/hook_validations/id.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/script.py
- demisto_sdk/commands/common/hook_validations/structure.py
fixes: https://github.com/demisto/etc/issues/22589
Suggest the command to execute to fix the validation failure (if one exists).
> Update Validation Failure Messages

- demisto_sdk/__main__.py
- demisto_sdk/commands/validate/README.md
> Fixed readme for validate

- demisto_sdk/commands/validate/file_validator.py
> halpert Handling the case file_path is a tuple due to renaming or moving

- demisto_sdk/commands/create_id_set/README.md
> Fixed readme - Create id_set

- demisto_sdk/commands/download/README.md
> Update README.md download

- demisto_sdk/commands/split_yml/README.md
> typo fix in split-yml README + ref link to dir structure

- CHANGELOG.md
> Added upload changes to changelog

- demisto_sdk/commands/lint/helpers.py
fixes: https://github.com/demisto/etc/issues/24009
> Fixed typos

- CHANGELOG.md
- demisto_sdk/commands/upload/tests/uploader_test.py
- demisto_sdk/commands/upload/uploader.py
- demisto_sdk/tests/integration_tests/upload_integration_test.py
Fixed issue where a not supported file was considered as incident field file
> Fixed typo

- demisto_sdk/commands/generate_docs/generate_playbook_doc.py
- demisto_sdk/tests/integration_tests/generate_docs_integration_test.py
fixes: https://github.com/demisto/etc/issues/23828
> Fixed playbook readme name file

- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/tests/test_linter/conftest.py
- demisto_sdk/commands/lint/tests/test_linter/gather_facts_test.py
- demisto_sdk/commands/lint/tests/test_linter/os_runner_test.py
fixes: https://github.com/demisto/etc/issues/23916
Collect unit-test files for linting with flake8.
> Collect unittest Files for Linting with flake8

- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/integration_test.py
fixes: https://github.com/demisto/etc/issues/23586
> print yaml formed error instead of json for integration files

- demisto_sdk/commands/lint/commands_builder.py
> fix mypy in commands-builder

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/validate/tests/validators_test.py
fixes: demisto/etc#24080
Unclear error message in case of integration with no tests configured
> Improving unclear error messages

- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/init/tests/initiator_test.py
- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/linter.py
fixes:
```python
demisto_sdk/commands/lint/helpers.py:100: error: Incompatible return value type (got "int", expected "bool")
demisto_sdk/commands/lint/helpers.py:266: error: Name 'container_obj' already defined on line 260
demisto_sdk/commands/lint/helpers.py:289: error: Incompatible return value type (got "str", expected "float")
demisto_sdk/commands/lint/helpers.py:309: error: Item "None" of "Optional[IO[bytes]]" has no attribute "read"
demisto_sdk/commands/lint/helpers.py:313: error: Incompatible return value type (got "Union[bytes, Any]", expected "str")
demisto_sdk/commands/init/initiator.py:258: error: Incompatible types in assignment (expression has type "int", variable has type "str")
demisto_sdk/commands/init/initiator.py:267: error: Unsupported operand types for - ("str" and …
```
> mypy fix helprers, initiator, linter

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/commands/common/tests/structure_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/validate/file_validator.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/tests/constants_test.py
- demisto_sdk/tests/test_files/integration_ignored_invalid_unified.yml
- demisto_sdk/tests/test_tools.py
fixes: https://github.com/demisto/etc/issues/23067
- Printing fix suggestions with json.dumps or yaml.parse according to the file
- ignoring _unified files
- Making release notes error message more readable
> demisto/etc#23067 Improving unclear error messages

- README.md
- demisto_sdk/commands/download/README.md
update sdk global docs & download command local docs
> Download docs

- CHANGELOG.md
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_generic_yml.py
- demisto_sdk/commands/format/update_playbook.py
- demisto_sdk/tests/integration_tests/format_integration_test.py
fixes: https://github.com/demisto/etc/issues/23825
https://github.com/demisto/etc/issues/23948
https://github.com/demisto/etc/issues/23448
https://github.com/demisto/etc/issues/23937
> Fixed yes, no changing to boolean

- demisto_sdk/__main__.py
- demisto_sdk/commands/lint/README.md
- demisto_sdk/commands/lint/lint_manager.py
- demisto_sdk/commands/lint/tests/linter_manager_test.py
Reverts demisto/demisto-sdk#412 cause of https://github.com/demisto/etc/issues/24267
> Revert "Fixed report to correspond to needed failing unit test file structure"

- demisto_sdk/__main__.py
- demisto_sdk/commands/lint/lint_manager.py
- demisto_sdk/commands/lint/tests/linter_manager_test.py
Partially fixes: demisto/etc#23791
> Reverted changes that broke sdk master

- CHANGELOG.md
- docs/release_guide.md
> updating release docs and changelog file

- demisto_sdk/commands/common/schemas/classifier.yml
- demisto_sdk/commands/common/schemas/indicatorfield.yml
> schema changes for classifiers and indicatorfield

- .flake8
- demisto_sdk/__main__.py
- demisto_sdk/commands/download/downloader.py
- demisto_sdk/commands/format/update_generic.py
- demisto_sdk/commands/format/update_generic_json.py
- demisto_sdk/commands/format/update_generic_yml.py
- demisto_sdk/commands/format/update_integration.py
- demisto_sdk/commands/format/update_layout.py
- demisto_sdk/commands/format/update_playbook.py
- demisto_sdk/commands/generate_docs/generate_script_doc.py
- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/lint/commands_builder.py
- demisto_sdk/commands/lint/lint_manager.py
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/tests/constants_test.py
- demisto_sdk/tests/test_files/Packs/DummyPack/Integrations/UploadTest/UploadTest.py
- demisto_sdk/tests/test_files/content_repo_example/Integrations/Securonix/Securonix.py
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.py
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzureValid/Integrations/FeedAzureValid/FeedAzureValid.py
Removed f' strings with missing placeholders to fix flake8 errors
> removed f' strings with missing placeholders

- demisto_sdk/commands/download/README.md
> download docs update

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/image.py
- demisto_sdk/commands/common/tests/image_test.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/tests/test_files/not_default_image_integration-Zoom.yml
> Image validatition will not consider image in the yml file as error

- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/incident_field.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/validate/file_validator.py
- demisto_sdk/commands/validate/tests/validators_test.py
* Added skipping method for all files validation
* added incident_fields white listed names
* added progress printing for all files validations
> All files validations fixes

- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/playbook.py
- demisto_sdk/commands/common/tests/playbook_test.py
- demisto_sdk/commands/validate/file_validator.py
fixes: demisto/etc#24517
Removed validation of test playbooks
> Test playbooks are no longer validated

- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/validate/file_validator.py
> Fix for rn bug

- CHANGELOG.md
> 1-0-5 release notes

- CHANGELOG.md
> Release branch 1-0-9

- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
fixing PA104 - where looked for regex in pack-ignore
> fixing PA104 error

- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/commands/validate/file_validator.py
> error format fixs

- demisto_sdk/commands/common/tools.py
- requirements.txt
fixes color setting for windows.
@idovandijk please provide a screenshot of the colored command output
will not affect Mac users:
> replaced ansi color with colorama to support cli colors in windows

- demisto_sdk/commands/validate/README.md
> updating validate README.md

- .circleci/config.yml
- demisto_sdk/utils/trigger_against_content_branch.sh
> Adding trigger against content branch

- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/hook_validations/incident_field.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/hook_validations/release_notes.py
- demisto_sdk/commands/common/tests/pack_unique_files_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
- demisto_sdk/commands/validate/file_validator.py
RN should not be checked in modified-files flow.
RN should be checked without structure validation in added-files flow
> fixing bug in new rn validation

- .circleci/config.yml
- CHANGELOG.md
- requirements.txt
> Release 1-1-1

- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/incident_field.py
- demisto_sdk/commands/common/schemas/report.yml
- demisto_sdk/commands/common/tests/incident_field_test.py
- demisto_sdk/commands/validate/file_validator.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/tests/test_files/fake_pack/.pack-ignore
…RP102 to allowed ignored errors, adding some additional prints
Updating reports schema and adding to schema check, adding IF107 and RP102 to allowed ignored errors, adding some additional prints
> Validate - several improvements 

- demisto_sdk/__main__.py
> Update ReleaseNotes Fix for added files not discovered while generating release notes

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/integration.yml
fixes: https://github.com/demisto/content/pull/7359
Added new field to integration schema for incremental feeds.
> added new key to integration schema

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/secrets/secrets.py
- demisto_sdk/commands/secrets/tests/secrets_test.py
- demisto_sdk/commands/validate/file_validator.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/tests/integration_tests/secrets_integration_test.py
fixes: https://github.com/demisto/etc/issues/25250
The issue occurred when the file name had a space in it.
> Secrets path not found - fixed the issue + UT

- CHANGELOG.md
- demisto_sdk/commands/validate/file_validator.py
> Ignored validation non supported fix

- CHANGELOG.md
adding ignored errors changelog
> adding ignored errors changelog

- demisto_sdk/__main__.py
- demisto_sdk/commands/upload/README.md
fixes: https://github.com/demisto/etc/issues/24371
Upload classifiers using demisto-sdk is working on 6.0.0 version and up.
Added a clarification for it in the README file and in the help option in sdk upload.
> Add a clarification about sdk upload classifiers

- demisto_sdk/commands/create_artifacts/content_creator.py
Fixed prefix of scripts files in Test Playbooks folder of packs.
> Fixed adding prefix in scripts (test playbooks folder)

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/incident_type.py
- demisto_sdk/commands/common/tests/incident_type_test.py
fixes: https://github.com/demisto/etc/issues/24193
Add a validation that checks the playbookID field in incidents type is not UUID.
> Invalid playbookID in incident type

- demisto_sdk/__main__.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/create_artifacts/content_creator.py
- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/lint_manager.py
- demisto_sdk/commands/validate/file_validator.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
Identify if demisto-sdk running inside external repository
> identify external repository

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/description.py
- demisto_sdk/commands/validate/file_validator.py
minor visual improvements and changelog.
> Minor visual changes

- .circleci/config.yml
- CHANGELOG.md
- demisto_sdk/commands/common/tools.py
- Fixed an issue with the server version compare
> Release 1-1-2

- demisto_sdk/commands/common/hook_validations/description.py
The description for non-beta integrations is not found correctly.
> description bug fix

- demisto_sdk/commands/download/downloader.py
removing support of old classifiers in download
> removing support of old classifiers in download

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
> SDK release 1-1-3

- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
> remove spaces from rns updater

- demisto_sdk/commands/validate/file_validator.py
TestPlaybooks are being checked on added files
> fixing bug - testplaybook checked on added files

- .circleci/config.yml
> skip coveralls on fork

- demisto_sdk/commands/unify/tests/unifier_test.py
- demisto_sdk/commands/unify/unifier.py
Perform case insensitive ignore of test files and so on when doing unify.
> Unify: case insensitive

- demisto_sdk/commands/update_release_notes/update_rn.py
> get displayname now gets displayname

- demisto_sdk/commands/common/tests/update_id_set_test.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/find_dependencies/find_dependencies.py
- demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py
- demisto_sdk/tests/test_files/DummyPack/Integrations/DummyIntegration/DummyIntegration.yml
- demisto_sdk/tests/test_files/DummyPack/Integrations/integration-DummyIntegration.yml
- demisto_sdk/tests/test_files/id_set/id_set.json
Related: https://github.com/demisto/etc/issues/24610
Added the fields to id_set
> Dependencies integration

- .circleci/config.yml
- CHANGELOG.md
- demisto_sdk/commands/common/schemas/playbook.yml
- demisto_sdk/commands/common/tests/update_id_set_test.py
> Fix playbooks schemas

- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://github.com/demisto/etc/issues/25884
> Update error message for is_bump_required in Update Release Notes

- .circleci/config.yml
Added the update_conf_json script run before the validate step
Triggered master and validate -a passes successfully
> update conf json before validate step

- demisto_sdk/commands/unify/tests/unifier_test.py
- demisto_sdk/commands/unify/unifier.py
Update developer contribution header to community
> Update developer to community

- demisto_sdk/commands/common/constants.py
> Fix regex for remote and upstream detection

- demisto_sdk/commands/common/hook_validations/base_validator.py
preventing situations where file_path in handle_error is not a string:
> making sure file_path in handle_error is a string

- demisto_sdk/commands/common/update_id_set.py
> dependencies- fix

- demisto_sdk/commands/common/schemas/script.yml
fixes: https://github.com/demisto/etc/issues/25695
removing "tags" from required fields in scripts - that way it is not enforced in validate and not auto-added in format.
> removing "tags" from required fields in scripts

- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_playbook.py
- demisto_sdk/tests/test_files/format_new_playbook_copy.yml
fixes: https://github.com/demisto/etc/issues/23560
remove _dev _copy from subplaybooks
> remove _dev _copy from subplaybooks

- demisto_sdk/commands/common/hook_validations/structure.py
fixes: https://github.com/demisto/etc/issues/25622
schema should not be checked for test-playbooks
> Test Playbooks structure should not be checked

- CHANGELOG.md
- TestSuite/contribution.py
- TestSuite/integration.py
fixes: mypy errors from merging https://github.com/demisto/demisto-sdk/pull/577 - see [failing build](https://app.circleci.com/pipelines/github/demisto/demisto-sdk/4560/workflows/21b72515-d288-4630-b229-1498e3e650a0/jobs/4661/steps)
Fixes the mypy errors that my commits entered into the repo.
> Fix mypy Errors

- .circleci/config.yml
- .pre-commit-config.yaml
Parallelizes the demisto-sdk circleci build
> Parallelize Circle Build

- .circleci/config.yml
fixes: https://app.circleci.com/pipelines/github/demisto/demisto-sdk/4595/workflows/32afb508-9f4f-405a-b4ed-9d8af664b88b
Added a new job called `checkout-content` which checks out the `content` repo and persists the repo directories to the workspace. Makes the jobs that use the content repo in their commands require the aforementioned new job.
> Fix Parallel Build

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/init/README.md
- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/init/tests/initiator_test.py
Adds a `description` option to the command. Now when the `contribution` option is provided, the command will take into account values passed for `name` and `description` and use them in creating the converted contribution pack.
> Init Command - Contribution Option Flow Improvements

- demisto_sdk/commands/create_artifacts/content_creator.py
- requirements.txt
fixing the way yml are being rewritten by content creator
> fixing yml script write bug

- demisto_sdk/commands/create_artifacts/content_creator.py
- demisto_sdk/commands/create_artifacts/tests/content_creator_test.py
there are 3 bundles tests, content and packs
file with fromversion below 6.0.0  should be in both content and packs
file with fromversion above 6.0.0  should only be in packs
file with toversion 5.9.9 or below should only be in content
content and tests bundle act the same
> fixing content creator logic

- demisto_sdk/commands/create_artifacts/content_creator.py
new layouts prefix should be `layoutscontainer`
> Content Creator - fix layoutscontainer prefix

- .mypy.ini
Added mypy.ini config file with the recommended config for running mypy. Note that check_untyped_defs is commented out as it requires further review. 
The config improves the output and also includes error codes for excluding.
Output before the config (on a test error):
Output after:
> mypy config file

- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
Validate should always pass when running using git on release branch.
> Validate command release branch fix

- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
Improving pack metadata bump error message -now includes the current found version
> Improving pack metadata bump error message

- demisto_sdk/commands/lint/linter.py
https://bandit.readthedocs.io/en/latest/plugins/b701_jinja2_autoescape_false.html
> linter - setting jinja2 env autoescape to true

- CHANGELOG.md
added v1.1.6 to CHANGELOG file
> added v1.1.6 to CHANGELOG file

- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/init/templates/HelloWorld/HelloWorld.yml
- demisto_sdk/tests/test_files/DummyPack/Integrations/DummyIntegration/DummyIntegration.yml
- demisto_sdk/tests/test_files/DummyPack/Integrations/integration-DummyIntegration.yml
updated integration default classifiers and mappers fields
> Update integration default classifiers and mappers fields

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/integration_test.py
fixes: https://github.com/demisto/etc/issues/26681
Allowed 'feedReputation' parameter to be hidden
> allow 'feedReputation' parameter to be hidden

- CHANGELOG.md
- demisto_sdk/commands/unify/unifier.py
fixes: 
fixed referenced before assignment error in unifier for JS packages.
> Add js package support in unifier

- CHANGELOG.md
- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/init/tests/initiator_test.py
- demisto_sdk/tests/integration_tests/init_integration_test.py
related to: https://github.com/demisto/etc/issues/25229
Added new field `githubUser` in init of `pack_metadata`.
> Added githubUser field in init of pack metadata

- demisto_sdk/commands/validate/validate_manager.py
> id_set creation fix

- demisto_sdk/commands/common/tests/update_id_set_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/unify/unifier.py
- demisto_sdk/tests/test_files/invalid_file_structures/dashboard.json
- demisto_sdk/tests/test_files/invalid_file_structures/integration.yml
- demisto_sdk/tests/test_files/invalid_file_structures/playbook.yml
- demisto_sdk/tests/test_files/invalid_file_structures/script.yml
- demisto_sdk/tests/test_files/yml_invalid_structure.yml
fixes: https://github.com/demisto/etc/issues/26485
fixes: https://github.com/demisto/etc/issues/26225
fixes: https://github.com/demisto/etc/issues/26484
added support for the Windows file system (path separator).
> Support windows in create id set

- demisto_sdk/__main__.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/tests/constants_test.py
- demisto_sdk/tests/test_files/integration-test-beta.yml
fixes: https://github.com/demisto/etc/issues/27033
Update the file type validation for commands:
- split-yml
- extract-code
- generate-test-playbook
- generate-docs
to support beta integration.
> Support beta integration in the commands split-yml, extract-code, generate-test-playbook and generate-docs

- demisto_sdk/commands/common/schemas/integration.yml
required for: https://github.com/demisto/etc/issues/26803
Added support for sourcemoduleid in the integrations schema.
> Added sourcemoduleid to the integrations schema

- CHANGELOG.md
- demisto_sdk/commands/find_dependencies/find_dependencies.py
- demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py
> Added version filtering in find dependencies

- demisto_sdk/commands/common/hook_validations/docker.py
Make a static method in the docker image validator to get the latest tag for a docker image.
> Make a generic function to get docker image tag

- CHANGELOG.md
- demisto_sdk/commands/upload/tests/uploader_test.py
- demisto_sdk/commands/upload/uploader.py
- demisto_sdk/tests/test_files/Packs/DummyPack/TestPlaybooks/DummyTestPlaybook.yml
Added support for Test PB in upload
> Added support for Test PB in upload

- demisto_sdk/commands/split_yml/extractor.py
- demisto_sdk/commands/split_yml/tests/extractor_test.py
- demisto_sdk/commands/unify/tests/unifier_test.py
- demisto_sdk/commands/unify/unifier.py
fixes: https://github.com/demisto/etc/issues/27195
Add noqa comment to import of common server. In unifier support also comments at end of import.
> add noqa comment to commonserver import

- demisto_sdk/commands/create_artifacts/content_creator.py
- demisto_sdk/commands/lint/lint_manager.py
- demisto_sdk/commands/validate/file_validator.py
fixed few LGTM alerts regarding imports.
> fixed import warnings of LGTM

- demisto_sdk/commands/lint/resources/pipfile_python2/Pipfile.lock
- demisto_sdk/commands/lint/resources/pipfile_python3/Pipfile
- demisto_sdk/commands/lint/resources/pipfile_python3/Pipfile.lock
Update default dev Pipfile packages.
> update base Pipfile packages

- demisto_sdk/commands/openapi_codegen/base_code.py
- demisto_sdk/tests/test_files/swagger_python.txt
Remove `Bearer` from the API key header
> swagger tool - remove bearer

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/update_release_notes_integration_test.py
fixes: https://github.com/demisto/etc/issues/27214
fixes: https://github.com/demisto/etc/issues/27215
fixes: https://github.com/demisto/etc/issues/26864
test scripts were recognized as scripts.
> fixed test script file type

- demisto_sdk/commands/common/errors.py
fixes: https://github.com/demisto/etc/issues/26733
updated reference link in the error message.
> updated docs link in error message

- CHANGELOG.md
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/init/tests/initiator_test.py
fixes: demisto/etc/issues/27060
fixes: demisto/etc/issues/24011
Fixed an issue where the **Init** command failed on scripts.
Changed the init templates source to the remote repo.
init will use local templates only if the remote source is not reachable.
> Init Templates and bug fix

- demisto_sdk/commands/download/downloader.py
- demisto_sdk/commands/download/tests/downloader_test.py
- demisto_sdk/commands/split_yml/extractor.py
- demisto_sdk/commands/split_yml/tests/extractor_test.py
fixes: demisto/etc/issues/26862
Removed Changelog file creation when running split yml.
> Removed Changelog creation from split-yml command

- demisto_sdk/commands/format/update_generic_json.py
Fixed an issue where **format** removed keys with falsy values instead of null ones
> Format Bug fix

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
Added *--skip-pack-dependencies* flag to **validate** command to skip pack dependencies validation.
> Validate skip pack dependencies flag

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_integration.py
- demisto_sdk/tests/test_files/integration-fetch-valid.yml
fixes: demisto/etc/issues/26638
> DefaultValue in fetch related params fix

- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/create_id_set/tests/update_id_set_test.py
- demisto_sdk/commands/init/templates/HelloWorldScript/HelloWorldScript.py
> Fixed LGTM suggestion

- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_playbook.py
- demisto_sdk/tests/constants_test.py
fixes: demisto/etc/issues/27488
Fixed an issue where format failed for tpb
> Fixed an issue in tpb formatting

- CHANGELOG.md
- demisto_sdk/commands/openapi_codegen/openapi_codegen.py
- demisto_sdk/tests/test_files/swagger_config.json
- demisto_sdk/tests/test_files/swagger_pets.json
- demisto_sdk/tests/test_files/swagger_python.txt
- demisto_sdk/tests/test_files/swagger_yaml.yml
Fix ref direct access and not adding `*/*` headers to the code
> swagger tool - fix ref access and * headers

- demisto_sdk/commands/common/hook_validations/image.py
fixes: https://github.com/demisto/etc/issues/27512
> image validator - small attr change

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/release_notes.py
- demisto_sdk/commands/common/tests/release_notes_test.py
fixes: https://github.com/demisto/etc/issues/26292
Validation now fails when all release notes have been excluded.
> Fail validation when all release notes are excluded.

- .pre-commit-config.yaml
- tox.ini
Fixing:
- **Mypy** - run by tox and pre-commit - only pre-commit run mypy now.
- **isort** - Fix error if found.
- **Excluded files** - Global excluded and better regex exclude.
> fix pre-commit and tox

- CHANGELOG.md
- demisto_sdk/commands/openapi_codegen/openapi_codegen.py
- demisto_sdk/tests/test_files/swagger_pets.json
Ignore empty data in paths in the swagger JSON.
> swagger tool - handle empty data

- CHANGELOG.md
Missing changelog for recent update-release-notes fix.
> Add update-rn change to changelog

- CHANGELOG.md
> validate-error-msg

- CHANGELOG.md
- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/tests/helper_test.py
fixes: https://github.com/demisto/etc/issues/26621
Added a check for ci env var 
> Run lint on circle ci

- demisto_sdk/__main__.py
Updated the parameter of the pack parameter to pack_path.
> Updated parameter name in UpdateRN

- CHANGELOG.md
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/templates/dockerfile.jinja2
see cert in docker in the referenced issue
fixes: https://github.com/demisto/etc/issues/25468
> fix docker image pulling for pwsh in linter

- demisto_sdk/commands/lint/linter.py
> Lint not failing

- CHANGELOG.md
> changelog for json2outputs

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/init/tests/initiator_test.py
fixes: https://github.com/demisto/etc/issues/27550
> Fixed an issue where **init** offered a non relevant pack support type.

- demisto_sdk/commands/split_yml/extractor.py
fixed argument identifier in `split-yml` command output.
> updated split-yml next steps comment

- demisto_sdk/commands/common/schemas/integration.yml
fixes: https://github.com/demisto/etc/issues/28049
> Added new mirroring fields to yml schema

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://github.com/demisto/etc/issues/27997
> Fix issue where out of sync packs caused a crash

- demisto_sdk/__main__.py
- demisto_sdk/commands/init/README.md
Update the `init` command's documentation to reflect the updated command.
> Update the init Command's Documentation

- demisto_sdk/__main__.py
- demisto_sdk/commands/json_to_outputs/README.md
- demisto_sdk/commands/json_to_outputs/json_to_outputs.py
Fixes: https://github.com/demisto/demisto-sdk/pull/709
> fixed descriptions json-to-outputs

- CHANGELOG.md
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/28109
Adding missing RN testing for old format files
> Adding missing RN testing for old format files

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/docker.py
- demisto_sdk/commands/format/README.md
- demisto_sdk/commands/format/format_module.py
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_integration.py
- demisto_sdk/commands/format/update_script.py
- demisto_sdk/tests/test_files/update-docker/Slack.yml
- demisto_sdk/tests/test_files/update-docker/SlackAsk.yml
reference: https://github.com/demisto/etc/issues/25903
Add the option to update the docker image as part of the format command.
> format: support for updating docker image

- CHANGELOG.md
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/28140
> updated validate on deleted files

- docs/release_guide.md
> updated release guide

- demisto_sdk/commands/common/schemas/integration.yml
sourcemodule id was over indented. Moved it to root.
> [Fix] remove sourcemoduleid

- CHANGELOG.md
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/28216
adding rn validation for added files in existing packs
> adding rn validation for added files in existing packs

- demisto_sdk/commands/common/schemas/playbook.yml
fixes: https://github.com/demisto/etc/issues/28230
playbook schema fix
> playbook schema fix

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/28332
> Fixed an issue were doc_images required release-notes and validations

- demisto_sdk/__main__.py
- demisto_sdk/commands/create_artifacts/content_artifacts_creator.py
- demisto_sdk/commands/create_artifacts/tests/content_artifacts_creator_test.py
FYI - @yaakovi 
- Fix flag to true/false value.
- Fix summary to print only content_packs if flag is on.
I tested and validated functionality.
> Fix packs flag

- demisto_sdk/__main__.py
making create-content-artifacts hidden command to not confuse contribs
> making create-content-artifacts hidden command

- demisto_sdk/__main__.py
fixes: https://github.com/demisto/etc/issues/28370
> update-rn msg p -> i

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/release_notes.py
- demisto_sdk/commands/common/tests/release_notes_test.py
see referenced issue
fixes: https://github.com/demisto/etc/issues/28410
> Fixed an issue where renamed files were failing on *validate*

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
> Indicator field support in RN

- CHANGELOG.md
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/constants_test.py
- demisto_sdk/tests/test_files/fake_pack/Integrations/test_data/results.json
- demisto_sdk/tests/test_files/fake_pack/Integrations/test_data/results_json.py
fixes: https://github.com/demisto/etc/issues/28447
> Fixed an issue where files in test dirs where being validated

- demisto_sdk/commands/common/update_id_set.py
> fixed create-id-set timeout

- CHANGELOG.md
> changed changelog

- demisto_sdk/commands/create_artifacts/content_artifacts_creator.py
FYI - @roysagi @barchen1 
FIx suffix handling in create artifacts.
> Fix suffix

- demisto_sdk/commands/common/constants.py
> added TLP back

- demisto_sdk/commands/lint/lint_manager.py
> fixed return error

- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/28770
Handling the FileNotFoundError within filter_changed_files
> handling FileNotFoundError within filter_changed_files

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/playbook.yml
fixes: https://github.com/demisto/etc/issues/28932
Change the tags type to be mapping instead of string
> Schema error - playbook tags

- demisto_sdk/commands/lint/lint_manager.py
added check for only failure to be written to file.
> Fix for lint false failure in circle

- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/resources/pylint_plugins/xsoar_level_checker.py
> type only for py3

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/integration.yml
fixes: https://github.com/demisto/etc/issues/29063
Supporting the displaypassword field.
> integration schema fix

- CHANGELOG.md
- demisto_sdk/commands/lint/resources/pylint_plugins/xsoar_level_checker.py
- demisto_sdk/commands/lint/tests/test_pylint_plugin/xsoar_level_checker_test.py
- demisto_sdk/tests/integration_tests/xsoar_linter_integration_test.py
fixes: https://github.com/demisto/etc/issues/29033
removed return-type annotations and docstrings warnings msgs
> Removed return-type annotations and docstrings Warning msgs

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/test_playbook.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzureValid/TestPlaybooks/just_a_test_script.yml
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzureValid/TestPlaybooks/script-prefixed_automation.yml
fixes: https://github.com/demisto/etc/issues/29007
Added fromversion validation for test playbooks and scripts.
> adding test playbook validation

- CHANGELOG.md
> Updated the release note.

- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/tests/helper_test.py
added support for python2 pylint warnings which only have 'W:'
> Fixwarnigns

- CHANGELOG.md
- demisto_sdk/commands/unify/tests/unifier_test.py
- demisto_sdk/commands/unify/unifier.py
fixes: https://github.com/demisto/etc/issues/28898
Changed the Community contribution description.
> Changed description for community pack

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/format/format_module.py
- demisto_sdk/commands/format/update_classifier.py
- demisto_sdk/commands/format/update_dashboard.py
- demisto_sdk/commands/format/update_generic.py
- demisto_sdk/commands/format/update_generic_json.py
- demisto_sdk/commands/format/update_generic_yml.py
- demisto_sdk/commands/format/update_incidentfields.py
- demisto_sdk/commands/format/update_incidenttype.py
- demisto_sdk/commands/format/update_indicatorfields.py
- demisto_sdk/commands/format/update_indicatortype.py
- demisto_sdk/commands/format/update_integration.py
- demisto_sdk/commands/format/update_layout.py
- demisto_sdk/commands/format/update_mapper.py
- demisto_sdk/commands/format/update_playbook.py
- demisto_sdk/commands/format/update_pythonfile.py
- demisto_sdk/commands/format/update_report.py
- demisto_sdk/commands/format/update_script.py
- demisto_sdk/commands/format/update_widget.py
- demisto_sdk/tests/integration_tests/format_integration_test.py
fixes: https://github.com/demisto/etc/issues/28767
Added -y option to assume "yes" as answer to all prompts and run non-interactively
> Implement no interactive mode

- CHANGELOG.md
> Updated release notes

- demisto_sdk/__main__.py
Added example for pack path format in update-release-notes help section
> adding example for pack path in update-rn

- CHANGELOG.md
- demisto_sdk/commands/format/format_module.py
- demisto_sdk/commands/format/tests/test_formatting_json_test.py
- demisto_sdk/commands/format/update_connection.py
- demisto_sdk/commands/format/update_script.py
- demisto_sdk/tests/constants_test.py
fixes: https://github.com/demisto/etc/issues/28223
Added support for canvasContextConnections files in **format** command.
> Support Connections in format command

- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/29352
> Fixed validate against release branch

- demisto_sdk/commands/secrets/secrets.py
fixes: https://github.com/demisto/etc/issues/29445
> Fixed secrets link

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/secrets/secrets.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/update_release_notes_integration_test.py
fixes: https://github.com/demisto/etc/issues/28689
> Fixed metadata validation for NonSupported and Legacy packs

- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/schemas/integration.yml
> added IAM as an optional integration category (demisto-sdk)

- CONTRIBUTION.md
N/A
* Uses colon instead of hyphen for consistency
* add missing space
- [n/a] Tests
> Use colon instead of hyphen and add missing space

- .circleci/config.yml
Fix to the build failure introduced by latest content master.
> set python path

- CHANGELOG.md
- demisto_sdk/commands/unify/tests/unifier_test.py
- demisto_sdk/commands/unify/unifier.py
fixes: https://github.com/demisto/etc/issues/29747
> Unifier - handle no image for integration

- requirements-dev.txt
Added coloredlogs to the dev requirements
> Added coloredlogs to dev requirements

- CHANGELOG.md
- demisto_sdk/__main__.py
fixes: https://github.com/demisto/etc/issues/29109
> Update RN - pass text arg to all update rn calls

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/find_dependencies/find_dependencies_command.md
- demisto_sdk/tests/integration_tests/find_dependencies_integration_test.py
fixes: https://github.com/demisto/etc/issues/29684
> fixed -p to -i in find-dependencies

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/description.py
- demisto_sdk/commands/common/tests/description_test.py
fixes: https://github.com/demisto/etc/issues/29479
> Validate - do not warn about detailed desc for unified/deprecated integrations

- demisto_sdk/tests/workflow_test.py
pylance found some issues, fixed them.
> Workflow test fixes

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/28627
Validate  - old format files Improved error output
> Validate  - old format files Improved error output

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/playbook.py
- demisto_sdk/commands/common/tests/playbook_test.py
fixes: https://github.com/demisto/etc/issues/29836
Validate fails if there is a usage of DeleteContext in a playbook using all=yes
> added new playbook validation for deletecontext all=yes

- demisto_sdk/commands/generate_docs/generate_integration_doc.py
- demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
- demisto_sdk/tests/test_files/fake_integration/fake_README.md
> Generate Docs - change Demisto to Cortex XSOAR

- CHANGELOG.md
> updated rn

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/playbook.py
- demisto_sdk/commands/common/tests/playbook_test.py
fixes: https://github.com/demisto/etc/issues/29881
Added a new validation for using in playbooks.
> added using instance validation

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/validate/README.md
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
fixes: https://github.com/demisto/etc/issues/28828
> demisto-sdk validate --staged flag

- demisto_sdk/__main__.py
- demisto_sdk/commands/format/tests/test_formatting_json_test.py
- demisto_sdk/commands/format/update_connection.py
- demisto_sdk/commands/format/update_generic.py
fixes: https://github.com/demisto/etc/issues/29979
removed import of test file from an src file. used empty string as default value like in the rest of the update modules.
before and after the fix:
> removed import of test file in src file

- demisto_sdk/commands/common/hook_validations/readme.py
- demisto_sdk/commands/common/tests/readme_test.py
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_script.py
- demisto_sdk/tests/test_files/README-invalid2.md
- demisto_sdk/tests/workflow_test.py
fix readme validation to apply same mdx fix logic as in content-docs. Will detect now the following file https://github.com/demisto/content/blob/b63f7408b7b7afbc4db0c369955b8a9003232539/Packs/PhishTank/Integrations/PhishTankV2/README.md which failing to deploy in content-docs
change in workflow_test.py to lazy initialise ContentGitRepo so it isn't done in test discovery. @jochman FYI. 
> Readme validate fix

- CHANGELOG.md
- demisto_sdk/commands/openapi_codegen/openapi_codegen.py
- demisto_sdk/commands/openapi_codegen/tests/openapi_codegen_test.py
- demisto_sdk/tests/test_files/swagger_config.json
- demisto_sdk/tests/test_files/swagger_pets.json
- demisto_sdk/tests/test_files/swagger_python.txt
- demisto_sdk/tests/test_files/swagger_yaml.yml
fixes: https://github.com/demisto/etc/issues/29991
Fixed the functions duplication names.
Manage to run the entire flow and upload successfully to Demisto.
> Fixed duplicates in functions name

- CHANGELOG.md
fixes: https://github.com/demisto/etc/issues/30228
> Added release notes

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/docker.py
- demisto_sdk/commands/common/tests/docker_test.py
fixes: https://github.com/demisto/etc/issues/29728
https://github.com/demisto/etc/issues/29602
> Fix error for non existing docker

- CHANGELOG.md
- demisto_sdk/commands/lint/resources/pylint_plugins/partner_level_checker.py
- demisto_sdk/commands/lint/tests/test_pylint_plugin/partner_level_checker_test.py
fixes: https://github.com/demisto/etc/issues/30400
> Fixed finally clause in lint command

- demisto_sdk/commands/common/content/objects/pack_objects/incident_field/incident_field.py
- demisto_sdk/commands/common/content/objects/pack_objects/incident_type/incident_type.py
- demisto_sdk/commands/upload/tests/uploader_test.py
fixes: No issue yet
Incident types and fields didn't upload correctly. They now upload.
> Upload incident type + field fix

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/tests/constants_test.py
- demisto_sdk/tests/test_files/invalid-beta-integration.yml
- demisto_sdk/tests/test_files/valid-beta-integration.yml
fixes: https://github.com/demisto/etc/issues/29413
fixed to Validate ID was not modified
> fixed to Validate ID was not modified

- CHANGELOG.md
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/workflow_test.py
--staged flag checked diff against master instead of last commit.
> fixed staged flag no bringing only staged changes

- .circleci/config.yml
> Run validate files with python 3.8

- CHANGELOG.md
- demisto_sdk/commands/lint/resources/pylint_plugins/base_checker.py
- demisto_sdk/commands/lint/tests/command_builder_test.py
- demisto_sdk/commands/lint/tests/test_pylint_plugin/base_checker_test.py
- demisto_sdk/tests/integration_tests/xsoar_linter_integration_test.py
- demisto_sdk/tests/test_files/invalid_py3_XSOARLinter.py
fixes: https://github.com/demisto/etc/issues/28629
> Adding a checker to validate commonServerPython import

- CHANGELOG.md
- demisto_sdk/commands/generate_docs/generate_integration_doc.py
- demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
- demisto_sdk/tests/test_files/fake_integration/fake_README.md
fixes: https://github.com/demisto/etc/issues/29972
Added optional values to argument description (if exists)
Added default value to argument description (if exists)
> Added default value and predefined values to argument description

- TestSuite/integration.py
- TestSuite/pack.py
- TestSuite/playbook.py
- demisto_sdk/commands/common/tests/base_validator_test.py
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/init/initiator.py
- demisto_sdk/tests/integration_tests/format_integration_test.py
- demisto_sdk/tests/integration_tests/secrets_integration_test.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
> Remove deprecated functions

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/tests/base_validator_test.py
fixes: https://github.com/demisto/etc/issues/30667
Removed all occurrences of certification as it comes to partners, which solved the issue.
> Support level bugfix

- conftest.py
> added playbook to conf testsuite

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/format/update_generic.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/30708
fixes: https://github.com/demisto/etc/issues/30625
Fixing Staged flag, fixing redundant check BC warnings on added files.
> Fixing Staged flag, fixing redundant check BC warnings on added files.

- CHANGELOG.md
> updating CHANGELOG.md

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/find_dependencies/find_dependencies.py
- demisto_sdk/commands/validate/validate_manager.py
related to this PR: https://github.com/demisto/content/pull/10094
fixes: https://github.com/demisto/etc/issues/30839
validation old beta fix and RN check for APIModules
> validation old beta fix and RN check for APIModules

- demisto_sdk/__main__.py
fixes: https://github.com/demisto/etc/issues/30841
making -a flag required for create-content-artifacts
> making -a flag required for create-content-artifacts

- CHANGELOG.md
- demisto_sdk/commands/upload/uploader.py
demisto-sdk upload command now supports mappers
> sdk upload mapper

- CHANGELOG.md
Fixed the whitespaces issue in the changelog file from https://github.com/demisto/demisto-sdk/pull/897
> Changelog whitespaces fix

- CHANGELOG.md
> changelog fixes

- demisto_sdk/commands/common/errors.py
related: https://github.com/demisto/content/pull/9960
as @glicht @anara123 @yaakovi talked in the pre-demo. the tlp color here is a filter since it’s already marked by the feed.
so we need to ignore this error.
> added IN122 to the ignorable errors

- demisto_sdk/__main__.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
improving printed error in case of not running from demisto content root.
> improving printed error

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/tests/integration_test.py
reference: https://github.com/demisto/etc/issues/31038
Added the new category
> added new category to integration validations

- demisto_sdk/__main__.py
> unify input must be a dir

- demisto_sdk/commands/format/format_module.py
fixes: https://github.com/demisto/etc/issues/30815
Added a recommendation to the user to run validate command when it fails while running *format*
> Added recommendation to run validate

- demisto_sdk/commands/common/schemas/integration.yml
https://github.com/demisto/content/pull/10103
add category to schema file of integration.
> added new category to schema file

- CHANGELOG.md
- demisto_sdk/commands/lint/linter.py
fixes: https://github.com/demisto/etc/issues/31207
Retry support for all exceptions when building a docker image.
> docker build: retry support

- CHANGELOG.md
- demisto_sdk/commands/lint/commands_builder.py
- demisto_sdk/commands/lint/tests/command_builder_test.py
fixes: https://github.com/demisto/etc/issues/28040
in the referenced issue
> Bandit now reports also on medium severity issues

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/validate/validate_manager.py
Added a flag --skip-id-set-creation for validate
Added the capability to run validate command without creating id_set validation.
> added a flag --skip-id-set-creation for validate command

- demisto_sdk/commands/run_cmd/README.md
fixes: https://github.com/demisto/etc/issues/23205
> Run readme updates

- .circleci/config.yml
- tox.ini
fixes: https://github.com/demisto/etc/issues/31339
Creating a different env for tox unit tests and venv
> adding no-test env for build

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/update_release_notes/README.md
fixes: https://github.com/demisto/etc/issues/29456
added prev-ver argument to update-release-notes command.
> added prev-ver arg to update release notes

- .circleci/config.yml
moving the SDK build to run on python 3.7 instead of 3.8
> moving build python 3.7

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/create_id_set/create_id_set.py
- demisto_sdk/commands/create_id_set/tests/update_id_set_test.py
fixes: https://github.com/demisto/etc/issues/31175
add the option to create an ID set on a specific pack.
> Create id set - add the option to create an ID set on a specific pack

- .circleci/config.yml
- package-lock.json
adding update to npm as part of the validate section.
> adding npm update to build

- CHANGELOG.md
- demisto_sdk/commands/lint/resources/pylint_plugins/xsoar_level_checker.py
- demisto_sdk/commands/lint/tests/test_pylint_plugin/xsoar_level_checker_test.py
fixes: https://github.com/demisto/etc/issues/31061
Added new xsoar linter validation for "NotImplementedError"
> implemented NotImplementedError in xsoar linter

- demisto_sdk/commands/lint/resources/pylint_plugins/xsoar_level_checker.py
Added try exception in the new notImplementedError validation.
> fixed nightly

- CHANGELOG.md
- demisto_sdk/commands/generate_docs/generate_integration_doc.py
- demisto_sdk/commands/generate_docs/generate_playbook_doc.py
- demisto_sdk/commands/generate_docs/generate_script_doc.py
- demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
- demisto_sdk/tests/test_files/fake_integration/fake_README.md
> removed changes

- CHANGELOG.md
- demisto_sdk/commands/upload/uploader.py
fixes: https://github.com/demisto/etc/issues/32061
Upload failed on beta integrations, turns out that happens when it's not in the supported type list. Who knew?
> Support Uploading Beta Integrations

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/tests/pack_unique_files_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/31867
adding price change validation
> adding price change validation

- CHANGELOG.md
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/resources/pylint_plugins/xsoar_level_checker.py
- demisto_sdk/commands/lint/tests/test_pylint_plugin/xsoar_level_checker_test.py
fixes: https://github.com/demisto/etc/issues/32172
Added a check for if its a script , and if it is then the NotImplementedError wont be checked on it.
for example for CertificatesTroubleshoot which is a script:
> Notimplemented for integrations only

- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/tests/pack_unique_files_test.py
skipping price check on master branch of private repo
> skipping price check on master branch of private repo

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/incident_type.py
- demisto_sdk/commands/common/schemas/incidenttype.yml
- demisto_sdk/commands/common/tests/incident_type_test.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
related: https://github.com/demisto/etc/issues/28221
adding auto extraction validation checks for incident types
> adding auto extraction validation checks for incident types

- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/tests/pack_unique_files_test.py
- demisto_sdk/commands/find_dependencies/find_dependencies.py
- demisto_sdk/commands/validate/validate_manager.py
fixing issue where id_set creation was created even when skipping flag was set
> fixing issue where id_set creation was created even when skipping flag was set

- CHANGELOG.md
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/tests/test_linter/os_runner_test.py
fixes: https://github.com/demisto/etc/issues/32173
Added the unittest files to the flake8 files directly instead of running twice.
Now looks like this:
> Fixed lint ran Twice on lint files and on unit tests files.

- CHANGELOG.md
- demisto_sdk/commands/lint/commands_builder.py
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/tests/command_builder_test.py
- demisto_sdk/commands/lint/tests/test_linter/docker_runner_test.py
fixes: No issue 
disable pylint unsubscriptable-object for py3.9
> disable pylint unsubscriptable-object for py3.9

- demisto_sdk/commands/lint/commands_builder.py
- demisto_sdk/commands/lint/linter.py
> fixed pylint for 3.9

- demisto_sdk/__main__.py
- demisto_sdk/commands/test_content/Docker.py
- demisto_sdk/commands/test_content/IntegrationsLock.py
- demisto_sdk/commands/test_content/ParallelLoggingManager.py
- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/execute_test_content.py
- demisto_sdk/commands/test_content/mock_server.py
- demisto_sdk/commands/test_content/tests/BuildContext_test.py
- demisto_sdk/commands/test_content/tests/ParallelLoggingManager_test.py
- demisto_sdk/commands/test_content/tests/mock_unit_test.py
- demisto_sdk/commands/test_content/timestamp_replacer.py
- demisto_sdk/commands/test_content/tools.py
- requirements.txt
Added a new hidden command `test-content` that will run the test-content step in the build.
The proxy, ParallelLoggingManager, Docker and locking mechanism were copied as well and will be deleted from content in a seperate PR.
https://github.com/demisto/etc/issues/32220#event-4155053781
> Adding new command - test-content

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/id.py
- demisto_sdk/commands/validate/validate_manager.py
- requirements-dev.txt
- requirements.txt
> move print to logical place

- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/upload/uploader.py
- demisto_sdk/tests/integration_tests/upload_integration_test.py
fixes: https://github.com/demisto/etc/issues/32301
Upload now checks gracefully if it can connect to demisto server
> Raise nice error if can't connect to server

- CHANGELOG.md
> update changelog file

- CHANGELOG.md
- demisto_sdk/commands/validate/validate_manager.py
> IDSetValidator - add ignored_errors=pack_error_ignore_list to instance creation

- demisto_sdk/commands/unify/tests/unifier_test.py
- demisto_sdk/commands/unify/unifier.py
related: https://github.com/demisto/etc/issues/32548
Add an extra new line to avoid formatting issues. See: https://github.com/demisto/etc/issues/32548
> Unifier: fix doc link to add extra new line for formatting

- demisto_sdk/commands/test_content/TestContentClasses.py
Fixing slack usage for the sdk command `test-content`
> Fixed slack usage

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/id.py
- demisto_sdk/commands/common/tests/id_test.py
The old validation from the time we checked the integrity of the id_set.json is non relevant anymore and was removed.
https://github.com/demisto/content/pull/10817
> rm old id validation

- demisto_sdk/commands/test_content/TestContentClasses.py
https://github.com/demisto/etc/issues/32220
- In case executing the playbook was not successful - no need to run docker test
- In case an exception is raised while executing a test - make sure it won't kill the thread to avoid deadlock
> Some minor fixes to the test execution

- CHANGELOG.md
> rn cleanup 1.2.6

- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/mock_server.py
- Remove the status line for the midmdump
- Improving test results prints
> Test content fixes

- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/tests/BuildContext_test.py
fixes: https://github.com/demisto/etc/issues/31386
Supporting unmockable playbooks
> Supporting unmockable playbooks

- .circleci/config.yml
Add merge ID sets to validate in sdk build.
> Add merge ID sets to validate in sdk build

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/id.py
- demisto_sdk/commands/common/tests/id_test.py
fixes: https://github.com/demisto/etc/issues/30342
fixes: https://github.com/demisto/etc/issues/31851
* Added a validation that the classifier of an integration exists.
* Added a validation that the mapper of an integration exists.
* Added a validation that the incident types of a classifier exist.
* Added a validation that the incident types of a mapper exist.
> id_set validations phase2

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/update_release_notes/update_rn.py
same as https://github.com/demisto/demisto-sdk/pull/1026
> added the option to pass text when generating RN for ApiModules

- demisto_sdk/commands/common/hook_validations/readme.py
fixes: https://github.com/demisto/etc/issues/32631
`mdx_verify_server` check in readme.py is unstable, adding retries and increasing timeout from 10 to 20.
> Read-me validations sometimes fail - retry and raise timeout

- CHANGELOG.md
- demisto_sdk/commands/common/tools.py
fixes: https://github.com/demisto/etc/issues/32717
as the approved files are rather small:
```
-rw-r--r--  1 bkatzir  PALOALTONETWORK\Domain Users   658B Jan  6 15:52 Tests/Marketplace/approved_tags.json
-rw-r--r--  1 bkatzir  PALOALTONETWORK\Domain Users   776B Jan 11 17:29 Tests/Marketplace/approved_usecases.json
```
I've put the maxsize on 8.
> use lru in get_remote_file

- demisto_sdk/commands/test_content/tests/timestamp_replacer_test.py
- demisto_sdk/commands/test_content/timestamp_replacer.py
- requirements-dev.txt
https://github.com/demisto/etc/issues/32220
Added unittests for timestamp_replacer.py
> Added unittests for timestamp_replacer.py

- demisto_sdk/commands/common/errors.py
> err typo fix

- demisto_sdk/commands/run_cmd/README.md
fixes: https://github.com/demisto/etc/issues/32784
> Runner - added missing args to readme

- demisto_sdk/commands/upload/README.md
fixes: https://github.com/demisto/etc/issues/24453
> Upload readme

- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/execute_test_content.py
- Fix an issue with the PR comment of the build.
- Fix slack notification on failed test.
> Minor fixes

- demisto_sdk/commands/find_dependencies/find_dependencies.py
fixes: https://github.com/demisto/etc/issues/30568
In the referenced issue
> find_dep - rm redundant code

- demisto_sdk/commands/lint/resources/pipfile_python3/Pipfile
- demisto_sdk/commands/lint/resources/pipfile_python3/Pipfile.lock
> Added vcrpy library to SDK

- CHANGELOG.md
- TestSuite/repo.py
- demisto_sdk/commands/common/tests/dependencies_test.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/create_id_set/tests/update_id_set_test.py
- demisto_sdk/commands/find_dependencies/find_dependencies.py
fixes: https://github.com/demisto/etc/issues/32775
> Id set outgoing mappers - added support for the incident fields

- CHANGELOG.md
Move uuid validation description line to changelog section 
> Move uuid validation description line to changelog section

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/hook_validations/id.py
- demisto_sdk/commands/common/tests/id_test.py
- demisto_sdk/commands/common/tests/playbook_test.py
- demisto_sdk/commands/validate/README.md
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
- demisto_sdk/tests/workflow_test.py
relates to: https://github.com/demisto/etc/issues/32746
rmed redundant id_set creation and better the code flow.
validate_files is down from 18 to 15 min now.
> id_set dup logic rmed

- demisto_sdk/commands/common/hook_validations/id.py
- demisto_sdk/commands/validate/validate_manager.py
Adding option to ignore id set errors
> Adding option to ignore id set errors

- CHANGELOG.md
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/constants_test.py
fixes: https://github.com/demisto/etc/issues/33128
We should exclude all changes from doc_files directory when running validation 
> Exclude changes from doc_files directory when running validation

- demisto_sdk/commands/init/tests/contribution_converter_test.py
Skipping flaky test on SDK: 
https://github.com/demisto/etc/issues/33244
> skipping flaky test

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/integration_test.py
fixes: https://github.com/demisto/etc/issues/30343
Integration parameters display name should be capitalized and spaced using whitespace and not underscores.
> Validate integration parameters display name

- demisto_sdk/commands/common/errors.py
added an error for context changes in yml, for PR https://github.com/demisto/demisto-sdk/pull/1077
> added errors

- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/tests/server_context_test.py
- demisto_sdk/commands/test_content/tests/test_context_test.py
fixes: https://github.com/demisto/etc/issues/33251
This PR is about supporting the enforcement of the second playback of the mocking infra
> Enforcing second playback

- demisto_sdk/commands/init/contribution_converter.py
- demisto_sdk/commands/init/tests/contribution_converter_test.py
fixes: https://github.com/demisto/etc/issues/33116
Added `readme_files` as instance variable to use after in the contribution management flow to add to the comment the files that needs to be reviewed.
> Added readme_files paths as instance variable

- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
formatted the rn entry for updated docker image
> Update Release Notes - fmt updated docker img rn

- demisto_sdk/commands/common/schemas/integration.yml
added `resetContext` to integration schema
> Integration Schema - add resetContext

- demisto_sdk/commands/test_content/execute_test_content.py
fixes: https://github.com/demisto/etc/issues/33090
Before posting a comment into a PR, check if this comment was already posted. If it was, don't post it again to avoid spamming PRs.
> Prevent Content-Bot from repeating same comment in PR

- CHANGELOG.md
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/create_id_set/tests/update_id_set_test.py
> Merge ID sets support Packs

- .circleci/config.yml
creating the id_set through the SDK build
> creating the id_set through the SDK build

- demisto_sdk/commands/secrets/secrets.py
fixes: https://github.com/demisto/etc/issues/33411
> ignore dev-req

- CHANGELOG.md
> release sdk - changelog

- CHANGELOG.md
- demisto_sdk/__main__.py
fixing create id set flag in validate
> fixing create id set flag

- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/validate/validate_manager.py
adding prev-ver support on pack_metadata file check
> adding prev-ver support on pack_metadata file check

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/tests/pack_unique_files_test.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
adding a warning in validate in case id set file was not found or was not created.
> no id_set file warning

- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/tests/pack_unique_files_test.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
improving warning message and method name for pack unique file dependencies check
> improving warning message and method name for pack unique file dependencies check

- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/release_notes.py
- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/commands/common/legacy_git_tools.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/validate/validate_manager.py
Removing pack metadata identification - this should fix content infra without any required changes on content side.
> Removing pack metadata identification

- demisto_sdk/commands/lint/lint_manager.py
> fixing warning not printing

- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/readme.py
- demisto_sdk/commands/validate/validate_manager.py
If MDX server fails we should fail the validation but not crash the command.
Also improved the error message with a suggestion about what should be done to correct this.
> introducing new error for mdx server installation failure

- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
fixing issue if file not found when running json output
> fixing issue if file not found when running json output

- demisto_sdk/commands/common/errors.py
fixes: https://github.com/demisto/etc/issues/34005
> rm docker from ALLOWED_IGNORE_ERRORS

- README.md
Add note about DEMISTO_SDK_SKIP_VERSION_CHECK
> readme update: add not about DEMISTO_SDK_SKIP_VERSION_CHECK

- demisto_sdk/commands/run_cmd/README.md
fixes: https://github.com/demisto/demisto-sdk/issues/811
removed the `-k` option from the docs.
> Run command: Update README.md

- demisto_sdk/commands/test_content/Docker.py
Add some more logging to the docker mem check.
> docker mem check: add debug logging

- CHANGELOG.md
relates: https://github.com/demisto/demisto-sdk/pull/1138
Added a description in the changelog file about the new validation that i added, which is to validate that some specific fields in the yml file are not removed or changed from true  to false.
> added a description in the CHANGELOG file about the validation task

- CHANGELOG.md
- demisto_sdk/commands/common/git_util.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
changes here:
1) Getting prev_ver in release branch from os.env var.
2) when running on the release branch only check committed files.
3) adding support for git handling with sha1.
> Fixing git handling for release branch build

- demisto_sdk/commands/upload/uploader.py
fixes: https://github.com/demisto/demisto-sdk/issues/1113
solving an issue with uploader which caused an error
> solving an issue with uploader which caused an error

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/split_yml/extractor.py
fixes: https://github.com/demisto/demisto-sdk/issues/810
exposing no-pipenv option in split yml and adding additional logs
> exposing no-pipenv option in split yml and adding additional logs

- demisto_sdk/commands/common/content/objects/abstract_objects/general_object.py
- demisto_sdk/commands/common/content/objects/pack_objects/change_log/change_log.py
- demisto_sdk/commands/common/content/objects/pack_objects/classifier/classifier.py
- demisto_sdk/commands/common/content/objects/pack_objects/connection/connection.py
- demisto_sdk/commands/common/content/objects/pack_objects/dashboard/dashboard.py
- demisto_sdk/commands/common/content/objects/pack_objects/incident_field/incident_field.py
- demisto_sdk/commands/common/content/objects/pack_objects/incident_type/incident_type.py
- demisto_sdk/commands/common/content/objects/pack_objects/indicator_field/indicator_field.py
- demisto_sdk/commands/common/content/objects/pack_objects/indicator_type/indicator_type.py
- demisto_sdk/commands/common/content/objects/pack_objects/integration/integration.py
- demisto_sdk/commands/common/content/objects/pack_objects/layout/layout.py
- demisto_sdk/commands/common/content/objects/pack_objects/playbook/playbook.py
- demisto_sdk/commands/common/content/objects/pack_objects/readme/readme.py
- demisto_sdk/commands/common/content/objects/pack_objects/release_note/release_note.py
- demisto_sdk/commands/common/content/objects/pack_objects/report/report.py
- demisto_sdk/commands/common/content/objects/pack_objects/script/script.py
- demisto_sdk/commands/common/content/objects/pack_objects/widget/widget.py
Adding type method in order to replace find_type in the future.
> adding type method in all content objects

- demisto_sdk/commands/common/schemas/integration_CHANGELOG.md
- demisto_sdk/commands/common/schemas/script_CHANGELOG.md
> removed redundant files

- demisto_sdk/commands/create_artifacts/content_artifacts_creator.py
- requirements.txt
fixes an issue where flake8 was failing on variable scope (logger).
> Logger bug

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
fixes: https://github.com/demisto/etc/issues/34397#event-4455028219
Integration with duplicate params was not detected as invalid integration.
Also, added a fix for duplicate args that have not been detected (noticed it during the duplicate params fix)
> Fix duplicate params not detected

- demisto_sdk/commands/common/constants.py
fixes: https://app.circleci.com/pipelines/github/demisto/content/74621/workflows/021ebdc4-0f3b-4675-bc31-2ffbcfd2fb15/jobs/307772
fixed mapping of release note headers
> fixed mapping of release note headers

- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/constants.py
https://github.com/demisto/etc/issues/33859
Fixing the ssh tunnel command that should be executed locally to access the server instances.
> Fixing ssh tunnel command comment

- CHANGELOG.md
- demisto_sdk/commands/lint/linter.py
> Fix an error where lint failed on bandint run

- demisto_sdk/commands/test_content/execute_test_content.py
Updated the message displayed in a PR in case skipped integrations/tests were found related to this PR, to be more informative.
> Update Skipped content message in PR

- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/init/tests/initiator_test.py
fixes: https://github.com/demisto/etc/issues/34976
adding supported from version for init.
> adding Supported from version for init

- CHANGELOG.md
- demisto_sdk/commands/lint/resources/pylint_plugins/xsoar_level_checker.py
- demisto_sdk/commands/lint/tests/test_pylint_plugin/xsoar_level_checker_test.py
https://github.com/demisto/etc/issues/35080
Fixed a problem where demisto-sdk lint did search for raise  NotImplementedError in else clauses only
> Unimplemented-Warning-Error

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/readme.py
- demisto_sdk/commands/common/tests/readme_test.py
- demisto_sdk/tests/test_files/README-short-invalid.md
https://github.com/demisto/etc/issues/32637
> Validate Readme has at least 30 chars if not empty

- demisto_sdk/commands/common/schemas/script.yml
related to: https://github.com/demisto/content/pull/11659
added a workaround for the `fromversion` field
> updated script schema

- requirements.txt
upgrade the `ujson` package:
Version 3 contains a bug where the function `ujson.dump` ignores the `indent` argument and always uses one space.
it is fixed in later versions.
this affects the format command (for JSON files)
before (using 3.0.0):
after (using 4.0.2):
> Update requirements.txt - ujson v4.0.2

- demisto_sdk/commands/common/logger.py
- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/linter.py
increase number of attempts to find py ver to 3 and log the exception
> Lint - increase attempts to 3 and log docker error in find py ver

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
- demisto_sdk/tests/test_files/integration-feedvalid.yml
https://github.com/demisto/etc/issues/35471
adding hidden to command schema validation
> add hidden to command schema validation

- CHANGELOG.md
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/format/tests/test_formatting_yml_test.py
- demisto_sdk/commands/format/update_playbook.py
fixes: https://github.com/demisto/etc/issues/35205
* Fixed an issue where running **format** on a playbook whose `name` does not equal its `id` would cause other playbooks who use that playbook as a sub-playbook to fail.
> fixing sub-playbook id change issue

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/script.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/common/tests/script_test.py
fixes: https://github.com/demisto/etc/issues/34857
Added a validation that commands' names and arguments in core packs, or scripts' arguments do not contain the word incident.
> Incident word in core packs or scripts

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/layout.py
- demisto_sdk/commands/common/tests/layout_test.py
- demisto_sdk/commands/format/tests/test_formatting_json_test.py
- demisto_sdk/commands/format/update_layout.py
- demisto_sdk/tests/test_files/validate_integration_test_valid_types.py
fixes: https://github.com/demisto/etc/issues/35081
Added a validation that layoutscontainer's id and name are matching.
> validating that layouts_container's name equals id

- CHANGELOG.md
Modifying changelog after release
> demisto-sdk-release-1.3.4 changelog

- demisto_sdk/commands/common/schemas/dashboard.yml
> updating dashboard schema

- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/common/schemas/script.yml
https://github.com/demisto/etc/issues/32307
https://github.com/demisto/etc/issues/35436
Added schema updates required for polling.
> Add Polling to Script and Integration Schemas

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/hook_validations/image.py
- demisto_sdk/commands/common/tests/base_validator_test.py
- demisto_sdk/commands/common/tests/image_test.py
- demisto_sdk/commands/common/tools.py
fixes: https://github.com/demisto/etc/issues/35960
Fix image-related validation results that are output to json file.
> Fix image-related validation outputs

- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/tests/base_validator_test.py
related: https://github.com/demisto/etc/issues/35960#issuecomment-823105907
handling image entity type identification for unified yml validation json output.
> handling image identification for unified ymls.

- requirements.txt
limiting astroid version temporarily
> limiting astroid version temporarily

- README.md
Adding documentation about how to use `.demisto-sdk-conf`.
> Adding documentation about how to use `.demisto-sdk-conf`

- demisto_sdk/commands/download/README.md
https://github.com/demisto/demisto-sdk/issues/799
Fixed description.
> Download Update README.md

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/tests/pack_unique_files_test.py
fixes: https://github.com/demisto/etc/issues/35584
Added validation for core-packs mandatory dependencies to not be dependent on un-core packs
> Added validation for core-packs mandatory dependencies

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
fixes: https://github.com/demisto/etc/issues/36077
Fixed update release notes when changed integration logo.
> Fixed update release notes when changed integration logo

- demisto_sdk/commands/common/schemas/playbook.yml
fixes: https://github.com/demisto/etc/issues/36390
adding deprecated to playbook schema
> adding deprecated to playbook schema

- CHANGELOG.md
Changelog update about private repo change
> Changelog update about private repo change

- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/tests/testplaybook_test.py
- demisto_sdk/commands/test_content/tools.py
fixes: https://github.com/demisto/etc/issues/29349
- added reset containers before applying the server conf
- cleared server conf after test
- added reset containers if server conf were applied
> Test Content - clean server config and reset containers if needed

- demisto_sdk/commands/common/constants.py
- demisto_sdk/tests/constants_test.py
adding default and fixing repo detection
> adding default and fixing repo detection

- demisto_sdk/commands/init/templates/BaseIntegration/BaseIntegration.py
- demisto_sdk/commands/init/templates/BaseIntegration/BaseIntegration.yml
- demisto_sdk/commands/init/templates/BaseIntegration/BaseIntegration_test.py
- demisto_sdk/commands/init/templates/BaseIntegration/test_data/baseintegration-dummy.json
Update template to a better convention.
Minimum calls to `demiso` class
updated docker image 
readabillity improvements
> Update baseintegration template

- CHANGELOG.md
- demisto_sdk/__main__.py
> disable upgrade check with envvar.

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/find_dependencies/find_dependencies.py
- demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py
fixes: https://github.com/demisto/etc/issues/36641
fixed core pack dependencies and added the use_pack_metadata flag to find dependencies command.
> Fixed core pack dependencies validation and added the use_pack_metadata flag

- demisto_sdk/commands/common/tools.py
Fixed a problem when the dsdk is running outside of git repo and failed.
> Fix running outside GitHub

- .circleci/config.yml
- demisto_sdk/commands/validate/validate_manager.py
Aligning SDK build with recent changes in content build
> Aligning SDK build with recent changes in content build

- demisto_sdk/commands/test_content/IntegrationsLock.py
> Integrations Lock - set CI project id

- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/tests/constants_test.py
> Fix another branch finding issue

- demisto_sdk/commands/test_content/IntegrationsLock.py
Reverts demisto/demisto-sdk#1270
> Revert "Integrations Lock - set CI project id"

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/script.py
- demisto_sdk/commands/common/tests/script_test.py
> Outputs key with none type

- demisto_sdk/commands/common/hook_validations/readme.py
- demisto_sdk/commands/common/tests/readme_test.py
https://github.com/demisto/etc/issues/33031
> fixed and added the option to check for default sentences

- CHANGELOG.md
Running build to see it passes all steps
> SDK release 1-3-6

- CHANGELOG.md
Fixed RN entry for image and description names validation
> fixed RN entry

- demisto_sdk/__main__.py
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/tests/dependencies_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/find_dependencies/find_dependencies.py
- demisto_sdk/tests/integration_tests/find_dependencies_integration_test.py
find-dependencies will merge the dependencies from local and content repo.
fixes: https://github.com/demisto/etc/issues/33848
> private repo to content dependencies check

- demisto_sdk/__main__.py
fixes: https://github.com/demisto/etc/issues/29834. 
not full ,partialy
Remove all -h flags
remove command names from the `@click.command` decorator
move help to docstring
> I came in like a wrecking ball

- demisto_sdk/commands/common/errors.py
> fixing misswording in errors

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/integration_diff/integration_diff_detector.py
- demisto_sdk/commands/integration_diff/tests/integration_diff_test.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/commands/validate/validate_manager.py
fixes: https://github.com/demisto/etc/issues/35139
Added a new demisto-sdk command, integration-diff.
> New command integration-diff

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/content_entity_validator.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/script.py
- demisto_sdk/commands/common/tests/integration_test.py
- demisto_sdk/commands/common/tests/script_test.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
- demisto_sdk/tests/workflow_test.py
fixes: https://github.com/demisto/etc/issues/29240
Added validation for separators in integration and script folder and files names.
> added validation for separators in names

- demisto_sdk/commands/common/schemas/reputation.yml
- demisto_sdk/tests/test_files/validate_integration_test_valid_types.py
- [] Ready
fixes: https://github.com/demisto/etc/issues/33806
Add "legacyName" field to reputation schema.
> add legacyName to reputation schema

- CHANGELOG.md
> 1.3.7 release

- demisto_sdk/commands/integration_diff/README.md
Added README docs to integration-diff command.
> Added docs to integration-diff

- CHANGELOG.md
- demisto_sdk/commands/secrets/secrets.py
- demisto_sdk/commands/secrets/tests/secrets_test.py
fixes: https://github.com/demisto/etc/issues/34802
Remove the if (the branch) is_forked condition, to allow detection secrets for forked branches
> Allow secrets detection for forked branches

- demisto_sdk/commands/common/docker_util.py
- demisto_sdk/commands/common/tests/docker_util_test.py
- demisto_sdk/tests/test_files/just_a_txt_file.txt
> added docker_util

- demisto_sdk/commands/common/schemas/reputation.yml
- demisto_sdk/tests/test_files/validate_integration_test_valid_types.py
fixes: https://github.com/demisto/demisto-sdk/pull/1284
Add "legacyNames" field to reputation schema.
> Add legacy names field to reputation

- CHANGELOG.md
> 1.3.8 sdk release

- demisto_sdk/commands/test_content/tests/timestamp_replacer_test.py
- demisto_sdk/commands/test_content/timestamp_replacer.py
fixes: https://github.com/demisto/etc/issues/31779
added a replacement to the random boundary.
> added repleacment for boundary

- CHANGELOG.md
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/format/update_classifier.py
- demisto_sdk/commands/format/update_connection.py
- demisto_sdk/commands/format/update_dashboard.py
- demisto_sdk/commands/format/update_generic_json.py
- demisto_sdk/commands/format/update_incidentfields.py
- demisto_sdk/commands/format/update_incidenttype.py
- demisto_sdk/commands/format/update_indicatorfields.py
- demisto_sdk/commands/format/update_indicatortype.py
- demisto_sdk/commands/format/update_layout.py
- demisto_sdk/commands/format/update_mapper.py
- demisto_sdk/commands/format/update_pythonfile.py
- demisto_sdk/commands/format/update_report.py
- demisto_sdk/commands/format/update_widget.py
fixes: https://github.com/demisto/etc/issues/37254
Made sure that  format's **Assume yes** flag does work for all entities.
> make sure that assume yes flag works for all entities

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/content_entity_validator.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/script.py
fixes:https://github.com/demisto/etc/issues/37193
Fixed output in separators validation to include the invalid files and to suggest the repair.
> Fixed output in separators validation

- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
Adding print in case of dependency only on core packs.
> Add core pack deps print

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/common/tools.py
> remove DISABLE_SDK_VERSION_CHECK env var

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/playbook.yml
fixes: https://github.com/demisto/etc/issues/37603
Removed it in the scheme
> Made iscontext not required on left condition

- CHANGELOG.md
> release 1.3.9

- CHANGELOG.md
- demisto_sdk/commands/generate_docs/generate_integration_doc.py
- demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
https://github.com/demisto/etc/issues/37184
Added a handle for password parameter in generate-docs command.
> Added a handle for password parameter in generate-docs

- demisto_sdk/commands/common/tests/description_test.py
- demisto_sdk/commands/common/tests/structure_test.py
- demisto_sdk/commands/validate/validate_manager.py
> fix tests and release notes error

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/description.py
- demisto_sdk/commands/common/hook_validations/readme.py
- demisto_sdk/commands/common/tests/description_test.py
- demisto_sdk/commands/common/tests/readme_test.py
- demisto_sdk/tests/test_files/CortexXDR/README.md
- demisto_sdk/tests/test_files/Packs/CortexXDR/README.md
- demisto_sdk/tests/test_files/README-invalid.md
- demisto_sdk/tests/test_files/README-valid.md
- demisto_sdk/tests/test_files/VulnDB/VulnDB_description.md
- demisto_sdk/tests/test_files/content_repo_example/Integrations/Securonix/README.md
fixes: https://github.com/demisto/etc/issues/25118
Added a validation for the word demisto in README and description.
> Validate demisto in docs and description

- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/docker.py
- demisto_sdk/commands/common/hook_validations/incident_field.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/hook_validations/script.py
- demisto_sdk/commands/validate/validate_manager.py
related: https://github.com/demisto/server/pull/18734
threat naming standard of the incident fields as an error.
@sagylell @aviadl - please look at the error message.
> updated naming error behavior of incident fields

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://github.com/demisto/etc/issues/37437
Fixed the display name function in update rn for the old layouts.
> Update rn layout name

- demisto_sdk/commands/validate/validate_manager.py
- requirements.txt
Adding color to percent prints
> adding color to percent print

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/update_rn.py
fixes: https://github.com/demisto/etc/issues/36941
Staging to Git release notes that is being generated by update-release-notes command.
> Stage-Update-Release-Notes-To-Git

- requirements.txt
> ruamel version change

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/incident_field.py
set IF100 (bad words in incident fields) to core packs only.
> set IF100 to core packs only

- demisto_sdk/__main__.py
- demisto_sdk/commands/lint/README.md
- demisto_sdk/commands/lint/commands_builder.py
- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/lint_manager.py
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/resources/pipfile_python2/Pipfile
- demisto_sdk/commands/lint/resources/pipfile_python2/Pipfile.lock
- demisto_sdk/commands/lint/resources/pipfile_python3/Pipfile
- demisto_sdk/commands/lint/resources/pipfile_python3/Pipfile.lock
- demisto_sdk/commands/lint/tests/command_builder_test.py
- demisto_sdk/commands/lint/tests/helper_test.py
- demisto_sdk/commands/lint/tests/test_linter/docker_runner_test.py
- requirements.txt
related to: https://github.com/demisto/etc/issues/22899
Adding coverage report to demisto-sdk lint command.
[content coverage](https://375905-60525392-gh.circle-artifacts.com/0/artifacts/coverage_report/html/index.html)
FYI @glicht @anara123
> adding cov report to lint command

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/update_rn.py
i removed a quote from the help menu
> Remove extra quotes from help menu

- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/resources/pipfile_python2/Pipfile.lock
> fixed Pipfile.lock

- demisto_sdk/commands/lint/helpers.py
> small fix for coverage

- requirements.txt
fixes: https://github.com/demisto/demisto-sdk/issues/1377
loosening colorama dependency
> loosening colorama deps

- demisto_sdk/commands/lint/helpers.py
> added log info for empty cov report

- CHANGELOG.md
> sdk-release-1.4.1

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/integration.py
- demisto_sdk/commands/common/hook_validations/script.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
fixes: https://github.com/demisto/etc/issues/38487
Validation of correct display name for every versioned script or integration to be supported by any v<number> and not only v2
> Apply is_valid_file validation from v2 validation to every version number

- CHANGELOG.md
- demisto_sdk/commands/lint/commands_builder.py
- demisto_sdk/commands/lint/lint_manager.py
- demisto_sdk/commands/lint/tests/command_builder_test.py
fixes: https://github.com/demisto/etc/issues/25209
Add skipped indication to pylint
> add skipped indication to pylint

- CHANGELOG.md
- demisto_sdk/commands/generate_docs/common.py
fixes: https://github.com/demisto/etc/issues/38484
> Generate Docs To Stage Files To Git Auto

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/lint/lint_manager.py
- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/tests/test_linter/conftest.py
- demisto_sdk/commands/lint/tests/test_linter/gather_facts_test.py
- demisto_sdk/tests/integration_tests/xsoar_linter_integration_test.py
adding timeout flag for docker client
> adding timeout flag for docker client

- demisto_sdk/commands/lint/lint_manager.py
change the location of the coverage report to be before the test summary.
> coverage place change

- demisto_sdk/__main__.py
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/error_code_info/error_code_info.py
- demisto_sdk/tests/integration_tests/error_code_info_test.py
ever encountered an ignored error in the pack-ignore file and didn't know what it means?
use the `demisto-sdk error-code` command to quickly find relevant information regarding this error.
Note: this command is hidden.
> added the error-code info command

- demisto_sdk/commands/generate_docs/generate_script_doc.py
fixing demsito in gen docs for scripts
> fixing demsito in gen docs for scripts

- demisto_sdk/commands/lint/resources/pipfile_python3/Pipfile
- demisto_sdk/commands/lint/resources/pipfile_python3/Pipfile.lock
- added [hypothesis](https://hypothesis.readthedocs.io/en/latest/index.html) requirement
- see https://github.com/demisto/content/pull/13397 for example
- bumped py version to 3.9
> Lint Pipfile - add hypothesis and bump py version to 3.9 

- demisto_sdk/commands/common/errors.py
removed a line which is no loner relevant since the error was deleted.
> deleted a line which is no longer relevant

- CHANGELOG.md
- demisto_sdk/commands/init/initiator.py
- demisto_sdk/commands/init/tests/initiator_test.py
- demisto_sdk/tests/integration_tests/init_integration_test.py
- demisto_sdk/tests/workflow_test.py
fixes: https://github.com/demisto/etc/issues/36311
> added fromversion to the init command

- demisto_sdk/commands/validate/validate_manager.py
> print error for missing pack ignore

- CHANGELOG.md
> fixing changelog

- CHANGELOG.md
> sdk-release-1.4.2

- docs/release_guide.md
Update the SDK release process documentation with the new step of check the new SDK in content-private build
> update the SDK release proccess doc with the private build step

- demisto_sdk/commands/lint/resources/pipfile_python2/Pipfile.lock
[build](https://app.circleci.com/pipelines/github/demisto/content/97666/workflows/ae131964-9dfc-444c-a780-3cee22564eb9/jobs/391648)
> update Pipfile.lock  for python2 

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/init/initiator.py
- demisto_sdk/tests/integration_tests/init_integration_test.py
fixes: https://github.com/demisto/etc/issues/38657
fixing init without -n
> fixing init without -n

- .pre-commit-config.yaml
pre-commit are using regex, not globs. fixing it.
> Change globs to regex

- demisto_sdk/__main__.py
> stopped exit chaining + click 8.1 preparations

- demisto_sdk/commands/common/tests/update_id_set_test.py
- demisto_sdk/commands/create_id_set/create_id_set.py
- demisto_sdk/commands/create_id_set/tests/create_id_set_test.py
moved the IDSetCreator tests to the right file.
> Fix tests location part2

- demisto_sdk/commands/init/templates/BaseIntegration/BaseIntegration.py
- demisto_sdk/commands/init/templates/BaseScript/BaseScript.py
- demisto_sdk/commands/init/templates/FeedHelloWorld/FeedHelloWorld.py
- demisto_sdk/commands/init/templates/HelloIAMWorld/HelloIAMWorld.py
- demisto_sdk/commands/init/templates/HelloWorld/HelloWorld.py
- demisto_sdk/commands/init/templates/HelloWorldScript/HelloWorldScript.py
added pragma comment to ignore coverage check for script/integration
> added pragma comment to ignore coverage check for script/integration entry point

- demisto_sdk/commands/create_id_set/create_id_set.py
- demisto_sdk/commands/create_id_set/tests/create_id_set_test.py
fixed a dependency issue like the following (`VirusTotal` depends on `Polyswarm`):
> IDSetCreator: fixed an issue with generic commands

- demisto_sdk/commands/common/errors.py
> IncidentField Name Validation: Fixed typo

- CHANGELOG.md
> changelog location quickfix

- demisto_sdk/commands/common/tests/pack_unique_files_test.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
fixes: https://github.com/demisto/etc/issues/39040
> Fix usecases/tags approved list issue for non-content repos

- demisto_sdk/commands/common/hook_validations/script.py
fixed wrong argument to error_handle function
> fixed worng argument for handle_error

- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/resources/pylint_plugins/base_checker.py
Fixing pylint import error in xsoar linter
> fixing xsoar linter import

- demisto_sdk/commands/format/update_mapper.py
> fixing format

- demisto_sdk/commands/test_content/TestContentClasses.py
added a new line for an easier copy of the ssh command from the logs
> added a new line for easier copy of the ssh command from the logs

- demisto_sdk/commands/common/tools.py
> fixing find type

- demisto_sdk/commands/lint/lint_manager.py
making lint go alphabetically on packages
> making lint go alphabetically on packages

- demisto_sdk/commands/common/tests/update_id_set_test.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py
- demisto_sdk/tests/test_files/DummyPack/Integrations/integration-DummyIntegration.yml
related: https://github.com/demisto/etc/issues/39266
add docker images to the ID set for easier collection
> added docker image indications to id set

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/openapi_codegen/openapi_codegen.py
- demisto_sdk/commands/openapi_codegen/tests/openapi_codegen_test.py
fixes: https://github.com/demisto/etc/issues/39243
Fixed an issue where open API command was overwriting existing file by adding a config suffix to saved config file name.
> Open API bug fix

- demisto_sdk/commands/lint/linter.py
fixes: https://github.com/demisto/etc/issues/39437
> lint: use uid 4000 if running as root

- CHANGELOG.md
- demisto_sdk/commands/openapi_codegen/openapi_codegen.py
- demisto_sdk/commands/openapi_codegen/tests/openapi_codegen_test.py
fixes: https://github.com/demisto/etc/issues/39351
Added a fix to check if the props is dict object. Because some swaggers have example entries containing string indicating the type of the object and not the structure of the object itself
> Demisto SDK OpenAPI Command Str Has No Attribute Items Fix

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/base_validator.py
- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
fixes: https://github.com/demisto/etc/issues/39271
Fixed an issue when validate suggested running format on the yml file when mandatory fields were missing. 
Foramt does not handle adding those fields so the print was wrong. 
My solution is an indicative message to the user which field to add and the path to add it to.
> fix validate wrong error 

- CHANGELOG.md
> release 1.4.5

- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/tests/errors_test.py
- demisto_sdk/commands/validate/tests/validators_test.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
> updated an error message

- CHANGELOG.md
- demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
- demisto_sdk/commands/update_release_notes/update_rn.py
Fixed an issue where --text flag is ignored when using -f flag
> update_rn fix Force and text  flags

- CHANGELOG.md
- demisto_sdk/__main__.py
- demisto_sdk/commands/generate_test_playbook/test_playbook_generator.py
- demisto_sdk/commands/generate_test_playbook/tests/test_playbook_generator_test.py
- demisto_sdk/tests/test_files/fake_integration_expected_test_playbook.yml
- demisto_sdk/tests/test_files/fake_integration_expected_test_playbook__all_brands.yml
fixes: https://github.com/demisto/etc/issues/39483
Enhances the **generate-test-playbook** command to use only integration tested on commands, rather than (possibly) other integrations implementing them.
> Branded test playbook

- demisto_sdk/commands/lint/linter.py
- demisto_sdk/commands/lint/tests/test_linter/gather_facts_test.py
https://github.com/demisto/etc/issues/38470
removing flies that are in gitignore
> Lint ignore files

- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/linter.py
- Retry pwsh on timeout.
- Excluding pwsh from `get_python_version_from_image` method.
- giving the option for timeout increase in the `get_python_version_from_image` method.
> pwsh related improvements in lint

- CHANGELOG.md
> sdk release 1.4.6

- demisto_sdk/commands/lint/helpers.py
- demisto_sdk/commands/lint/linter.py
based on a change made here https://github.com/demisto/demisto-sdk/pull/1495 - expanding to pwsh tests as well.
> expanding uid 4000 fix to pwsh

- CHANGELOG.md
- demisto_sdk/commands/common/errors.py
fixes: https://github.com/demisto/etc/issues/39116
fixing wording in 2 errors
> fixing wording in 2 errors

- demisto_sdk/commands/test_content/TestContentClasses.py
ignore slack errors in the test-content command (we are using it as a best-effort - it shouldn't fail the build)
> ignored slack errors in test-content command

- CHANGELOG.md
- TestSuite/pack.py
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/errors.py
- demisto_sdk/commands/common/hook_validations/author_image.py
- demisto_sdk/commands/common/hook_validations/pack_unique_files.py
- demisto_sdk/commands/common/hook_validations/structure.py
- demisto_sdk/commands/common/tests/author_image_validator_test.py
- demisto_sdk/commands/common/tests/pack_unique_files_test.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/format/format_module.py
- demisto_sdk/commands/validate/validate_manager.py
- demisto_sdk/tests/integration_tests/validate_integration_test.py
fixes: https://github.com/demisto/etc/issues/40061
1 - validate will now recognize newly added old-format files when running with -g.
2 - Added author image validation to -g flow
> fixing validate issues

- CHANGELOG.md
- demisto_sdk/__main__.py
fixes: https://github.com/demisto/etc/issues/40165
> renamed description_dictionary argument

- demisto_sdk/commands/common/tools.py
fixes: https://github.com/demisto/etc/issues/40271
> get remote file replace token in log error upon requests failure

- demisto_sdk/commands/common/errors.py
in the new format, it is easier to copy the suggested command by double-clicking it.
> Improve docker image update suggestion

- demisto_sdk/commands/json_to_outputs/README.md
mistyped argument in `json-to-outputs` readme
> corrected argument name

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/description.py
- demisto_sdk/commands/common/tests/description_test.py
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/tests/test_files/gitlab_ci_test_file.yml
handling gitlab ci yml file loads - to avoid situations like this: https://app.circleci.com/pipelines/github/demisto/content/107435/workflows/1b85df12-928c-4c53-8dea-32d596d7cffa/jobs/411459
> handling gitlab ci yml file loads

- .github/pull_request_template.md
Add our `VS Code Extension` as required checkboxes to the `demisto-sdk` repo's PR template so that when new functionality/features/commands is/are implemented in the `demisto-sdk`, that we make sure to also add it to the extension.
> Add extension requirements to pr template

- CHANGELOG.md
- README.md
- demisto_sdk/commands/generate_docs/generate_integration_doc.py
- demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
fixes: https://github.com/demisto/etc/issues/39711
When there is an empty list outputs it should not create a table with empty contents, but print that there are no outputs.
Before:
After:
> Fix the outputs empty list

- demisto_sdk/commands/common/tests/conf_test.py
- demisto_sdk/commands/common/tests/pack_metadata_validator_test.py
> Remove some TODOs from Demisto SDK

- demisto_sdk/commands/common/schemas/incidentfield.yml
- demisto_sdk/commands/common/tests/structure_test.py
Will be available fromversion 6.5 of the server. Will do nothing below it
> added openEnded to incidentfield schema

- demisto_sdk/commands/common/update_id_set.py
> remove debug prints from update_id_set.py

- CHANGELOG.md
> v1.4.8 release

- demisto_sdk/commands/common/schemas/layoutscontainer.yml
- demisto_sdk/commands/common/update_id_set.py
Need to add definition id info in layout containters
> adding GOM support for layoutscontainer

- README.md
added a reference to demisto-py readme (for more configurations)
fixed readme formatting
> demisto-py notes (and markdown fixes)

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
Use case: https://github.com/demisto/content/pull/14494
Add 'hidden' option to the integration schema so the validation won't fail.
> Added the hidden field to the integration argument schema

- CHANGELOG.md
> removed changelog duplicate head

- .circleci/config.yml
- demisto_sdk/commands/common/update_id_set.py
add generic definition to id set types
> add definition to id set type

- CHANGELOG.md
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/tests/test_files/content_repo_example/Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
Removed hidden field from integration argument schema, the UI does not support it.
> removed hidden field from integration argument schema

- .circleci/config.yml
Remove update conf JSON as it was removed from content
> remove update conf json

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/id.py
- demisto_sdk/commands/common/tests/id_test.py
- demisto_sdk/commands/common/tools.py
fixes: https://github.com/demisto/etc/issues/39936
Not failing playbook in case the version mismatch but skip unavailable is set
> Not failing playbook in case the version mismatch but skip unavailable is set

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/conf_json.py
fixes: https://github.com/demisto/etc/issues/40160
skipping tests validation for api modules
> skipping tests validation for api modules

- demisto_sdk/commands/split/ymlsplitter.py
fixes: https://github.com/demisto/etc/issues/38710
improving error handling and messaging in split command
> improving error handling and messaging in split command

- demisto_sdk/commands/common/errors.py
fixes: https://github.com/demisto/etc/issues/40602
improving error message for CJ105
> improving error message for CJ105

- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/common/schemas/script.yml
> Add autoUpdateDockerImage To Schema

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/description.py
- demisto_sdk/commands/common/tests/description_test.py
fixes: https://github.com/demisto/etc/issues/40923
Search for description file was done incorrectly.
> Description Validation Wrong Warning Bug Fix

- CHANGELOG.md
- demisto_sdk/commands/upload/uploader.py
https://github.com/demisto/etc/issues/40585
Allow packs that are not in content structure to upload without error
> Upload not content pack

- demisto_sdk/commands/common/schemas/genericdefinition.yml
> Generic Definition Schema - add pluralName

- CHANGELOG.md
- demisto_sdk/commands/unify/yml_unifier.py
fixes: https://github.com/demisto/etc/issues/39919
Improved error message
> SDK Upload To Point To Error In Pack Metadata If Such Happened

- demisto_sdk/commands/common/update_id_set.py
Added a check needed to identify layouts which are not considered duplicates
> Added layout typeId duplicate check

- CHANGELOG.md
> removed unnesessary changelog

- CHANGELOG.md
- demisto_sdk/commands/format/tests/test_formatting_json_test.py
- demisto_sdk/commands/postman_codegen/postman_codegen.py
- demisto_sdk/commands/postman_codegen/tests/postman_codegen_test.py
fixes: https://github.com/demisto/etc/issues/38631
Fix double dot when given body of postman was a list
> Postman Generator Double Dot Bug

- CHANGELOG.md
- demisto_sdk/commands/common/constants.py
- demisto_sdk/commands/common/hook_validations/release_notes.py
- demisto_sdk/commands/common/tests/release_notes_test.py
- demisto_sdk/commands/validate/tests/validators_test.py
fixes: demisto/etc#41614
Author image was not listed as file type that should not appear in the RN. Fixed it by adding it to skipped files from RN
> Author Image RN Complete Fix

- CHANGELOG.md
> Fixed changelog - remove 1.5.2 header

- TestSuite/pack.py
- demisto_sdk/commands/common/schemas/genericfield.yml
- demisto_sdk/commands/common/tests/generic_field_test.py
- demisto_sdk/tests/test_files/validate_integration_test_valid_types.py
> added opendended to generic object

- CHANGELOG.md
- demisto_sdk/__main__.py
> added name attribute to the versionParamType

- demisto_sdk/__main__.py
- demisto_sdk/commands/coverage_analyze/README.md
- demisto_sdk/commands/coverage_analyze/coverage_report.py
- demisto_sdk/commands/coverage_analyze/tests/helpers_test.py
related: https://github.com/demisto/content/pull/15684
change coverage-min url
> change coverage-min url

- CHANGELOG.md
> added changelog .env

- demisto_sdk/commands/common/tests/dependencies_test.py
- demisto_sdk/commands/find_dependencies/find_dependencies.py
fixes: https://github.com/demisto/etc/issues/42348
> SDK - read dependencies from meta_data in find-dependency command

- demisto_sdk/commands/common/schemas/genericmodule.yml
https://github.com/demisto/content/pull/15795
> Generic Module Schema - add table view attributes

- demisto_sdk/__main__.py
published the `error-code` command.
> expose the error-code command

- CHANGELOG.md
- demisto_sdk/commands/common/hook_validations/conf_json.py
- demisto_sdk/commands/common/tests/conf_test.py
> Ignore Missing TPB For Dynamic Section Scripts

- CHANGELOG.md
> 1.5.3 release

- demisto_sdk/commands/find_dependencies/find_dependencies.py
quick fix to a newly-introduced error message
> missing in id-set error text fix

- CHANGELOG.md
> jobs changelog

- CHANGELOG.md
> fix 1.5.4 **run** command release notes

- CHANGELOG.md
- demisto_sdk/commands/common/tests/tools_test.py
- demisto_sdk/commands/common/tests/update_id_set_test.py
- demisto_sdk/commands/common/tools.py
- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py
> xsoar repos should be the same source in id_set

- demisto_sdk/commands/create_id_set/tests/create_id_set_test.py
fixes: https://github.com/demisto/etc/issues/44780
Make sure all id_set keys are checked for during the UT
> check for all id_set keys

- CHANGELOG.md
- demisto_sdk/commands/test_content/TestContentClasses.py
- demisto_sdk/commands/test_content/tests/integration_test.py
fixes: https://github.com/demisto/etc/issues/44178
Added the option to use Test Playbooks with instances with specified classifier/mapper/ incidentType
> added classifier, mapper and incident type to test playbook 

- demisto_sdk/commands/common/update_id_set.py
- demisto_sdk/commands/create_id_set/tests/create_id_set_test.py
fixes: https://github.com/demisto/etc/issues/44910
Added to each pack in id-set the content items within it.
[id_set.json.zip](https://github.com/demisto/demisto-sdk/files/7744552/id_set.json.zip)
> Id-Set: Add content items per pack

- demisto_sdk/commands/common/schemas/classifier.yml
- demisto_sdk/commands/common/schemas/incidentfield.yml
- demisto_sdk/commands/common/schemas/incidentfields.yml
- demisto_sdk/commands/common/schemas/incidenttype.yml
- demisto_sdk/commands/common/schemas/indicatorfield.yml
- demisto_sdk/commands/common/schemas/integration.yml
- demisto_sdk/commands/common/schemas/mapper.yml
- demisto_sdk/commands/common/schemas/playbook.yml
- demisto_sdk/commands/common/schemas/reputation.yml
- demisto_sdk/commands/common/schemas/script.yml
related: https://github.com/demisto/content/pull/16554, https://github.com/demisto/etc/issues/44708
Added the marketplaces field to the relevant schemas
I did not add the field to the schema of the unsupported xsiam items as we didn't add it to the items themselves.
> MarketplactV2: Added the marketplaces field to the relevant schemas
