demisto_sdk/yaml_tools/unifier.py

always require unique file names when building content artifacts, both when building locally or in circle

align local behavior to circle

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/common/hook_validations/base_validator.py
demisto_sdk/core.py

Changing exit method and adding error message for no RN
sys.exit doesnt seem to break the build on failure.
A search brought up the option to use os__exit instead

Changing exit method and adding error message for no RN

---

demisto_sdk/core.py
demisto_sdk/dev_tools/lint_manager.py

Adding git flag to lint command (instead of no-bc)
-g or --git will run lint on only changed packages (compared to master).

Adding git flag to lint command (instead of no-bc)

---

README.md

Ready
N/A
Fixes a typo in README.md in the bash completion setup instructions
N/A

Fixed typo in bash completion setup instructions

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/script.py

Ready
fixes: https://circleci.com/gh/demisto/content/39317
is_docker_valid was misplaced in script.py as a BC check, causing it to fail
docker was valid -> `is_docker_valid` returned true -> `is_breaking_backwards` = true -> validation failed.
last check
circle with a fix here (first build with sdk 0.3.5, second build with sdk of this branch)
https://circleci.com/gh/demisto/content/tree/mypy-update_testing

is_docker_valid was misplaced in script.py

---

demisto_sdk/commands/generate_docs/common.py
demisto_sdk/commands/generate_docs/generate_integration_doc.py
demisto_sdk/commands/generate_docs/generate_playbook_doc.py

Ready
- Support playbook inputs in the old format.
- Fix command context description generation.
- Remove playbookQuery from context example.

Minor fixes in generate-docs command

---

CHANGELOG.md
demisto_sdk/commands/init/initiator.py
demisto_sdk/commands/init/templates/HelloWorld/HelloWorld_test.py
demisto_sdk/commands/init/templates/HelloWorldScript/HelloWorldScript_test.py

Ready
fixes: https://github.com/demisto/etc/issues/21827
switched full path import to relative import.
after running:
1. `demisto-sdk init --script -n Shai --id shai -o .` or `demisto-sdk init --integration -n Shai --id shai -o .`
2. `demisto-sdk lint -d Shai`
both options return success
when initializing a pack:
1. `demisto-sdk init --pack -n Shai -o .`
2. `demisto-sdk lint -d Shai/Integrations/Shai`
also return success

fixed imports in templates

---

demisto_sdk/commands/init/templates/HelloWorld/HelloWorld.py
demisto_sdk/commands/init/templates/HelloWorldScript/HelloWorldScript.py

Ready
We are getting `Import pollutes the enclosing namespace` errors on our PRs from LGTM. Adding an ignore comment to our star imports in the templates to not have this error anymore.
@yaakovi what other ignore comments did you want to add to these lines?

add star import lgtm ignore to the demisto-sdk templates

---

demisto_sdk/commands/lint/lint_manager.py

Ready
https://github.com/demisto/demisto-sdk/pull/186
Use `git diff --name-only HEAD..HEAD^` to gets the changes between current master version and the last commit in master instead of: `https://github.com/demisto/content/compare/COMMIT_HASH...COMMIT_HASH` which depends on CIRCLE_COMPARE_URL variable.

Update lint get_packages_to_run from master

---

CHANGELOG.md
demisto_sdk/commands/unify/unifier.py

Ready
fixed an issue where long lines in unified yml caused syntax error due to automatic line breaks of ruamel dump.
see attached files
[with_bug.txt](https://github.com/demisto/demisto-sdk/files/4193391/with_bug.txt)
[without_bug.txt](https://github.com/demisto/demisto-sdk/files/4193393/without_bug.txt)

disable long line breaks in unified ymls

---

demisto_sdk/commands/unify/unifier.py

Ready
some scripts / integrations contains very long lines (like `WhoIs` below).
this is causing the sdk to split those lines in the unified yaml creating SyntaxErrors in code.

increase line width limit in scripts

---

README.md

Ready
`split-yml` had no such option for flag `-m` - removed from README

removed -m flag option from split yml readme

---

CHANGELOG.md
demisto_sdk/commands/common/tools.py

Ready
When working off-line or with a slow internet the version check can really slow things down for simple tasks. Added an env var `DEMISTO_SDK_SKIP_VERSION_CHECK` if it is set then version check is skipped. Additionally if `CI` is set then we skip. 

add env var to allow skip version check

---

requirements.txt

Ready
Bump PyYAML newest release version 5.3.1 which contains a security fix for [CVE-2020-1747](https://bugzilla.redhat.com/show_bug.cgi?id=1807367)

Bump PyYAML to 5.3.1

---

README.md
demisto_sdk/__main__.py

Ready
We should use `pip3` in our docs as on systems that have both py 2 and 3, using pip will fail.

use pip3 and not pip in docs

---

demisto_sdk/commands/common/hook_validations/incident_type.py

Ready
@mayagoldb FYI
fixes: https://github.com/demisto/etc/issues/23024
run on files from https://github.com/demisto/content/pull/6145 locally
```
(py37) ➜  content git:(pb_with_loop_keys) ✗ demisto-sdk validate -g
You are using demisto-sdk 0.4.8.dev2, however version 0.4.7 is available.
You should consider upgrading via “pip3 install --upgrade demisto-sdk” command.
Using git
Running validation on branch pb_with_loop_keys
Starting validating files structure
Validates only committed files
Validating IncidentTypes/incidenttype-mayag.json
Starting validation against origin/master
The files are valid
```

incidenttype validator - if field is 0 than failed

---

.circleci/config.yml
.coveragerc
.gitignore
README.md
pytest.ini
requirements-dev.txt
tox.ini

Ready
Adding code coverage support for our unit tests. A few changes to the build:
* add pytest.ini file to exclude: `demisto_sdk/commands/init/templates`
* removed flake8 from tox (it is run via pre-commit)
* coverage support (including upload to coveralls.io and to circleci artifacts)

Coverage support

---

demisto_sdk/__main__.py

Ready
fixes: https://github.com/demisto/etc/issues/22551
Running commands after hiding them:

Hide extract-code and create-content-artifacts from help

---

CHANGELOG.md
demisto_sdk/commands/common/tests/tools_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/tests/constants_test.py

Ready
When deleting a readme file, the validator tried to load the file as yml to check details in it.

fixed bug with validate on readme files when they are removed.

---

demisto_sdk/commands/common/constants.py

The Misc dir being `Packs/Base/Misc` caused the directory to be copied twice. 
As part of https://github.com/demisto/content/pull/6347, I'm reverting it.

Fix the misc dir

---

demisto_sdk/commands/lint/README.md
demisto_sdk/commands/lint/linter.py

1. Replace operator to bitwise operator.2. Update readme.
2. Replace operator to bitwise operator.# Please enter the commit message for your changes. Lines starting

Update Readme and Bitwise Operator fix

---

demisto_sdk/commands/common/hook_validations/integration.py
demisto_sdk/commands/common/tests/integration_test.py
demisto_sdk/commands/validate/file_validator.py

Moved `ImageValidator` and `DescriptionValidator` validations from `file_validator` to `integration`

Move ImageValidator and DescriptionValidator validations to IntegrationValidator

---

CHANGELOG.md
demisto_sdk/commands/secrets/secrets.py
demisto_sdk/commands/secrets/tests/secrets_test.py

fixes: demisto/etc#23400
There are lots of README.md files in. content repo, at least one per pack.
When messing with lots of README files it is not enough to know the base name of the file, the full path must be included.
In addition- when there are multiple files with the same names such as README.md it only shows secrets for the last one checked

demisto/etc#23400: printing file path instead of file name

---

demisto_sdk/commands/lint/helpers.py

fixes: https://github.com/demisto/etc/issues/23638
Fixing regression - Run lint (from master) will copy the following files and will override them if exists:
For python:
```
CommonServerPython.py
CommonServerUserPython.py
conftest.py
demistomock.py
```
For PowerShell:
```
CommonServerPowerShell.ps1
demistomock.ps1
```

Lint command - copy files and leave them there

---

demisto_sdk/commands/lint/lint_manager.py

fixes: https://github.com/demisto/etc/issues/23880
The bug source is in the creation of - "lint_report.json", and I can't reproduce the bug, I checked old builds and didn't find similar.
From the traceback I see that we have None values in the dict I am creating, however, it seems to be a bug in JSON dumps, Because I verified the logs and I see that all tests have keys initialized and value initialized, However, I removed the sort-key for now, if it will be reproduced I will get the JSON, this will avoid the bug in the future.

remove sort-can produce bug

---

demisto_sdk/commands/generate_docs/common.py
demisto_sdk/commands/generate_docs/generate_integration_doc.py
demisto_sdk/commands/generate_docs/generate_playbook_doc.py
demisto_sdk/commands/generate_docs/generate_script_doc.py
demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
demisto_sdk/tests/integration_tests/generate_docs_integration_test.py
demisto_sdk/tests/test_files/fake_integration/fake_README.md
demisto_sdk/tests/test_files/playbook-Test_playbook.yml

fixes: https://github.com/demisto/etc/issues/23824
fixes: https://github.com/demisto/etc/issues/23914
fixes: https://github.com/demisto/etc/issues/23931
1. Removes the `Source` column of the inputs table of the docs generated for playbooks by the `generate-docs` command.
2. The row for the inputs table generated for a playbook that accepted a `playbookInputQuery` as input was practically empty. Added default values for the `Name` and `Description` columns for inputs of this type to playbooks.
3. Quotation marks (single and double) were accidentally escaped if they appeared in the `Description` column. Fixed.
4. Updated the `Default Value` column to be the combined `root` and `accessor` (separated by a period) where applicable.

Generate Docs Bug Fixes

---

demisto_sdk/commands/run_cmd/runner.py
demisto_sdk/tests/integration_tests/run_cmd_integration_test.py
demisto_sdk/tests/integration_tests/run_integration_test.py

fixes: https://github.com/demisto/etc/issues/23611
There was a var that was not assigned but still used

run command - fix when running non-existing command

---

CHANGELOG.md
demisto_sdk/commands/download/downloader.py
demisto_sdk/commands/download/tests/downloader_test.py

fixes: https://github.com/demisto/etc/issues/24107
The file was causing the error was of type `preprocessrule`, the `find_type` function doesn't handle files of this type. From now and so on files of this type will be ignored by the download command.
@ShahafBenYakir I'll update the docs in a different PR will be opened soon.

Download bug fix

---

demisto_sdk/commands/common/hook_validations/docker.py
demisto_sdk/commands/common/tests/docker_test.py

When the docker image is not the latest we want to only return an error and not break build.

Docker image change should not fail build

---

demisto_sdk/commands/common/hook_validations/incident_field.py

The files `incidentfield-Claroty_Alert_Resolved.json`, `incidentfield-Claroty_Alert_Type.json`, `incidentfield-Code42_Alert_Type.json`,  `incidentfield-Code42_File_Events.json` and `XDR_Alerts.json` have the word "alert" in their names- This PR adds those names to the ignore white list.

Added names with alert to ignore white list

---

demisto_sdk/commands/validate/file_validator.py

Fixed bug in validation where a renamed unified file would fail `get_pack_name` function as it was a tuple.
Cherry picked from https://github.com/demisto/demisto-sdk/pull/447/commits/b9afaea672722c509997b29e54ebfe0df27e4e1e

Validator fix

---

CHANGELOG.md
demisto_sdk/commands/common/constants.py
demisto_sdk/commands/common/tests/constants_regex_test.py
demisto_sdk/commands/validate/file_validator.py

fixes: https://github.com/demisto/etc/issues/25204
Fixed an issue where new and old classifiers where mixed on validate command by editing their regex.

fixed old and new classifiers regex

---

demisto_sdk/commands/find_dependencies/find_dependencies.py

Update pack metadata `displayedImages` field only with first level of dependencies.

Update pack metadata with first level of dependencies images

---

demisto_sdk/commands/generate_docs/generate_integration_doc.py

fixes:
in case there is output with no description.

fixed error handling in generate-docs for missing output descriptions

---

demisto_sdk/commands/common/constants.py
demisto_sdk/commands/common/tests/errors_test.py
demisto_sdk/commands/common/tests/tools_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/update_release_notes/update_rn.py
demisto_sdk/commands/validate/file_validator.py

fixes: https://github.com/demisto/etc/issues/25737
We now check to see if an upstream is configured. If not and the origin is also not the content repo, we print a warning to explain how to configure an upstream. Git diffs will use the content master if the upstream is configured.

Added detection for and validation with upstream remotes for contributors

---

demisto_sdk/commands/create_artifacts/content_creator.py

Fixed a small issue in create-content-artifacts where uploading directories inside NonCircleTests dir raised an exception.
See an example [here](https://app.circleci.com/pipelines/github/demisto/content/16868/workflows/65f89bc9-71ba-4514-8ba2-1ae0afb396d5/jobs/59293/steps).

small fix in content creator

---

CHANGELOG.md
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py

fixes: https://github.com/demisto/etc/issues/25925
Dict of identified items was unsorted, so when iterating over the dict, if a value was repeated with another value in between the two, it would break the order of the generated release notes.

Sort changed_items dict by value in update_rn.py

---

demisto_sdk/commands/common/update_id_set.py
demisto_sdk/commands/generate_docs/generate_script_doc.py

fixes: https://github.com/demisto/etc/issues/23650
Fixed typo and turned off the output of id_set in generate_script_doc

fix typo and print to stdout generate docs

---

demisto_sdk/commands/create_artifacts/content_creator.py

The command would fail if `id_set.json` file was not present to be copied to the artifacts. Now it will copy it if the file is present, otherwise, it will continue.

Fix Content Creator's Copying of the `id_set.json` File

---

.circleci/config.yml

Because the `.tox` directory was being restored from cache from build to build, activating the cached `tox` environment and then executing `demisto-sdk` commands in various job steps would result in the cached version of the `demisto-sdk` to be run instead of the newest changes as checked out from the current build.

Circle Config Fixes

---

demisto_sdk/commands/validate/validate_manager.py

Add a fix for prev-ver flag in sdk-validate so now the validation will compare against the given branch.

fix prev-ver flag

---

demisto_sdk/commands/find_dependencies/find_dependencies.py
demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py

all integrations dependencies of indicator type are marked as optional.
need to add tests

set integration dependency of indicator types as optional

---

CHANGELOG.md
demisto_sdk/__main__.py

fixes: internal
* Added a prompt to the `demisto-sdk update-release-notes` command to prompt users to commit changes before running the release notes command when no changes are detected.

Add message to prompt users to commit their changes before running update RN command.

---

demisto_sdk/commands/generate_docs/common.py
demisto_sdk/commands/generate_docs/tests/generate_docs_test.py

If an html element contains a style prop it will cause mdx to fail rendering. Added regex to remove style prop. Also improved md example if receiving json.

remove style props when formatting md (generate docs)

---

demisto_sdk/__main__.py
demisto_sdk/commands/find_dependencies/find_dependencies.py
demisto_sdk/tests/integration_tests/find_dependencies_integration_test.py

fixes: https://github.com/demisto/etc/issues/26678
print an error message in case of misspelled pack name

handle wrong pack name in find dependencies

---

demisto_sdk/commands/lint/lint_manager.py

fixes: https://github.com/demisto/etc/issues/26869
In case active branch is master, `last_common_commit` will be set to previous master commit (equivalent to `'origin/master~1'`)

Fixed Lint and Unit Test on master branch

---

demisto_sdk/commands/lint/resources/pipfile_python2/Pipfile.lock
demisto_sdk/commands/lint/resources/pipfile_python3/Pipfile
demisto_sdk/commands/lint/resources/pipfile_python3/Pipfile.lock

https://github.com/demisto/demisto-sdk/pull/646
When executing lint command pylint validation failed with the error: `/usr/local/bin/python: No module named pylint`
reverting the old pip files fixed this issue.

Revert lint pipfile packages

---

CHANGELOG.md
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py

fixes: https://github.com/demisto/etc/issues/27382
Updated the method `build_rn_template` - make sure that file type is not None before build the release notes for this item.

validate file type in RN creation

---

demisto_sdk/commands/init/initiator.py
demisto_sdk/commands/init/tests/initiator_test.py

Changes init for contribution zip conversion. Namely,
- Author value can be passed when initializing the `Initiator` class to be set in the `pack_metadata.json` file.
- `support` field in `pack_metadata.json` file is set to `community`.
- `email` field in `pack_metadata.json` file is set to the empty string.
- Differentiate between the name set in `pack_metadata.json` file (display name and therefore can contain spaces) and the pack directory name which must be appropriately formatted.

Init Contribution Changes

---

demisto_sdk/commands/common/hook_validations/base_validator.py
demisto_sdk/commands/common/tests/base_validator_test.py

fixes: https://github.com/demisto/etc/issues/26881
```
================= Validating file =================
Validating Packs/PcapAnalysis/Playbooks/playbook-PCAP_File_Carving.yml as playbook
Validating scheme for Packs/PcapAnalysis/Playbooks/playbook-PCAP_File_Carving.yml
ERROR:pykwalify.core:validation.invalid
ERROR:pykwalify.core: --- All found errors ---
ERROR:pykwalify.core:["Cannot find required key 'description'. Path: ''"]
Packs/PcapAnalysis/Playbooks/playbook-PCAP_File_Carving.yml: [ST109] - Missing description in root
Please add to the root of the yml a description.
=========== Found errors in the following files ===========
Packs/PcapAnalysis/Playbooks/playbook-PCAP_File_Carving.yml - [ST109]
The files were found as invalid, the exact error message can be located above
```

handle_error better suggestion how to fix

---

CHANGELOG.md
demisto_sdk/__main__.py

Add the `--author` option to `init` command's cli arguments. Update the changelog to reflect the updates made to the `init` command relevant to contribution zip file conversion.

Init Author Option and Changelog

---

CHANGELOG.md
demisto_sdk/commands/update_release_notes/update_rn.py

fixes: https://github.com/demisto/etc/issues/27849
Error was caused when giving an incomplete path as an input.

Catch meta_data join error when path is not found in RN command

---

demisto_sdk/commands/lint/linter.py

FYI - @glicht @yaakovi 
Fix wrong handling when rerun should be done.
Build for validation (Excepted behavior - Fail on Pytest) - https://app.circleci.com/pipelines/github/demisto/content/23877/workflows/eebf4734-131f-4afa-ae9a-6c5415c43322/jobs/95383

Lint - Fix Rerun handling

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py

fixed an issue where update release notes crash when a file was renamed.
before:
after:

fixed a bug in update-release-notes command

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/validate/tests/validators_test.py
demisto_sdk/commands/validate/validate_manager.py

fixes: https://github.com/demisto/etc/issues/24157
continues PR: https://github.com/demisto/demisto-sdk/pull/744
Add the following behavior:
* demisto-sdk validate validates that the APIModule change is accompanied by release notes for all related packs.

Api module release notes support to validate

---

demisto_sdk/commands/create_artifacts/content_artifacts_creator.py

FYI - @yaakovi @bakatzir @orhovy @roysagi 
fixes: https://github.com/demisto/etc/issues/28546
Fixing duplicate lint log messages, I produced this bug when I rewrite the `content-create-artifacts` command, However I believe that we should develop a better mechanism for logging in our code (Singleton or any other solution) so it will not happen again.
After fix:

Fix lint duplicate log message

---

CHANGELOG.md
demisto_sdk/__main__.py

Fixed an issue where **update-release-notes** was failing with a wrong error message if no pack or input was given.
```
Starting to update release notes.
Collecting all committed files
Collecting all local changed files against the content master
Traceback (most recent call last):
File "/Users/darbel/.pyenv/versions/3.8.0/bin/demisto-sdk", line 11, in <module>
load_entry_point('demisto-sdk==1.2.1', 'console_scripts', 'demisto-sdk')()
File "/Users/darbel/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/Users/darbel/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/Users/darbel/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line …
```

[Fix] update-release-notes failing with exception when no path is given

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/commands/common/update_id_set.py
demisto_sdk/commands/create_id_set/create_id_set.py
demisto_sdk/commands/create_id_set/tests/update_id_set_test.py
demisto_sdk/commands/generate_docs/README.md
demisto_sdk/commands/generate_docs/generate_integration_doc.py
demisto_sdk/commands/generate_docs/generate_script_doc.py
demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
demisto_sdk/tests/test_files/docs_test/script-Set.yml

Small improvements to generate docs:
* Clarification on -e arg
* Use json formatting for context data
* Remove `Deprecated` logic in Script docs as this is handled in the the docs site.
* Script "Used In" to include max 10 entries
* Ignore 0.0.0 version (probably less relevant after move for version branch in content repo)
* Human Readable in script to be quoted as we do in integration docs
* Add _DEMISTO_SDK_ID_SET_REFRESH_INTERVAL_ (see changelog)
Generate doc can be seen here: 
https://github.com/demisto/content/blob/e94f5d29972183d33458e8743ef5f7ef619a6796/Packs/CommonScripts/Scripts/script-Set_README.md

Gen docs small improvements

---

CHANGELOG.md
demisto_sdk/commands/json_to_outputs/json_to_outputs.py
demisto_sdk/commands/json_to_outputs/tests/json_to_outputs_test.py

fixes: https://github.com/demisto/etc/issues/28471
isinstance of int was. checked before bool . bool is a subclass of int and as a result true was determined as int. converted the if statements to insure the correct type.

fixed an issue where jsontooutptus determined bool as int

---

demisto_sdk/commands/lint/helpers.py
demisto_sdk/commands/lint/tests/helper_test.py

added additional check in the split function. check not only if msg starts with E but also if there is the error number right after.

Fix for mypy error for files which name starts with E

---

demisto_sdk/commands/download/downloader.py

There's really no need to validate that the dir is in content, just we have packs.

remove uneeded term from download

---

.circleci/config.yml
.gitignore
CHANGELOG.md
demisto_sdk/commands/common/hook_validations/docker.py
demisto_sdk/commands/common/hook_validations/readme.py
demisto_sdk/commands/common/mdx-parse-server.js
demisto_sdk/commands/common/tests/create_id_set_test.py
demisto_sdk/commands/common/tests/dependencies_test.py
demisto_sdk/commands/common/tests/readme_test.py
demisto_sdk/commands/run_cmd/tests/runner_test.py
demisto_sdk/commands/split_yml/extractor.py
demisto_sdk/commands/split_yml/tests/extractor_test.py
demisto_sdk/commands/unify/tests/unifier_test.py
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/tests/integration_tests/find_dependencies_integration_test.py
demisto_sdk/tests/integration_tests/run_integration_test.py
package-lock.json
package.json
tox.ini

* Update to docker latest version to cache result. Reduced `demisto-sdk validate -i Packs/Base` from 1 min to under 30 seconds.
* Update to readme to cache result if node is available and use mdx server instead of spawning node each time. Reduced `demisto-sdk validate -i Packs/CommonPlaybooks ` from 2 minutes to under 20 seconds.
* Overrall `validate` is running now in 11 minutes (before over 1 hour and 20 minutes). See build.
* Changed build to just run all content tests also on branch and removed the `FAKE_MASTER` as it wasn't working anyway (see: https://github.com/demisto/etc/issues/28676)
* Changed all docker images to use specific version and where needed use an image with node
* Added node setup before running unit tests so readme validation tests run
* …

Validate speed up

---

demisto_sdk/commands/init/initiator.py

Updates the `init` command's conversion flow of a contribution zip file to use the non-interactive version of the `demisto-sdk format` command.

Use Non-Interactive Format Command in the init Command

---

.circleci/config.yml
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
requirements-dev.txt

Changed order of build steps to reduce build time. Build is down to under 20 minutes (before was over 25).
Main change is that tox-3-7 is used as dependency for the content repo tests instead of tox-3-8. tox 3-8 which is with coverage is run in paralel.
See the build in circleci for visual flow of the jobs.
Added a small fix so unit test update rn doesn't modify files in the repo.

Build improvements

---

CHANGELOG.md
demisto_sdk/commands/download/downloader.py
demisto_sdk/commands/run_cmd/runner.py
demisto_sdk/commands/run_playbook/playbook_runner.py
demisto_sdk/commands/upload/uploader.py

In short: this PR allows setting the env var: `DEMISTO_VERIFY_SSL=no` and avoid passing `--insecure` every time.
We were ignoring the `DEMISTO_VERIFY_SSL` var when `--insecure` was not specified. This small PR changes this behaviour so the demisto-py client will use the env var when --insecure is not passed. if --insecure is passed then that will be used. If the var is not set we default to verify as before. 

support for DEMISTO_VERIFY_SSL

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/readme.py
demisto_sdk/commands/common/tests/readme_test.py

Change logic to always run readme validations if node modules are available. If env variable `DEMISTO_README_VALIDATION` or `CI` is set then will not perform node modules test.

run readme validation if node modules are available

---

CHANGELOG.md
TestSuite/pack.py
demisto_sdk/commands/format/format_module.py
demisto_sdk/tests/integration_tests/format_integration_test.py

fixes: https://github.com/demisto/etc/issues/29696
- skipping files that are added to the dir when running lint
- handling commonserverpython
- not handling commonserverpowershell as we dont run format on it
- skipping doc image files

Format - skip unnecessary files

---

demisto_sdk/commands/find_dependencies/find_dependencies.py
demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py

Related: https://github.com/demisto/etc/issues/29255
Fixes: https://github.com/demisto/etc/issues/30052
Improved the timing from ~10-13 minutes to ~15 seconds.
1. Instead of generating a new dependencies graph for each pack from scratch and calculate its dependencies - A full dependencies graph of all packs will be generated once, saved into memory, and from it the dependency sub-graph of each pack will be extracted and used for the calculations
2. Once the full graph is ready, the dependency calculation of each pack will be executed concurrently using multiprocessing.
This is not a breaking change as I only added new methods so this can be merged regardless to the content PR.
This PR is about section 1, section 2 is in the matching content PR …

Speed up pack dependencies calculations

---

demisto_sdk/__main__.py

fixes: https://github.com/demisto/etc/issues/30228
Fixed the release notes -u type validation. 
Now when wrong type is inserted the following message will appear:
`Error: Invalid value for '-u' / '--update_type': invalid choice: revisiob. (choose from major, minor, revision, maintenance, documentation)`

Fixed release notes type validation

---

demisto_sdk/commands/find_dependencies/find_dependencies.py

Currently, when a pack contains only `pack_metadata` (for example) an exception will be raised, though it is a legal pack.
This is now fixed.

removed exception on pack dependencies calculation to allow for empty packs

---

demisto_sdk/commands/lint/lint_manager.py

Remove deprecated `fn` argument. Will not work on py3.8

remove deprecated argument from executor

---

demisto_sdk/__main__.py
demisto_sdk/commands/init/README.md
demisto_sdk/commands/init/contribution_converter.py
demisto_sdk/commands/init/initiator.py
demisto_sdk/commands/init/tests/contribution_converter_test.py
demisto_sdk/commands/init/tests/initiator_test.py
demisto_sdk/tests/integration_tests/init_integration_test.py

Contribution conversion has been split out into its own file/class under the `init` command directory. Furthermore the `init` command arguments related to contribution zip file conversion have been removed as this functionality is not intended to be used from the command line but rather only as an import to other code. While the convenience function of `convert_contribution_to_pack` has been left (in the new class `ContributionConverter`) for the simple case of creating a new pack from a contribution, the functionality has been broken down into multiple functions which allow for code that imports this class to handle different cases (such as when updating an existing pack) by invoking those functions as per their own requirements.

Contribution Convert Refactor

---

CHANGELOG.md
demisto_sdk/commands/format/update_integration.py

fixes: https://github.com/demisto/etc/issues/30748
Don't remove the default value from the `feed` param.

Format - avoid duplicate feed param

---

CHANGELOG.md
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/pack_unique_files.py
demisto_sdk/commands/common/tests/pack_unique_files_test.py

fixes: https://github.com/demisto/etc/issues/30821
Added warning instead of error, when validation fails if pack has no README.md

Validate bug readme

---

CHANGELOG.md
demisto_sdk/commands/generate_docs/common.py
demisto_sdk/commands/generate_docs/generate_integration_doc.py
demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
demisto_sdk/tests/test_files/fake_integration/fake_README.md

fixes: https://github.com/demisto/etc/issues/30814
When generating a README.md file, the numbers in a list are being reset after a list item that contains a table.

Generate-docs - need to add indentation to a table if it's a part of a list item.

---

demisto_sdk/commands/init/contribution_converter.py
demisto_sdk/commands/init/tests/contribution_converter_test.py

works toward: https://github.com/demisto/etc/issues/30565
Updates the `ContributionConverter` class to have a `gh_user` instance variable and use it when constructing the `pack_metadata.json` file for a new pack being created from a contribution via the UI.

update ContributionConverter to have a github user instance variable

---

.circleci/config.yml

fixes: https://github.com/demisto/etc/issues/31320
No need to restore cache when using tox
The tox has it's own caching and it appears like the cache we have saves also the sdk version and prevents it from changing until the next change in the requirements.txt.

Don't restore cache in validate files step

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/script.py
demisto_sdk/commands/common/tests/script_test.py

fixes: https://github.com/demisto/etc/issues/31340
* Fixed an issue where validate command checked docker image tag on ApiModules pack.

Fixed an issue where validate checked docker image tag on ApiModules

---

CHANGELOG.md
TestSuite/pack.py
demisto_sdk/commands/generate_docs/generate_integration_doc.py
demisto_sdk/commands/generate_docs/generate_playbook_doc.py
demisto_sdk/commands/generate_docs/generate_script_doc.py
demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py
demisto_sdk/tests/integration_tests/Packs/FeedAzureValid/ReleaseNotes/1_0_1.md
demisto_sdk/tests/integration_tests/update_release_notes_integration_test.py
demisto_sdk/tests/test_files/fake_integration/fake_README.md
demisto_sdk/tests/test_files/fake_integration/fake_integration.yml

fixes: https://github.com/demisto/etc/issues/30648
Customers will able to know from which demisto version they can use new integration.

Add fromversion when a new integration is released to the RN and readme.

---

CHANGELOG.md
demisto_sdk/commands/upload/uploader.py

For some reason this PR: https://github.com/demisto/demisto-sdk/pull/806/files?file-filters%5B%5D=.py#diff-4a64a8945d641acadd958e216f57f9227715f81df3fbeb7a98de88c563fd6538L35
Broke support for DEMISTO_VERIFY_SSL env variable in uploader

fix verify ssl in uploader to use DEMISTO_VERIFY_SSL

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/incident_type.py

Fixed an issue where Auto-Extract fields were only checked for newly added incident types in the **validate** command.

fixing auto extract validation

---

demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/id.py
demisto_sdk/commands/common/tests/id_test.py
demisto_sdk/commands/validate/validate_manager.py

Aside from the added validations there was code in the id.py that was not called `is_id_duplicated`,`is_file_has_used_id` - so I deleted him.
fixes: https://github.com/demisto/etc/issues/29559

add id set validations - script using real cmds, incident type has real default PB

---

CHANGELOG.md
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/id.py
demisto_sdk/commands/common/tests/id_test.py

When running on an automation which has no `depends-on`, it fails.
see: fix: https://app.circleci.com/pipelines/github/demisto/content/58736/workflows/127bc7e7-b183-45f8-a2b3-b178df38521d/jobs/245342
handled and added ut.

check if commands exist

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/commands/generate_docs/README.md
demisto_sdk/commands/generate_docs/generate_integration_doc.py
demisto_sdk/commands/generate_docs/tests/generate_docs_test.py

fixes: https://github.com/demisto/etc/issues/32372
edited the readme and help section for the correct usage of command permissions file
return an empty list and an error in the end of the generate-docs run if the command does not exist in permission file.

Generate-docs command cp flag fix

---

CHANGELOG.md
demisto_sdk/commands/validate/validate_manager.py

When updating an apimodule script, all the related integration should have release notes.
the command that updated all those integrations is `demisto-sdk update-release-notes -i Packs/ApiModules -u revision` and now is printed as the suggestion for all those packs.
fixes:https://github.com/demisto/etc/issues/32119

improved message

---

demisto_sdk/commands/test_content/TestContentClasses.py
demisto_sdk/commands/test_content/execute_test_content.py
demisto_sdk/commands/test_content/mock_server.py

Since the query data is sorted - we need to always clean the newly created mock files and not only when problematic keys are set.

Always clean mock file after creation

---

demisto_sdk/commands/test_content/TestContentClasses.py

The print about failing playback should be displayed only if the playbook had .mock record file and a playback attempt was ececuted.

Change print about failed playbook to where it belongs

---

demisto_sdk/commands/test_content/TestContentClasses.py

related: https://github.com/demisto/etc/issues/27164
The proxy key for `LogRhythm` is useproxy, we need to add that key to the configuration in order to let the integration to actually be mocked.

Adding useproxy key to mocked integrations to support LogRhythm

---

demisto_sdk/commands/test_content/mock_server.py
demisto_sdk/commands/test_content/tests/mock_unit_test.py

Since in the current flow, when running in nightly mode, all instances finishes their execution together and attempt to push their commits to the `content-test-data` repo together, some of them fail to do so.
For example in the latest nightly - only 3/10 managed to push the updated mock files, the rest received the following error:
```
! [remote rejected]     master -> master (cannot lock ref 'refs/heads/master': is at 2e6861f25cf3075ab1ebdfdfc94e663cefefb8fc but expected ed07a660dc4e53e22c694e4bb3725c8605f7e630)
error: failed to push some refs to 'git@github.com:demisto/content-test-data.git'
```

Add a lock for pushing content-test-data commits

---

demisto_sdk/commands/test_content/TestContentClasses.py

When the demisto server initializes it starts the default python2 container without any proxy configurations (because they are not configured on the server yet)
Therefore, when running unmockable tests playbooks with integrations that uses that container (such as Mimecast v2, BigFix etc.) some of the commands can go to the old non-configured container and the requests will be routed to the integration instance itself instead of using the proxy playback.
The solution is to reset all containers before starting to run mockable tests and reset it again when starting to run unmockable tests.

Reset containers before mockable tests as well

---

demisto_sdk/commands/test_content/TestContentClasses.py
demisto_sdk/commands/test_content/mock_server.py
demisto_sdk/commands/test_content/tests/BuildContext_test.py
demisto_sdk/commands/test_content/tests/TestContext_test.py
demisto_sdk/commands/test_content/tests/mock_unit_test.py
demisto_sdk/commands/test_content/tests/test_tools.py
demisto_sdk/commands/test_content/tools.py

https://github.com/demisto/etc/issues/29360
- Using the internal IP of the instance instead of the default docker bridge's IP.
- Added a method that will query the instance and check if this is a RHEL instance or not and return a boolean accordingly.
- Not running docker threshold tests on RHEL instance

Support running with REHL using podman

---

demisto_sdk/commands/test_content/TestContentClasses.py
demisto_sdk/commands/test_content/mock_server.py
demisto_sdk/commands/test_content/tests/BuildContext_test.py

In case filtered tests is empty - the test should be skipped.

Fixing a case where empty filtered tests makes all tests be executed

---

demisto_sdk/commands/test_content/TestContentClasses.py

So that it will be clear why that test wasn't executed without doing through the debug logs

In case a test needs to run but it's in nightly tests - log it in warning level

---

CHANGELOG.md
demisto_sdk/commands/generate_docs/generate_integration_doc.py
demisto_sdk/commands/generate_docs/tests/generate_docs_test.py

fixes: https://github.com/demisto/etc/issues/32937
We didn't consider an string that contain an empty dict = '{}' as empty output, therefor a section was created.

When Context Example is empty don't generate the section in generate-docs

---

.circleci/config.yml
TestSuite/repo.py
demisto_sdk/commands/common/update_id_set.py
demisto_sdk/commands/init/contribution_converter.py
demisto_sdk/commands/init/tests/contribution_converter_test.py
demisto_sdk/tests/integration_tests/content_create_artifacts_integration_test.py

slightly increased tox timeout.
adding no pipenv option for contribution converter - and implementing this in the unit tests.
improved implementation of `test_integration_create_content_artifacts_no_zip` and `test_integration_create_content_artifacts_zip` tests.
Decreased thread count in create_id_set to match cpu_count.

fixing flaky tests

---

demisto_sdk/commands/common/update_id_set.py
demisto_sdk/commands/generate_docs/generate_script_doc.py
demisto_sdk/commands/init/contribution_converter.py
demisto_sdk/commands/init/tests/contribution_converter_test.py

fixes: can see [here](https://github.com/demisto/content/pull/11061/files?file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.md&file-filters%5B%5D=.py&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension&file-filters%5B%5D=dotfile#diff-053d18c1fc73a7f732c55cecea5d9c2631319f0fb8978b6d0f5fb2d39f830ef1) that the README for scripts wasn't being properly generated and the unified wasn't getting deleted
The `generate_script_doc` function would fail, resulting in the readme for a script extracted to a package not getting generated and the unified YAML for the script not being removed as it should be.

Fix README Generation for Scripts during Contribution Conversion

---

.circleci/config.yml
demisto_sdk/commands/common/hook_validations/id.py
demisto_sdk/commands/validate/validate_manager.py

Recently the file's validation duration has increased significanly in the build.
Working with @bakatzir we profiled it and saw that at least 20% of the time it spends on opening the id_set file.
So an easy optimization is to open the id_set.json once and cache it for reuse.
This alone have decreased the duration in ~8 minutes.
In addition, instead of creating the content id_set, downloading it from the GCP bucket can also save additional ~2 minutes. 
All together - time reduction of ~9 minutes.

Performance improvement for all files validations

---

CHANGELOG.md
demisto_sdk/commands/common/constants.py
demisto_sdk/commands/find_dependencies/find_dependencies.py
demisto_sdk/commands/find_dependencies/tests/find_dependencies_test.py

…lation
fixes: https://github.com/demisto/etc/issues/29940
fixes: https://github.com/demisto/etc/issues/33105
ignore file/email/ip/send-mail/send-notification dependencies
when collecting script dependencies.
~~TODO - Consider ignoring them for PB dependencies as well.~~  decided to do so. please see the referenced issue 33105.
commonscripts pack deps after change:
```
Found dependencies result for CommonScripts pack:
{
"DemistoRESTAPI": {
"mandatory": true,
"display_name": "Demisto REST API"
}
}
```

Filter generic and reputation command from scripts and PBs deps calc

---

CHANGELOG.md
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/validate/tests/validators_test.py
demisto_sdk/commands/validate/validate_manager.py

Fixing an issue where pack metadata version bump was not enforced when modifying an old format (unified) file.

adding old format file version bump check

---

demisto_sdk/commands/common/errors.py

relates: https://github.com/demisto/content/pull/11111

add docker errros to ignore list to allow usage of non demisto images

---

conftest.py
demisto_sdk/commands/init/tests/contribution_converter_test.py

Fixing the cpu_count method to return 2.
Since Circle build has an issue in it's virtualization where it has only 2 VCPU's but the 'cpu_count' method returns all physical CPU's (36) which causes it to use too many processes in the process pools.
fixes: https://github.com/demisto/etc/issues/33244

Fix cpu_count in unittests

---

demisto_sdk/commands/test_content/TestContentClasses.py
demisto_sdk/commands/test_content/constants.py
demisto_sdk/commands/test_content/execute_test_content.py
demisto_sdk/commands/test_content/mock_server.py
demisto_sdk/commands/test_content/tests/build_context_test.py
demisto_sdk/commands/test_content/tests/mock_unit_test.py
demisto_sdk/commands/test_content/tests/test_context_test.py
demisto_sdk/commands/test_content/tools.py

As part of the [content-test-conf PR](https://github.com/demisto/content-test-conf/pull/1105) and the [content PR](https://github.com/demisto/content/pull/11149), this PR implements the lab lockdown.
Mostly this PR is about replacing the usage of the public IP with the private IP in the `ssh`, and `scp` calls, and about replacing the public IP in the localhost and port used in the tunneling for the https calls:
https://github.com/demisto/etc/issues/32500

Supporting lab lockdown

---

demisto_sdk/commands/test_content/TestContentClasses.py
demisto_sdk/commands/test_content/tests/build_context_test.py

Use the internal server_ip for setting integration params.
Specifically - for integrations that needs to be configured with the server's IP in run-time.
@DeanArbel @teizenman Can you add the test failure issue here?
Here's a build that should run the TAXII playbook: https://app.circleci.com/pipelines/github/demisto/content/66657/workflows/a02be122-10a6-480a-a007-418bd8adf466/jobs/275217
fixes: https://github.com/demisto/etc/issues/32567
But it will be fixed only on the next sdk release.

Replacing the server placeholder with the server's internal IP

---

demisto_sdk/commands/test_content/tests/timestamp_replacer_test.py
demisto_sdk/commands/test_content/timestamp_replacer.py

fixes: https://github.com/demisto/etc/issues/33496
when running a stream request the mock server is actually trying to run the request.
this PR will set the live state to False so the request will not run.

Potential Fix for Upload and Download Files from record

---

demisto_sdk/commands/common/content/objects/pack_objects/indicator_field/indicator_field.py
demisto_sdk/commands/upload/uploader.py

N/A
Up until now the SDK does not allow to upload indicator fields from the indicator fields folder of a pack. One has to wrap the individual JSON files into a temporary JSON array file and then upload it via the UI (Settings -> Advanced -> Fields -> Upload Icon). The API endpoint used in this operation is `/incidentfields/import` (which is wrapped in the Python client as `client.import_incident_fields()`).
The fix does something similar here: it re-uses the upload logic from the incident field pack object class. I decided against subclassing the incident field pack object class because I feel indicator fields deserve either a dedicated endpoint for uploads or the incident upload endpoint is generalized. So subclassing would create an unnecessary dependency between the two.
N/A

allowing indicator field upload

---

demisto_sdk/commands/test_content/TestContentClasses.py

Small enhancement to add server URL to failing test module messages

Added the server URL to failed test module checks

---

demisto_sdk/__main__.py
demisto_sdk/commands/common/git_util.py
demisto_sdk/commands/validate/validate_manager.py
demisto_sdk/tests/workflow_test.py

fixing git util to only recognize 100% rename and handle non 100% recognition 
This handles cases like this:

fixing git util to only recognize 100% rename and handle non 100% recognition

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/commands/validate/validate_manager.py
demisto_sdk/tests/integration_tests/validate_integration_test.py

fixes: https://github.com/demisto/etc/issues/34153
Now validate will try and use `demisto/master` as a default if demisto exists in local remotes.
Will revert to 'origin/master' otherwise.
Will use the given `--prev-ver` if set.

adding prev_ver setup

---

demisto_sdk/commands/test_content/Docker.py

Added support in powershell docker threshold test.
Up until now - the docker images that were collected weren't the right ones.
Here's an example of how it looks (and fails) with that new fix.

Added support in docker threshold test for powershell integrations

---

.circleci/config.yml

fixes: demisto/etc#33434
Separate the create-id-set, merge-id-set and validate to sub-tasks in SDK build, plus removing the redundant create-id-set task.

Seperate validate files to sub-tasks in SDK build

---

demisto_sdk/commands/test_content/TestContentClasses.py

moved the ssh tunnel log to the beginning of the function so it will be printed even if the test failed on configuring the integrations.
before:
after:

moved the ssh tunnel log before configuring the integrations

---

demisto_sdk/commands/common/hook_validations/base_validator.py
demisto_sdk/commands/common/tests/base_validator_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/lint/lint_manager.py
demisto_sdk/commands/lint/tests/linter_manager_test.py
demisto_sdk/commands/split_yml/extractor.py

Updates the output results of the `validate`/`lint` command to be formatted appropriately for use in the client. This is only applicable when outputting the results of `validate`/`lint` to an output json file.

Reformat validate and lint json output file results

---

demisto_sdk/commands/test_content/TestContentClasses.py

IntegrationScript can sometimes be `None`.
This PR is about handling those cases.

Fix parsing integration type for cases where integrationScript is None

---

demisto_sdk/commands/init/contribution_converter.py
demisto_sdk/commands/init/tests/contribution_converter_test.py

can see the failure in `process_pack` step of the github actions workflow [here](https://github.com/demisto/contribution-management/runs/2164144039?check_suite_focus=true)
In the flow of updating an existing content pack. After the contribution zip file would be unarchived into the destination pack directory, the contents of the unarchived directories would be moved to the corresponding directories in which they belong when in the content repo's Pack structure. e.g. `content/Packs/ExamplePack/integration/integration-exampleintegration.yml` would be moved to `content/Packs/ExamplePack/Integrations/integration-exampleintegration.yml`. This would work fine for content items like integrations and scripts because the package structure of the unified yml that was being copied to the pack was …

Fix overwrite existing files when updating existing pack

---

CHANGELOG.md
demisto_sdk/commands/common/constants.py
demisto_sdk/commands/common/hook_validations/integration.py
demisto_sdk/commands/common/tests/integration_test.py

https://github.com/demisto/etc/issues/34765
Changing integration validation for additionalinfo in parameter, changing its condition from equals to contained.
This is needed because some integrations do require to add more additionalinfo in their parameter, and currently
are enforced to stick to the current additionalinfo structure exactly instead of containing it

Validate Params Performs Contains on AdditionalInfo Instead Of Equals

---

demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py

It was now matched to the `doc-review` templates.

Added period in the end of the docker rn

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/integration.py
demisto_sdk/commands/common/hook_validations/readme.py
demisto_sdk/commands/common/tests/readme_test.py
demisto_sdk/commands/common/tools.py

fixes: https://github.com/demisto/etc/issues/34856
Added the validation of RM102 to run when either yml OR readme are changed (while making sure errors appear only once if both have been changed)

validate context paths difference when only README changes

---

demisto_sdk/commands/common/constants.py

Fix content Python 3.9 support for Enum extension in order to support python 3.9
https://github.com/demisto/content/pull/12271

Fix content Python 3.9 support for Enum extension

---

CHANGELOG.md
demisto_sdk/commands/common/tests/dependencies_test.py
demisto_sdk/commands/common/update_id_set.py
demisto_sdk/commands/create_id_set/tests/update_id_set_test.py

fixes: https://github.com/demisto/etc/issues/36166
fixed identify unified integration when running create-id-set

fix identify unified integration when running create-id-set

---

demisto_sdk/commands/common/constants.py
demisto_sdk/commands/common/content/tests/objects/pack_objects/pack_metadata/pack_metadata_test.py
demisto_sdk/commands/common/content/tests/objects/pack_objects/pack_test.py
demisto_sdk/commands/common/logger.py
demisto_sdk/commands/create_artifacts/tests/content_artifacts_creator_test.py
demisto_sdk/commands/test_content/IntegrationsLock.py
demisto_sdk/commands/test_content/ParallelLoggingManager.py
demisto_sdk/commands/test_content/TestContentClasses.py
demisto_sdk/commands/test_content/execute_test_content.py

Supporting gitlab and circle build infra:
- Replacing circle env variables with gitlab env variable.
- Moving files that should be used by multiple jobs in the same pipeline to artifacts.
- Adding mechanism for querying gitlab pipelines as well as circle workflows in the locking mechanism. 
- Using gitlab env variable for slack messages in case the build is in gitlab ci.
-  https://github.com/demisto/etc/issues/35417
-  https://github.com/demisto/etc/issues/35418
- https://github.com/demisto/content/pull/12203
- https://github.com/demisto/content-private/pull/344

Supporting gitlab-ci build

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/integration.py
demisto_sdk/commands/common/tests/integration_test.py

fixes: https://github.com/demisto/etc/issues/36846
Fixed an issue where **validate** failed when the 'display' field is empty but 'displaypassword' was provided.

Fixed issue when validate failed on invalid display and valid display password

---

CHANGELOG.md
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/pack_unique_files.py
demisto_sdk/commands/common/tests/pack_unique_files_test.py
demisto_sdk/commands/validate/tests/validators_test.py

fixes: https://github.com/demisto/etc/issues/37227
Added a validation that checks if pack's README is the equal to pack description, if so return error.

Validating pack readme vs description

---

requirements.txt

Rummel has broken BC with their safe loader at version 0.17.5 (also checked the new 0.17.6) and the issue persists.

updating ruamel

---

demisto_sdk/__main__.py
demisto_sdk/tests/integration_tests/format_integration_test.py

fixes: https://github.com/demisto/etc/issues/23560, https://github.com/demisto/etc/issues/37649
Solves issue when format command doesn't have an input which caused format command to not properly.
Solved by checking if it's None before casting to string.

Fix format command issue when not having an input

---

CHANGELOG.md
demisto_sdk/__main__.py

The `lint_manager` already included logic to handle comma-separated paths passed as the value for the `-i` command option argument but the `click.option` type of `click.Path` prevented passing such a value. Updates the type of the `-i` option to accept multiple paths separated by commas.

Enable multi-path input for lint command

---

demisto_sdk/commands/init/contribution_converter.py

fixes: https://github.com/demisto/etc/issues/35912
Formatting without specifying an input pack, will run on modified files via git.
https://github.com/demisto/contribution-management/runs/2813735595?check_suite_focus=true
https://github.com/demisto/contribution-management/runs/2784670854?check_suite_focus=true

Contribution Management - Formatting on modified files only

---

CHANGELOG.md
demisto_sdk/commands/unify/tests/unifier_test.py
demisto_sdk/commands/unify/unifier.py

fixes: https://github.com/demisto/etc/issues/38351
When giving input to unify that is a path to a file (e.g, YML of integration) it does not indicate that the input is not expected but sends an unclear error message.
Enhanced the command to return a more precise error message.

Add-Error-Message-To-Unify-Not-Dir

---

demisto_sdk/commands/common/errors.py

A clearer error message regarding `description_missing_in_beta_integration` when the description file is missing.

detailed description_missing_in_beta_integration error message

---

CHANGELOG.md
demisto_sdk/commands/init/initiator.py
demisto_sdk/commands/init/tests/initiator_test.py

fixes: https://github.com/demisto/etc/issues/38435
Fixed init command when trying to init a pack without filling the metadata file.

Fix init pack without filling metadata

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/commands/update_release_notes/README.md
demisto_sdk/commands/update_release_notes/update_rn.py
demisto_sdk/commands/update_release_notes/update_rn_manager.py
demisto_sdk/tests/integration_tests/update_release_notes_integration_test.py

fixes: https://github.com/demisto/etc/issues/37772
https://github.com/demisto/demisto-sdk/pull/1368
Added the ability to force update release notes with the --force flag or -f flag. After speaking to @ShahafBenYakir, we agreed that we only need the ability to automatically bump a version with the update release notes command and then manually filling in the changes.

Update rn force flag

---

demisto_sdk/commands/lint/helpers.py

fixed an issue with the coverage report when the test files were empty.
an example : 
[PR](https://github.com/demisto/content/pull/12793/files/001b23be64004e6d0f4dfc604eff00fe0f6d2071..122c5ac840ff7c8170ed8045d2df8c164b68f0f4)
[build](https://app.circleci.com/pipelines/github/demisto/content/97120/workflows/7b934cb7-4cd7-467f-8329-64135270651b/jobs/390467)

fixed an issue with the coverage report when the test files were empty.

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/release_notes.py
demisto_sdk/commands/common/tests/release_notes_test.py

fixes: https://github.com/demisto/etc/issues/38946
Fixed an issue where the release notes validation attempted to open a pack metadata file using an incorrect path.

fixing rn validation pack path

---

CHANGELOG.md
demisto_sdk/commands/generate_docs/generate_integration_doc.py
demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
pytest.ini

When generating docs disable auto linking to human readable output http links. This output has a lot of times garbage links and is disabled by default in the Server. This change makes human readable output act similar regarding linking as is in the Server.

generate docs: disable md auto links

---

requirements.txt

fixes:
```
[2021-07-13T15:19:52.047Z]   File "/usr/local/lib/python3.7/dist-packages/demisto_sdk/commands/common/errors.py", line 3, in <module>
[2021-07-13T15:19:52.047Z]     import decorator
```
Decorator used as an import, but missing in requirements

Add Decorator to requirements

---

CHANGELOG.md
demisto_sdk/commands/common/git_util.py
demisto_sdk/commands/common/tools.py

The tag that was sent to the `get_local_remote_file_path` included the git remote resulting in an incorrect path.
like here: https://github.com/demisto/content-internal-dist/pull/49/checks?check_run_id=3104104481

fixing getting local "remote" file

---

CHANGELOG.md
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py

fixes: https://github.com/demisto/etc/issues/40148
The update release notes command used the old docker image version instead of the new when the docker image was changed. Fixed the issue and fixed the unitest.

update RN docker image bug fix

---

CHANGELOG.md
demisto_sdk/__main__.py

Made `all-brands` an alias of the actual argument name `use_all_brands`

fixed broken generate-test-playbook argument name

---

CHANGELOG.md
demisto_sdk/commands/validate/tests/validators_test.py
demisto_sdk/commands/validate/validate_manager.py

fixes: https://github.com/demisto/etc/issues/40196
added filter for '.gitlab', '.circleci', and '.github' dirs.
so they will be removed from the validation section.

added filter for '.gitlab', '.circleci', and '.github' dirs in validate manager

---

demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/integration.py
demisto_sdk/commands/common/tests/errors_test.py

fixes: https://github.com/demisto/etc/issues/40242
When a test is skipped, and a skip-comment is available (for example, `No instance` or `Issue 12345`), show it as part of the validation error message.

Skipped-test comments

---

demisto_sdk/commands/test_content/TestContentClasses.py

see failing test in https://github.com/demisto/content/pull/13857
playbook with "fromversion: 6.2.0" run on server 6.1 as it was recognized by the SDK as `99.99.98`

updated the server version mapping with 6.1 and 6.2

---

CHANGELOG.md
demisto_sdk/commands/generate_test_playbook/test_playbook_generator.py

fixes: https://github.com/demisto/etc/issues/40605
Test playbooks were placed one level too deep (as the `test-integration` path does not perfectly reflect the one at `content`)
Now, the location is set relative to the pack folder, to prevent such confusions.

test playbook location fixed

---

demisto_sdk/commands/init/initiator.py

In the init command it is possible to ignore secrets automatically. Before you choose to ignore then there is a message to those secrets you are going to ignore. The message also appears in case there are no secrets. To fix this I have added an if statement to check if there are any secrets and only if so then print this message.

Add an if statement to check if secrets have been detected

---

CHANGELOG.md
demisto_sdk/commands/json_to_outputs/json_to_outputs.py
demisto_sdk/commands/json_to_outputs/tests/json_to_outputs_test.py

fixes: https://github.com/demisto/etc/issues/40195
Patch solving the issue, as the elegant solution caused too much hassle compared to the size of the bug.

parsing datetime.min as date on json-to-outputs

---

README.md
demisto_sdk/commands/common/tools.py

8 tests failed last night, all of them had this error
ignored_tests_set.update(tools.get_ignore_pack_skipped_tests(pack))
TypeError: get_ignore_pack_skipped_tests() missing 1 required positional argument: 'modified_packs'
https://code.pan.run/xsoar/content/-/jobs/7467479
due to a change that was pushed yesterday
https://github.com/demisto/demisto-sdk/pull/1599
added default value for this argument

Fix SDK Nightly Unittests Missing Required Param

---

CHANGELOG.md
demisto_sdk/commands/download/downloader.py

When you have an invalid YAML file related to a custom object on your Demisto server, you cannot use the download command. 
The current implementation parses all YAML files and does not handle this case.
Here is the exception I got when using `demisto-sdk download -i xxx -o Packs/Custom`
```
Traceback (most recent call last):
File "dem-sdk/.venv/bin/demisto-sdk", line 33, in <module>
sys.exit(load_entry_point('demisto-sdk', 'console_scripts', 'demisto-sdk')())
File "dem-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "dem-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "dem-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
return …
```

Fix error with download command when invalid YAML file on Demisto server

---

demisto_sdk/commands/run_cmd/runner.py

When using the run command, and when the result returned is not a string, demisto-sdk crashes with
the following exception:
```
Traceback (most recent call last):
File "dem-sdk/.venv/bin/demisto-sdk", line 33, in <module>
sys.exit(load_entry_point('demisto-sdk', 'console_scripts', 'demisto-sdk')())
File "dem-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "dem-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "dem-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "dem-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params) …
```

Fix error when entry.contents is not a str after running the run command

---

demisto_sdk/commands/common/tests/tools_test.py
demisto_sdk/commands/common/tools.py

Few changes were made
1. changed ID set to be an argument (this works well for content tests), as well of not performing HTTP call every function call to get ID set
2. Added a sanity test to see id set returns the tpb path and pack if not skip
This requires a change from content side to send ID set to get_ignore_pack_skipped_tests in collect_tests_and_content_packs) which contains id_set as its argument so it shouldn't be a problem (and of course change sdk requirement to the hash of this merge)

Sdk nightly failure Fix

---

demisto_sdk/commands/common/hook_validations/id.py
demisto_sdk/commands/common/tests/id_test.py

fixes: https://github.com/demisto/etc/issues/39936
make sure validate fails in case a playbook uses un supported versioned sub-playbook and the main playbook is fromversion below 6.0.0

failing skipunavaiable only if fromversion about 6.0.0

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/readme.py
demisto_sdk/commands/common/tests/pack_unique_files_test.py
demisto_sdk/tests/test_files/Packs/DummyPack2/README.md

fixes: https://github.com/demisto/etc/issues/40414
fixed the regex to find only src paths that are inside an html img tag.

Readme image validation regex fix

---

CHANGELOG.md
demisto_sdk/commands/test_content/TestContentClasses.py

Added an ability to configure mapper and classifier in the build test instances.

trying to add mapper and classifier to integration

---

demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/pack_unique_files.py
demisto_sdk/commands/common/tests/pack_metadata_validator_test.py
demisto_sdk/commands/common/tests/pack_unique_files_test.py
demisto_sdk/commands/validate/tests/validators_test.py
demisto_sdk/commands/validate/validate_manager.py

fixes: https://github.com/demisto/etc/issues/41424
fixes: https://github.com/demisto/etc/issues/41425
- skip non-folders when calling `validate -a`
- validate packs have `pack_metadata.json` 
both prevent crashes when running `validate`.

Fix `validate` crashes  - skip files, validate `pack_metadata` exists 

---

demisto_sdk/commands/common/GitContentConfig.py

Fixed to use gitlab token to get the repo ID instead of github token

Gitlab support fix

---

Pipfile
Pipfile.lock
README.md
demisto_sdk/__main__.py
demisto_sdk/tests/integration_tests/format_integration_test.py

Customer can now run several repositories using [.env file](https://pypi.org/project/python-dotenv/).
example:
.env file
```bash
DEMISTO_BASE_URL=http://127.0.0.1:8080
DEMISTO_API_KEY=XXXXXXXXXXXXXXXXXXX
```
the demisto-sdk auto loads the environment variable from cwd so the user don't need to update it manually each time he moves to another repo.
asked in https://xsoar.ideas.aha.io/ideas/FR-I-1438

added support for .env file

---

demisto_sdk/commands/upload/uploader.py

related: https://github.com/demisto/etc/issues/44184
removing the reputation from the supported list until we implement it in the demisto-py.

disable the upload of indicator type (not supported at the moment)

---

Pipfile
Pipfile.lock

fixes: https://github.com/demisto/etc/issues/43962
Calling `demisto-sdk download` fails when using python <3.9 **and** `importlib-resources` is missing

add importlib-resources

---

CHANGELOG.md
demisto_sdk/commands/format/tests/test_formatting_yml_test.py
demisto_sdk/commands/format/update_generic_yml.py

fixes: https://github.com/demisto/etc/issues/43893
When running a format on a YML file, the `id` value should be changed to the `name` value. However, we don't change existing YMLs, because we have legacy YMLs which the `id` value is not equal to the `name`, but we don't set the `id` as the old `id`. 
This change will keep the existing `id` when running `format`

Update id according to old file in format

---

CHANGELOG.md
demisto_sdk/commands/format/update_generic_yml.py
demisto_sdk/commands/split/tests/ymlsplitter_test.py
demisto_sdk/commands/split/ymlsplitter.py
demisto_sdk/commands/unify/tests/yml_unifier_test.py
demisto_sdk/commands/unify/yml_unifier.py
demisto_sdk/tests/test_files/integration-EDL.yml
demisto_sdk/tests/test_files/integration-EDL_old_generated.yml

fixes: https://github.com/demisto/etc/issues/44714
When unifying YML, the API module code content is copied to the script. However, when splitting the YML filed. This code is not removed.
This PR removes the copied API module, and replaces the original `import` code.

replace ApiModule code in YmlSplitter back to import

---

demisto_sdk/commands/download/downloader.py

fixes: https://github.com/demisto/etc/issues/45585 
fixes: https://github.com/demisto/demisto-sdk/issues/1803
Fix regex flag in download command.
The bug:
The `handle_regex_flag` func handle just the list of the files from the previous func -> `handle_all_custom_content_flag`
The fix:
The regex func will open the file with all the downloaded files and extract files according to the regex pattern.

Fix regex flag in download command

---

demisto_sdk/commands/test_content/TestContentClasses.py

fixes: [link to the issue](https://github.com/demisto/etc/issues/38628)
Changed Classifier/ Mapper to be given in the conf.json in content instead of test-conf.
*Can be only tested live while build is running, as the classifier and mapper configured are erased from the instance once it is deactivated. *

End to end test - instance's classifier/ mapper

---

demisto_sdk/commands/lint/commands_builder.py
demisto_sdk/commands/lint/helpers.py
demisto_sdk/commands/lint/linter.py
demisto_sdk/commands/lint/tests/command_builder_test.py
demisto_sdk/commands/lint/tests/helper_test.py
demisto_sdk/commands/lint/tests/test_linter/conftest.py
demisto_sdk/commands/lint/tests/test_linter/docker_runner_test.py
demisto_sdk/commands/lint/tests/test_linter/gather_facts_test.py
demisto_sdk/commands/lint/tests/test_linter/os_runner_test.py
demisto_sdk/tests/integration_tests/xsoar_linter_integration_test.py

fixes: [link to the issue](https://github.com/demisto/etc/issues/45687)
- Update the methods to use `packaging.version.parse` for getting the python version and return string instead of float:
- `get_python_version_from_image`
- `get_python_exec`
- `build_pylint_command`
- `add_typing_module`
- `_run_xsoar_linter`
- `_docker_image_create`
- Update all the places using python version from float to string inside `demisto_sdk/commands/lint/`
- Update tests.

fix get_python_version_from_image method

---

demisto_sdk/commands/common/content/objects/pack_objects/pack.py
demisto_sdk/commands/common/tools.py
demisto_sdk/tests/test_files/content_slim/Packs/Sample01/README.md

fix create-content-artifacts to filter pack items by id_set using id and not name.

Fix create-content-artifacts filter by id set

---

CHANGELOG.md
demisto_sdk/commands/lint/linter.py
demisto_sdk/commands/lint/tests/test_linter/docker_runner_test.py

fixes: [link to the issue](https://github.com/demisto/etc/issues/45667)
Added support to other container exit codes. So far we have only checked the following status codes [0,1,2,3,4,5].
[Before change](https://app.circleci.com/pipelines/github/demisto/content/137383/workflows/8ed806ee-1329-4d15-a111-331d495bd454/jobs/467551/artifacts) status code 137 is not handled properly.
[After change](https://circle-production-customer-artifacts.s3.amazonaws.com/picard/5755c24dc9e77c0001e4cb97/61fbeafa1d60c53121c8c2f2-0-build/artifacts/artifacts/lint_debug_log.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220203T150307Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Credential=AKIAJR3Q6CR467H7Z55A%2F20220203%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=07787719769342ab5a4e0b62fed8b21b0b432f63 …

Pytest handle container exit codes

---

CHANGELOG.md
TestSuite/pack.py
demisto_sdk/commands/common/content/objects/pack_objects/pack.py
demisto_sdk/commands/create_artifacts/content_artifacts_creator.py
demisto_sdk/tests/integration_tests/content_create_artifacts_integration_test.py

related issue: https://github.com/demisto/etc/issues/46570
see `CommonScripts` pack v1.6.35 in MPv2
Fixed an issue when filtering items using the ID set in the **create-content-artifacts** command.
failing test without the fix: There is a warning about the skipped item due to the bug.

Fix create content artifact filter by id set

---

CHANGELOG.md
demisto_sdk/commands/split/tests/ymlsplitter_test.py
demisto_sdk/commands/split/ymlsplitter.py

fixes: https://github.com/demisto/etc/issues/46777
fixes: https://github.com/demisto/demisto-sdk/issues/1893
yml-splitter no longer fails on relative paths.

fix relative split output resolving

---

docs/release_guide.md

Updated the release_guide.md so that it will be clearer that the scripts should be triggered on the branch of the release version of the SDK.

Improvements in the release_guide.md 

---

demisto_sdk/commands/lint/templates/dockerfile.jinja2

https://github.com/demisto/content/pull/17746
After moving to debian bullseye installing pylint and pytest requires gcc to be installed

fixing the way we generate the dev docker to run the pylint and pytest

---

demisto_sdk/commands/doc_reviewer/doc_reviewer.py

fixes: https://github.com/demisto/etc/issues/45688
there was a prev change that removed the functionality of the -g arg in the doc review. 
fixed this bug.

review-docs -g functionality 

---

CHANGELOG.md
demisto_sdk/commands/doc_reviewer/rn_checker.py

fixes: https://github.com/demisto/etc/issues/45254
missing commas in template list, resulting in one long wrong template

dev-bug - missing commas in template list

---

demisto_sdk/__main__.py
demisto_sdk/commands/common/hook_validations/readme.py
demisto_sdk/commands/common/tests/readme_test.py
demisto_sdk/commands/validate/validate_manager.py
demisto_sdk/tests/integration_tests/validate_integration_test.py

Run the validate all command with Multiprocessing,
This downgrade the run-time of the validate all from ~30 m' to ~10 m'.
Added a parameter to disable this for debugging.
The multiprocessing broke some prints (the percent for example), but IMO the run time is more important here,
And the important prints - the files with the errors - are still there.

Run validate -a with Multiprocessing

---

CHANGELOG.md
demisto_sdk/commands/find_dependencies/README.md
demisto_sdk/commands/find_dependencies/find_dependencies.py
demisto_sdk/commands/find_dependencies/find_dependencies_command.md

fixes: https://github.com/demisto/etc/issues/47212
using the argument -o without the argument --all-packs-dependencies did not print a proper warning
the warning that should be printed:

Dev bug - get dependencies - using the argument -o without the argument --all-packs-dependencies did not print a proper warning

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/doc_reviewer/rn_checker.py
demisto_sdk/commands/update_release_notes/README.md
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py

fixes: https://github.com/demisto/etc/issues/46957
Remove the support for the flag *maintenance* in the command **update-release-notes**, and added a validation for banned templates

Dev Task - Remove support for the flag *maintenance* in the command **update-release-notes**

---

CHANGELOG.md
demisto_sdk/commands/validate/tests/validators_test.py
demisto_sdk/commands/validate/validate_manager.py

fixes: https://github.com/demisto/etc/issues/47503
Validate Deleted Files crashes when using flag -g due to git returning file_paths as PosixPath

[Dev-Bug] - Validate Deleted Files crashes when using flag -g

---

CHANGELOG.md
demisto_sdk/__main__.py

fixes: https://github.com/demisto/demisto-sdk/issues/1975
* Fixed a typo in the **validate** `--quiet-bc-validation` flag.

`--quiet-bc-validation` flag typo fix

---

CHANGELOG.md
demisto_sdk/commands/common/handlers/json/ujson_handler.py
demisto_sdk/commands/common/handlers/tests/json_test.py

fixes: https://github.com/ultrajson/ultrajson/issues/110
a forward slash was esacpped, fixed it.

feat: removed escape of forward slash in json files

---

CHANGELOG.md
demisto_sdk/commands/create_artifacts/content_artifacts_creator.py

Fixed the destination path when unifying parsing/modeling rules to be in the parent directory.
Succesefull uploaded pack: https://code.pan.run/xsoar/content/-/pipelines/2749831

Fixed destination path for unified parsing/modeling rules

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/content_entity_validator.py
demisto_sdk/commands/common/tests/content_entity_validator_test.py

fixes: [link to the issue](https://github.com/demisto/etc/issues/47965)
When changing an ApiModule it’s considered as a script and fails on validating with RM109 (FileType.SCRIPT is missing a README file). This PR fixed this issue.
We can see that the issue was solved in this run (https://app.circleci.com/pipelines/github/demisto/content/156824/workflows/f0e2fcc8-ad5e-455e-8ad4-1e1e9d20828a/jobs/505454).
The RM109 error was not raised.

Validate - ignore readme on apiModule scripts

---

CHANGELOG.md
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/script.py

fixes: https://github.com/demisto/etc/issues/46877
Modified the error message which is returned in case a script is placed directly under the `Scripts` folder and not under `Scripts/script_name`.

Update Scripts Validation Error

---

CHANGELOG.md
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/integration.py
demisto_sdk/commands/common/tests/integration_test.py
demisto_sdk/commands/format/update_generic.py

fixes: https://github.com/demisto/etc/issues/47517
- Fixes an issue where when command arguments were left empty, both `format` and `validate` would fail unexpectedly.
- After the fix, the `format` command will add `[]` to the empty arguments, and the `validate` command will show an indicative error.

Handle empty command arguments

---

CHANGELOG.md
demisto_sdk/commands/format/tests/test_formatting_generic_test.py
demisto_sdk/commands/format/update_generic.py

fixes: https://github.com/demisto/etc/issues/47717
Update the validate flow after running format.
When you run format on an existing file in the repo, `validate -g` will run afterwards.
When you run format on a new file, `validate -i` will run afterwards.
I changed the fromVersion field and run `demisto-sdk format -i Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json` in my local env and now I see the error that @idovandijk got only in the build.

validate after format fix

---

CHANGELOG.md

Validation documentation was changed to unreleased.

Change validation to unreleased

---

CHANGELOG.md
demisto_sdk/commands/common/constants.py
demisto_sdk/commands/update_release_notes/update_rn.py

Remove duplicate SIEM integration identifiers

Remove duplicate SIEM integration identifiers

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/pack_unique_files.py
demisto_sdk/commands/common/tests/pack_unique_files_test.py

related to: https://code.pan.run/xsoar/content/-/jobs/12959981
When validating the pack metadata, we don't need to check the remote tags and use cases file.
We should use the local lists when running against the content repository and skip the validation when running against an external repository.

remove remote tags and use cases from validation

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/wizard.py
demisto_sdk/commands/common/schemas/wizard.yml
demisto_sdk/commands/common/tests/wizards_test.py

related: https://github.com/demisto/etc/issues/47460
The `link_to_integration` field was changed to be `optional` from the `platform` side - which changes existing validations a bit - if there's an `unmapped` playbook, it'll be mapped to all integrations that are not mapped.

[Wizard] Make link_to_integration optional

---

CHANGELOG.md
demisto_sdk/commands/upload/uploader.py

Upload lists when the input is the content pack folder.
n/a
When we upload a list directly this works but when its the entire content pack, the lists folder is ignored.

Add LISTS_DIR constant

---

demisto_sdk/commands/run_playbook/README.md

Changed the parameters from playbook_name to playbook_id since that's what the SDK command expects. playbook_name doesn't work

Update README.md for run_playbook command

---

CHANGELOG.md
demisto_sdk/commands/lint/lint_manager.py

support mypy messages that have neither `note:` nor `error:`

improve mypy parsing

---

CHANGELOG.md
demisto_sdk/commands/coverage_analyze/helpers.py
demisto_sdk/commands/coverage_analyze/tests/helpers_test.py
demisto_sdk/commands/lint/helpers.py

`unexpected file list in coverage report` should be logged using the `DEBUG` level, not `ERROR`.

fix debug logging level

---

CHANGELOG.md
demisto_sdk/commands/common/update_id_set.py

Fixed an issue where **merge-id-sets** failed when a key was missing in one id-set.json.

[Fix] merge-id-sets fails when a key is missing in a set

---

.circleci/config.yml
demisto_sdk/commands/lint/linter.py

Due to recent change in content that runs poetry, we shouldn't use `poetry run` when running from content (because it will try to run in `content` env).
Instead, we activate the demisto-sdk env before.

Fix steps which the working directory is content

---

demisto_sdk/commands/lint/helpers.py
demisto_sdk/commands/lint/lint_manager.py
demisto_sdk/commands/lint/tests/helper_test.py

Python 2 is no longer required by lint, so this step is redundant.

remove validate env

---

CHANGELOG.md
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/id.py
demisto_sdk/commands/common/tests/id_test.py

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3227)
1) Fixed an issue in the ```PB110``` validation where if we have more than one playbook-id, the validation could fail based on the looping order of those playbook-ids
2) enhance the validation error message
3) refactor the validation logic to be not prone to errors (but the validation itself should behave the same)
error message example:
```
[ERROR]: Packs/CommonPlaybooks/Playbooks/playbook-Search_And_Delete_Emails_-_Generic_-_v2_6_1.yml: [PB110] - Playbook Phishing Investigation - Generic v2 with 'fromversion' 6.0.0 uses the following sub-playbooks along with their invalid 'fromversion': [Packs/CommonPlaybooks/Playbooks/playbook-Search_And_Delete_Emails_-_Generic_-_v2_6_1.yml: 6.1.0]. The 'fromversion' of …
```

fix flaky PB110 validation

---

demisto_sdk/commands/common/content/objects/pack_objects/pack.py
demisto_sdk/commands/common/tests/tools_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/create_artifacts/tests/content_artifacts_creator_test.py
demisto_sdk/commands/find_dependencies/find_dependencies.py

Fixed an issue where in the `create-content-artifacts` command where item filtering did not exclude some items.
related to: https://panw-global.slack.com/archives/G011E63JXPB/p1656252244205309

fix item filtering in create-content-artifacts

---

demisto_sdk/commands/validate/validate_manager.py

We want to ignore `.devcontainer` folder in validate as we ignor `.github`, `circleci`, etc...

ignore devcontainer folder in validate

---

demisto_sdk/commands/test_content/TestContentClasses.py

In XSIAM we can't create a new incident/alert using API call.
We need a correlation rule in order to create an alert.
We want to create an alert manually, when we send an API call to XSIAM server to create a new alert.
Server check which integration sent a new alert, if the request was sent manually and not from integration it
sets "sourceBrand" header to be "Manual". XSIAM Server looks for a correlation rule for such sourceBrand,
and if there is no such correlation rule, no alert will be created.
If there is a correlation rule for "Manual" integration the allert will be created.
If this step fails please create an integration with id and name "Manual", set isFetch: true for such
integration and make sure that the corresponding correlation rule is created.

Add manual integration.

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/tests/integration_tests/generate_docs_integration_test.py
demisto_sdk/tests/test_files/Playbooks/Playbooks.playbook-test.yml
demisto_sdk/tests/test_files/Playbooks/playbook-Test_playbook.yml

[fixes: link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3311)
At the moment the only input allowed for generate-docs is a single file, we upgrade it to allow the command to work on a whole pack.

Allow generate-docs to run on folders (Multiple files)

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/base_validator.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/validate/tests/validators_test.py
demisto_sdk/commands/validate/validate_manager.py

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3564)
Raised exception when trying to fetch a file that was deleted locally. Changed to `get_remote_file` , and updated `get_type` command to support files without file type (files that we can assume the `file_type` by the path suffix)

Dev-Bug - error when trying to get file dict of a deleted file

---

README.md

Explaining why npm & MDX are required
closes: https://github.com/demisto/demisto-sdk/issues/2231

npm & MDX in README

---

demisto_sdk/commands/common/git_content_config.py

Condition was always true, we need to check `and`, not `or`.

ALLOWED REPOS were never checked

---

CHANGELOG.md
demisto_sdk/commands/common/tools.py

fixes an issue where an incident field that actually exist in build in fields is not recognized correctly by the validation due to case-sensitive

fix bug in MP-106 validation

---

demisto_sdk/commands/common/hook_validations/pack_unique_files.py
demisto_sdk/commands/format/tests/test_formatting_generic_test.py
demisto_sdk/commands/format/update_description.py
demisto_sdk/commands/format/update_generic.py

fixes: [breaks contribution-management](https://github.com/demisto/contribution-management/runs/7833468935?check_suite_focus=true)
- change the `BaseUpdate` class to actually consider `prev_ver` (typically the branch to diff against) when fetching the old version of a file
- remove the unnecessary class-scoped initialization of the `git_util` in the `PackUniqueFilesValidator` class whose sole purpose was to determine a default value for the class initialization parameter of `prev_ver` - replaced the dynamically determined default value with `master`

Remove Class-Scoped Initialization of git_util

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/commands/common/constants.py
demisto_sdk/commands/common/content_constant_paths.py
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/conf_json.py
demisto_sdk/commands/common/hook_validations/content_entity_validator.py
demisto_sdk/commands/common/update_id_set.py
demisto_sdk/commands/create_id_set/create_id_set.py
demisto_sdk/commands/format/update_generic_yml.py
demisto_sdk/commands/generate_docs/generate_script_doc.py
demisto_sdk/commands/update_release_notes/update_rn.py
demisto_sdk/commands/update_release_notes/update_rn_manager.py
demisto_sdk/commands/validate/tests/validators_test.py
demisto_sdk/commands/validate/validate_manager.py
demisto_sdk/tests/integration_tests/format_integration_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3590?filter=-2
This PR solves the issue of running `demisto-sdk` commands from subdirectories of content outside content repo with `DEMISTO_SDK_CONTENT_PATH` env variable preconfigures.
In addition, moved to use pathlib instead of relative path strings.

Content path reform

---

CHANGELOG.md
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/content_entity_validator.py
demisto_sdk/commands/common/hook_validations/field_base_validator.py
demisto_sdk/commands/common/hook_validations/incident_type.py
demisto_sdk/commands/common/hook_validations/integration.py
demisto_sdk/commands/common/hook_validations/mapper.py
demisto_sdk/commands/common/hook_validations/script.py
demisto_sdk/commands/common/hook_validations/structure.py
demisto_sdk/commands/common/tests/content_entity_validator_test.py
demisto_sdk/commands/common/tests/structure_test.py

related to:
https://github.com/demisto/content/pull/20360
structure validation should not contain BC checks.
Even if BC is breaking (intentionally), we still want to run all potential validations

move BC validation to base validator

---

demisto_sdk/commands/common/schemas/playbook.yml

This is a new field in Demisto 6.8. A little disappointed to start seeing this error on demisto-sdk 😅
Add the new field from Demisto 6.8 to the schema

Add continueonerrortype to Playbook Schema

---

demisto_sdk/commands/common/tools.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3590?filter=-2
Demisto-SDK validate from subdirectory of content still fails because it can't find pack-ignore pack

Use absolute path in tools to fix validation errors

---

demisto_sdk/commands/common/errors.py

Added space in the error message of non allowed category.

Added space in the error message of non allowed category

---

.circleci/config.yml

reducing installation time from 2:30 minutes to 7 seconds (when cache is available)

use cache for installing in `pre-install-steps` CI step

---

CHANGELOG.md
demisto_sdk/commands/download/downloader.py

No issue raised, but fixes ability to download XSOAR system content playbooks.
When attempting to download a system playbook from an XSOAR instance, the following exception occurs:
```
Exception raised when fetching custom content:
'str' object has no attribute 'get'
```
The error occurs because the result of `self.arrange_response(system_items_list)` is not assigned back to `system_items_list`.
When subsequently iterating through `system_items_list` (`for item in system_items_list:`), the `item` variable is referencing the key (e.g., `"playbooks"`).
Thus, `self.build_file_name(item)` raises an exception when attempting to invoke the `get()` method on the `str` object that is passed to it.
After setting the appropriate environment variables (`DEMISTO_BASE_URL` and `DEMISTO_API_KEY`), run: …

Bugfix: downloading system playbooks from XSOAR instance raises an exception

---

TestSuite/pack.py
demisto_sdk/commands/common/content/objects/pack_objects/modeling_rule/modeling_rule.py
demisto_sdk/commands/common/content/objects/pack_objects/parsing_rule/parsing_rule.py
demisto_sdk/commands/common/content/tests/objects/pack_objects/modeling_rule/modeling_rule_test.py
demisto_sdk/commands/common/content/tests/objects/pack_objects/parsing_rule/parsing_rule_test.py

cleanup issue: https://jira-hq.paloaltonetworks.local/browse/CIAC-4349
workaround to the required from/to version fields in XSIAM 1.2 using the external prefix.
pack files after the update:

workaround to from/to version in XSIAM 1.2 using the external prefix

---

.circleci/config.yml

Making sure pytest collection works properly, preventing cases where tests were named identically and collection breaks (especially locally)

check for pytest collection

---

CHANGELOG.md
demisto_sdk/commands/create_artifacts/content_artifacts_creator.py
demisto_sdk/commands/create_artifacts/tests/content_artifacts_creator_test.py
demisto_sdk/tests/test_files/Packs/TestModelingRule/ModelingRules/modelingrule-OktaModelingRules.yml

fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-65421
Added the datasets field to modeling rules' information in the metadata.json.
@ilaner FYI - we'll need to update in the graph impl as well

Datasets field in modeling rule metadata

---

.circleci/config.yml
CHANGELOG.md
demisto_sdk/commands/common/hook_validations/readme.py
demisto_sdk/commands/common/tests/readme_test.py

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3999)
Ignoring RM108 fails but doesn't output anything, now fixed.

Readme validation bug

---

CHANGELOG.md
demisto_sdk/commands/download/downloader.py
demisto_sdk/commands/download/tests/downloader_test.py

fixes: #2422
This fix will have the sdk download command honor the --no-code-formatting flag for existing files.

Fix download no-code-formatting for existing file

---

.git-blame-ignore-revs

- Adds the `.git-blame-ignore-revs` file in the root of the project
- Adds the merge-commit in which all the import lines in the repo were updated to the new `isort` length of 120

Add git-blame-ignore-rev File

---

demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py

Changes the environment variable name default value for the `--collector-token` option to match what is defined in the `XsiamApiClientConfig` class in `demisto_sdk/commands/test_content/xsiam_tools/xsiam_client.py`.

COLLECTOR_TOKEN --> XSIAM_COLLECTOR_TOKEN

---

CHANGELOG.md
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/validate/tests/validators_test.py
demisto_sdk/tests/integration_tests/validate_integration_test.py

fixes: [CIAC-4735](https://jira-hq.paloaltonetworks.local/browse/CIAC-4735)
Hotfix for **is_valid_category** and **is_categories_field_match_standard** which failed due to limits for pulling the approved categories list on content private build.

hotfix for categories validation for private repo

---

CHANGELOG.md
demisto_sdk/commands/format/tests/test_formatting_json_test.py
demisto_sdk/commands/format/update_layout.py

indicator file
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-18875
Prevent failure in setting the fromversion using format command, Caused by None in tabs object in indicator file.

avoid exception when tabs are none in

---

CHANGELOG.md
demisto_sdk/commands/common/tests/test_files/test_changelog.md
demisto_sdk/commands/common/tools.py

Fixed the `--release-notes` flag in demisto-sdk.

Fixed --release-notes flag

---

CHANGELOG.md
TestSuite/rule.py
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/modeling_rule.py
demisto_sdk/commands/common/tests/modeling_rules_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/test_content/test_modeling_rule/tests/init_test_data_test.py
demisto_sdk/commands/test_content/xsiam_tools/test_data.py
demisto_sdk/commands/validate/tests/validators_test.py
demisto_sdk/commands/validate/validate_manager.py
demisto_sdk/tests/constants_test.py
demisto_sdk/tests/test_files/modeling_rules.xif
demisto_sdk/tests/test_files/modeling_rules_testdata.json

- `demisto-sdk validate` will now check for the existence and proper formatting of a modeling rule's testdata file (assuming the modeling rule `fromversion` field is 6.10.0 or greater)
- When running `demisto-sdk validate -a` AKA validating the entire `content` repository, the `MR104` (existence of a testdata file for version compatible modeling rules) will be ignored so that way the validation won't fail on existing modeling rules that did not have testdat added in our Nightly.

Add TestData file validation for Modeling Rules

---

CHANGELOG.md
demisto_sdk/commands/common/content/objects/pack_objects/modeling_rule/modeling_rule.py
demisto_sdk/commands/common/content/tests/objects/pack_objects/modeling_rule/modeling_rule_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4925
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4926
- correctly parse out all of a modeling rule's xql modeling fields even when the modeling rule has arbitrary whitespace in it (newlines etc.)

Correctly Parse Modeling Rules with Arbitrary Whitespace

---

.git-blame-ignore-revs

Taking no blame for #2561, #2586

git-blame-ignore for pre-commit changes

---

CHANGELOG.md
demisto_sdk/commands/prepare_content/integration_script_unifier.py
demisto_sdk/tests/integration_tests/unify_integration_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4978
Fixes an issue that if a custom automation was created with -c, then make sure it gets created without any spaces so that the server will know how to read it properly.

fix issue in the prepare-content command with custom automation

---

CHANGELOG.md
demisto_sdk/commands/common/content/objects/pack_objects/xdrc_template/xdrc_template.py
demisto_sdk/commands/prepare_content/prepare_upload_manager.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4952
* Fixed an issue where **xdrctemplate** was missing 'external' prefix.
* Fixed an issue in **prepare-content** command providing output path.

fix - xdrctemplate was missing 'external' prefix.

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/integration.py
demisto_sdk/commands/common/tests/integration_test.py

Changed the **validate** command to don't fall on the IN124 error code when the parameter is of type 4 and is replaced with a new parameter of type 9.

Update the IN124 error

---

demisto_sdk/commands/content_graph/objects/incident_field.py
demisto_sdk/commands/content_graph/objects/incident_type.py
demisto_sdk/commands/content_graph/objects/indicator_type.py
demisto_sdk/commands/content_graph/objects/job.py
demisto_sdk/commands/content_graph/objects/widget.py

The metadata fields should be the field name and not the alias

fix metadata fields in content items

---

CHANGELOG.md
demisto_sdk/commands/content_graph/objects/integration_script.py

Handles issue where docker_native_image_config was not found in 1.8.2 when running the upload command causing it to fail if not updated from content master
edit: managed to test that this PR fix works on a content branch where i deleted the `docker_native_image_config.json`file.

handle docker_native_image_config.json file not found

---

demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py

- Adds an error message notifying of potential parsing rule-related errors.
- When testdata is pushed and there are parsing rules for its dataset that modify the _time field, it can mean that the event will be old in XSIAM. So adding a timeframe of 10 years to our xql queries will account for when the testdata event time is old.
- When interactively running test, sleep one second after doing an upload of the pack to allow time for the pack installation.

Add Timeframe to Queries

---

demisto_sdk/commands/content_graph/objects/pack.py

We assumed that there can't be empty packs for specific marketplace. However, it is a possibility and we need to handle this.

fix empty content items in create artifacts

---

CHANGELOG.md

Moved change log for https://github.com/demisto/demisto-sdk/pull/2660 into Unreleased section.

Moved xsoar-only flag to unreleased in CHANGELOG

---

CHANGELOG.md
demisto_sdk/commands/update_release_notes/update_rn.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5255
When the command was executed twice, it failed.
In the ticket.

update-release-notes failure on 1.8.3 bug

---

demisto_sdk/commands/common/MDXServer.py

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5598)
fixed an issue where e2e docker tests were failing on 409 conflict error

fix e2e docker tests failing on 409

---

.circleci/config.yml

We currently checkout the content repo without the git commit history because we didn't use it.
However the update graph needs it to tell which packs were changed. Example: https://app.circleci.com/pipelines/github/demisto/demisto-sdk/21469/workflows/f89ca2f5-f127-48ac-986d-29ab8ab70404/jobs/162971

Checkout Content with commit history

---

demisto_sdk/commands/content_graph/objects/content_item.py
demisto_sdk/commands/content_graph/objects/pack.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5618
This will not dump content items or packs which doesn't exist on local path

safe dump of packs and content items

---

demisto_sdk/commands/test_content/TestContentClasses.py

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5587)
reset client before executing unmockable tests

reset client before executing unmockable tests

---

CHANGELOG.md
demisto_sdk/commands/error_code_info/error_code_info.py

Until now error code arguments used to have parameters with type 'list'. In the last SDK update, new error codes were added and were using List[str] in their arguments which caused the following exception:
`TypeError: Type List cannot be instantiated; use list() instead`
Fixed it by adding this type to the TYPE_FILLER_MAPPING dict.
FYI @MLainer1 @dantavori

Error code params parsing bug fix

---

CHANGELOG.md
conftest.py
demisto_sdk/commands/lint/lint_manager.py
demisto_sdk/commands/lint/linter.py
demisto_sdk/commands/lint/tests/test_linter/conftest.py
demisto_sdk/commands/lint/tests/test_linter/gather_facts_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5344
do not run deprecated scripts/integrations when running **lint -a**

Skip deprecated integrations/scripts when running lint-a

---

CHANGELOG.md
demisto_sdk/commands/content_graph/objects/pack.py

Fixed the serverMinVersion when dumping the pack metadata to calculating by the minimum from version of the pack's content items.
@YuvHayun FYI

Fix server min version field in pack metadata

---

demisto_sdk/commands/content_graph/parsers/layout.py

Fixed an issue where we pull relationships from layouts to indicator fields with the prefix "indicator_", while the fields' object_ids never include this prefix.

layout parser fix

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/integration.py

fixes: [5605](https://jira-hq.paloaltonetworks.local/browse/CIAC-5605)
* Fixed an issue where **validate** failed with **is_valid_integration_file_path_in_folder** in cases of integrations with MSAPIModule.

ignore MSAPIModule validations when changing only the integration

---

CHANGELOG.md
demisto_sdk/commands/content_graph/common.py
demisto_sdk/commands/content_graph/objects/base_content.py
demisto_sdk/commands/content_graph/parsers/content_item.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5881
Added better handling for invalid input (invalid path) in the `unify` command.

fixed specific invalid input error in unify

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/integration.py

This PR adds files with the `ApiModule.py` suffix to an ignore list so that they won't be validate.
Example of the current validation:
> [ERROR]: /Users/username/dev/demisto/content/Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/AWSSecurityHubEventCollector.yml: [IN137] - The integration file name: ['AWSApiModule.py'] is invalid, The integration file name and all the other files in the folder, should be the same as the name of the folder that contains it.

Ignore API Module Files From Validate

---

CHANGELOG.md
demisto_sdk/commands/content_graph/parsers/pack.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6115
Fixed the default value for server_min_version when parsing packs without content items.

Fixed default value for server_min_version

---

CHANGELOG.md
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/download/tests/downloader_test.py
demisto_sdk/commands/download/tests/tests_env/content/Packs/TestPack/Layouts/layoutscontainer-mytestlayout.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22748
fixes: https://github.com/demisto/demisto-sdk/issues/2138
Fixes an issue that when trying to download a layout without the `-f` arg, it would override the layout inside a pack.

Fix layouts gets overriden in download without -f

---

demisto_sdk/commands/common/hook_validations/graph_validator.py
demisto_sdk/commands/content_graph/tests/graph_validator_test.py

fixes a Neo4j exception during validate:
```
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Variable `None` not defined (line 7, column 50 (offset: 381))
"AND (p1.object_id in ['MicrosoftExchangeOnline', None] OR p2.object_id in ['MicrosoftExchangeOnline', None])"
```
occurred in https://github.com/demisto/content/pull/25594

Graph validate fix

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/playbook.py
demisto_sdk/tests/test_files/playbook_valid_inputs.yml

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6206
- Updates the `collect_all_inputs_in_use` method to remove `}` from the PB input name.
- Added to **playbook_valid_inputs.yml** the input `ResourceName` and use it in the task like this:
`simple: ${inputs.ResourceName}`
for testing the validation after the change.

Fix pb inputs validation

---

CHANGELOG.md
demisto_sdk/commands/prepare_content/prepare_upload_manager.py

fixes: https://github.com/demisto/demisto-sdk/issues/2906
Currently we log only the unify step and print that we were succeeded to unify the YML, but we don't log the output file path so the user does not know where the file is saved.

log the output file in prepare_content

---

CHANGELOG.md
demisto_sdk/commands/validate/validate_manager.py

fixes:https://jira-hq.paloaltonetworks.local/browse/CIAC-6195
Fixed an issue where validate printed errors in uniqe files twice.
The line removed in not necessary because of https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/common/hook_validations/base_validator.py#L258

removed unnecessary logging

---

CHANGELOG.md
demisto_sdk/commands/lint/helpers.py
demisto_sdk/commands/lint/tests/helper_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6336
currently, if an integration imports ApiModuleA and ApiModuleA imports ApiModuleB
only the  ApiModuleA copied to the lint directory
fix: go recursively on the imported ApiModules and copy all of them

Linter: copy multi level ApiModules to the lint dir

---

CHANGELOG.md
demisto_sdk/commands/init/contribution_converter.py
demisto_sdk/commands/init/tests/contribution_converter_test.py

…n_items_version_note
relates: [CIAC-3818](https://jira-hq.paloaltonetworks.local/browse/CIAC-3818).
Improved the message that is automatically generated on contributions PRs that add changes to old pack versions. 
Related PR: [2808](https://github.com/demisto/demisto-sdk/pull/2808).
Tested the improved message in this PR - [26067](https://github.com/demisto/content/pull/26067).
The final message is:

Improve the message on contribution PR to an old pack versions

---

CHANGELOG.md
demisto_sdk/commands/common/tests/tools_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5848
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6176
Added fixes to open dev-bugs. 
1. validate that get yml return value is of type dict. 
2. validate that no new release notes are being generated when running update-release-notes on a first version

Reales notes fix bugs

---

CHANGELOG.md
demisto_sdk/commands/content_graph/content_graph_commands.py
demisto_sdk/commands/content_graph/objects/base_content.py

* Fixed issue with `update-content-graph -i <path> -g` that ignored 
* Store first level dependencies when using multiprocessing (during the dump method).
fixes:
https://code.pan.run/xsoar/content/-/pipelines/5158419

update-content-graph ignored parameter

---

demisto_sdk/__main__.py

fixes:
Change the flags to <do> / --no-<do> for the optional hooks.
In the pre-commit hook itself we will disable it

change precommit flags behavior

---

CHANGELOG.md
demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py

Fix fail if modeling rules command fails. 
Currently, it only prints the error in red, but it should fail the command as well. Adding exitcode 1.
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6618

fail if modeling rules command fails

---

CHANGELOG.md
demisto_sdk/commands/test_content/TestContentClasses.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6653
Reset containers request(POST request to`/containers/reset`) failed in NG machines with the error:
>  {"id":"errUnsupportedAPI","status":400,"title":"this API is not supported","detail":"this API is not supported","error":"this API is not supported (52000)","encrypted":false,"multires":null}
see[ this build](https://code.pan.run/xsoar/content/-/jobs/25947200) for example
I updated the **_reset_containers** method to continue and not reset containers when the version is XSAIM or NG.

Fix execute tests

---

CHANGELOG.md
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/upload/uploader.py

* Fixed an issue where **upload** would not read a repo configuration file properly.
* Fixed an issue where **upload** would not handle the `-x`/`--xsiam` flag properly.

fix upload config file parsing

---

CHANGELOG.md
demisto_sdk/commands/common/constants.py
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/integration.py
demisto_sdk/commands/common/tests/integration_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3678
Make the existing `IN154` run on non-modified (new) files as well, and assure feeds have a reliability parameter as well.

Add a Validation To Assure Feed Integrations Have A Reliability Parameter

---

CHANGELOG.md
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/xsiam_dashboard.py
demisto_sdk/commands/validate/validate_manager.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4572
Validation has been added to XSIAM image dashboard names that begin with the pack name.
valid example:
pack_name => `Example`, dashboard_image => `Example_dashboard_image.png`
invalid example:
pack_name => `Example`, dashboard_image => `example_dashboard_image.png`

Validation for dashboard image name starts with the pack name

---

CHANGELOG.md
demisto_sdk/commands/common/git_util.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6889?filter=-1
* When checkout the repo in GitHub actions, the default state it checks out is on detached head, meaning it is not aware the branch. We don't actually need the branch to run and the commit hash is enough.
* It is safer to run git diff on the current commit hash, since the branch name could be messy and not related to the actual commit we would like to check.

Support gitutil on detached head

---

CHANGELOG.md
demisto_sdk/commands/content_graph/parsers/json_content_item.py
demisto_sdk/commands/content_graph/parsers/xsiam_dashboard.py
demisto_sdk/commands/content_graph/parsers/xsiam_report.py
demisto_sdk/commands/content_graph/tests/parsers_and_models_test.py
demisto_sdk/commands/content_graph/tests/test_data/xsiam_dashboard.json
demisto_sdk/commands/content_graph/tests/test_data/xsiam_report.json

fixes:
Edited the parser of XSIAM Dashboard and reports to parse the fromVersion, toVersion fields from the top level of those json files (it caused an issue in the parsing of the pack server min version that led us to install packs that should not be installed)

updated versions properties for xsiam content items in graph

---

CHANGELOG.md
demisto_sdk/commands/lint/resources/pylint_plugins/certified_partner_level_checker.py
demisto_sdk/tests/constants_test.py
demisto_sdk/tests/integration_tests/xsoar_linter_integration_test.py
demisto_sdk/tests/test_files/py3_XSOARLinter_demisto_results_warnings.py
demisto_sdk/tests/test_files/py3_XSOARLinter_demisto_results_warnings.yml

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6738
- Fixed an issue where **lint** falsely warned of using `demisto.results` command, for files who have to use it, for example scripts/integrations with `indicator- format` tag, they can't use `CommandResults`, so they have to use `demisto.results`.

fix for sdk linter retuning false warning

---

CHANGELOG.md
demisto_sdk/commands/common/content/objects/pack_objects/modeling_rule/modeling_rule.py
demisto_sdk/commands/common/content/tests/objects/pack_objects/modeling_rule/modeling_rule_test.py
demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
demisto_sdk/commands/test_content/test_modeling_rule/tests/test_modeling_rule_test.py
demisto_sdk/commands/test_content/xsiam_tools/test_data.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4949
In order to test the parsing rules (time field) I added the time field by default to the `test-modeling-rules` command.
Before the fix:
After the fix (failed result):
After the fix (success result):

added the time field to the test-modeling-rules

---

CHANGELOG.md
demisto_sdk/commands/content_graph/objects/content_item.py
demisto_sdk/commands/upload/tests/uploader_test.py

fixes:
This happens when content items deleted from content but the official graph in bucket (which is uploaded twice a day) contain those.

Graph: safe get file in graph

---

CHANGELOG.md

due to wrong git merge - there is wrong entry in the Changelog for version `1.16.0`
move it to the `unreleased` section

Fix Changelog after sdk release

---

CHANGELOG.md
demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py

Fixed an issue where the **modeling-rules test** command failed to get the existence of dataset in cases where the dataset takes more than 1 minute to get indexed.
related: [conversation](https://panw-global.slack.com/archives/G011E63JXPB/p1687087774598549)

[modeling-rules test] - increase timeout when querying for dataset existence

---

CHANGELOG.md
TestSuite/pack.py
demisto_sdk/commands/content_graph/common.py
demisto_sdk/commands/content_graph/objects/__init__.py
demisto_sdk/commands/content_graph/objects/pack.py
demisto_sdk/commands/content_graph/objects/pre_process_rule.py
demisto_sdk/commands/content_graph/parsers/__init__.py
demisto_sdk/commands/content_graph/parsers/layout.py
demisto_sdk/commands/content_graph/parsers/pack.py
demisto_sdk/commands/content_graph/parsers/pre_process_rule.py
demisto_sdk/commands/content_graph/tests/parsers_and_models_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25326?filter=-1
* Add PreProcessRule content item
* Handle correctly a case where `marketplace` field in `pack_metadata.json` is an empty list.
* Identify LayoutContainer by the data and not by name.

Content Models: supporting preprocess rules and enhancements and

---

demisto_sdk/commands/lint/helpers.py

fixes: 
See failure here: https://code.pan.run/xsoar/content-internal-dist/-/pipelines/5577499
We should not fail if CommonServerUserPython is not found, because we create it later in the pipeline

Lint: Don't fail if CommonServerUserPython does not exists

---

CHANGELOG.md
demisto_sdk/commands/content_graph/objects/integration.py

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25606
* Fixed an issue where an integration containing a command without a description would fail to upload while using the **upload** command.

Fix for optional command description

---

.circleci/config.yml
poetry.toml

fixes:
This will configure the `poetry` to install the virtualenv in `.venv` folder. 
This will make Demisto-SDK development configuration easier.

Configure poetry to install in .venv folder

---

CHANGELOG.md
demisto_sdk/commands/content_graph/objects/indicator_type.py

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25578
As mentioned in the ticket, the server expects the indicator type to be uploaded as an array. This change is identical to the implementation in Incident Types.

Implement new upload logic to indicator types

---

demisto_sdk/commands/format/tests/test_formatting_yml_test.py
demisto_sdk/commands/format/update_integration.py
demisto_sdk/tests/test_files/integration-fetch-valid.yml

Fixed an issue with the format command which added parameters we already have in an integration due to a mismatch in the parameters when comparison (we compare dicts so I removed optional parameters from original integration param)

added the required field to optional fields

---

CHANGELOG.md
demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
demisto_sdk/commands/test_content/test_modeling_rule/tests/test_modeling_rule_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7147
Fixed an issue where the **modeling-rules test** command failed to get the existence of result from dataset in cases where the results take time to load.

test-modeling-rules-fixes

---

.github/workflows/close_jira_issue_by_pr_merge.yml
.github/workflows/link_edited_pr_to_jira_issue.yml

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7269
We want to move the webhook that runs the script LINK_PR_TO_JIRA_ISSUE to Content Gold NG.

Move LINK_PR_TO_JIRA_ISSUE to Content Gold NG

---

CHANGELOG.md
demisto_sdk/__main__.py

fixes:
Fix typo in the log's flag help.

Fixed Typos in log help

---

demisto_sdk/commands/run_unit_tests/unit_tests_runner.py

fixes:
Fix run-unit-test command:
When running pytest it should be in a list, when running powershell supposed to be a str

fix run-unit-tests command

---

demisto_sdk/commands/lint/commands_builder.py
demisto_sdk/commands/lint/tests/command_builder_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7415
Added severity rule to the pwsh analyzer to return only errors, not warnings.

ignore non error outputs

---

TestSuite/job.py
demisto_sdk/commands/common/content/objects/abstract_objects/yaml_object.py
demisto_sdk/commands/common/content/objects/pack_objects/readme/readme.py
demisto_sdk/commands/common/content/tests/objects/abstract_objects/json_object_test.py
demisto_sdk/commands/common/handlers/json/orjson_handler.py
demisto_sdk/commands/common/handlers/json/ujson_handler.py
demisto_sdk/commands/common/handlers/yaml/ruamel_handler.py
demisto_sdk/commands/common/hook_validations/base_validator.py
demisto_sdk/commands/common/hook_validations/correlation_rule.py
demisto_sdk/commands/common/hook_validations/modeling_rule.py
demisto_sdk/commands/common/tests/release_notes_test.py
demisto_sdk/commands/content_graph/interface/neo4j/queries/dependencies.py
demisto_sdk/commands/content_graph/objects/base_content.py
demisto_sdk/commands/content_graph/objects/incident_field.py
demisto_sdk/commands/content_graph/objects/indicator_type.py
demisto_sdk/commands/generate_integration/XSOARIntegration.py
demisto_sdk/commands/prepare_content/integration_script_unifier.py
demisto_sdk/commands/prepare_content/rule_unifier.py
demisto_sdk/commands/prepare_content/tests/xdrc_template_unifier_test.py
demisto_sdk/commands/split/ymlsplitter.py
demisto_sdk/commands/test_content/timestamp_replacer.py
demisto_sdk/commands/test_content/xsiam_tools/xsiam_client.py
demisto_sdk/utils/circle-ci/circle_ci_client.py
pyproject.toml

* Added Ruff `TID251`, preventing import of `json` and `ruamel.yaml` directly (configured in `pyproject.toml`)
* Replaced all direct imports with handler imports (or, rarely, `noqa`s)

Require JSON/YAML_Handlers

---

CHANGELOG.md
demisto_sdk/commands/common/docker_helper.py

* Fixed an issue where in case a docker image could not be found locally, we would return DockerClient image instead of an Image object leading to possible `AttributeError` in functions using the `pull_image` function.

[docker_pull] - return Image object instead of DockerClient

---

demisto_sdk/commands/common/hook_validations/readme.py
demisto_sdk/commands/common/tests/readme_test.py
demisto_sdk/tests/test_files/README-invalid.md

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7325
Fixed the regex for the detection of wrong image URLs in README files (RM101 error).

fixed regex for the wrong image url detection

---

CHANGELOG.md
pyproject.toml

demisto-sdk release changes
* Fixed an issue where the *DEMISTO_SDK_SKIP_VERSION_CHECK* was ignored when running on non CI environments.
* Added the ability to ignore any validation in the **validate** command when running in an external (non-demisto/content) repo, by placing a `.private-repo-settings` file at its root.
* Fixed an issue where **validate** falsely detected backwards-compatibility issues, and prevented adding the `marketplaces` key to content items.
* Calling **format** with the `-d` flag now removes test playbooks testing the deprecated content from conf.json.
* Fixed an issue where the SDK would fail pulling docker images.
* Fixed an issue where **prepare-content** command would add the string `candidate` to scripts and integrations for the *nativeimage* key.
* Fixed an …

demisto-sdk release 1.18.0

---

demisto_sdk/commands/common/tests/test_files/test_sha1/content/file.txt
demisto_sdk/commands/common/tests/test_files/test_sha1/content/file2.txt
demisto_sdk/commands/common/tests/tools_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/content_graph/interface/graph.py
demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
demisto_sdk/commands/content_graph/tests/update_content_graph_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7520
Added a validation that content_graph was created with the current version of the parser.
if not it will create the graph from scratch.

added sha1 validation for content graph parser

---

CHANGELOG.md
pyproject.toml

demisto-sdk release changes
* Fixed an issue where the coloring directives where showing in log messages.
* Fixed an issue where **create-content-graph** was not executed upon changes in the parser infra files.
* Added a parameter `skip-packs-known-words` to the **doc-review** command, making sure that pack known words will not be added.

demisto-sdk release 1.18.1

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/structure.py
demisto_sdk/commands/common/tools.py

related: https://jira-hq.paloaltonetworks.local/browse/CIAC-7590
Adds support in validate command for svg images that will be used in the dynamic dashboard.

Support svg images in validate command

---

pyproject.toml

Following https://github.com/demisto/demisto-sdk/pull/3394, https://github.com/demisto/demisto-sdk/pull/3410
making sure we don't go back to using `distutils.version` (which prevents supporting Python 3.11)

prevent using deprecated distutils.version

---

CHANGELOG.md
pyproject.toml

demisto-sdk release changes
* Added the **graph** command group. The **create-content-graph** and **update-content-graph** commands were migrated to this command group, and named **graph create** and **graph update** respectively.
* Added the **graph get-relationships** command.
* The **graph create** command will now use a list of known content items from content-private, to avoid false-positives in validation `GR103`. Additionally, `GR103` was added to the **ALLOWED_IGNORE_ERRORS** list.
* The **modeling-rules test** command will now validate that the modeling rules schema mappings are aligned with the test-data mappings.
* Added the *--xsiam* flag to the **init** command in order to create XSIAM content.
* Fixed an issue where the `update-additional-dependencies` **pre-commit** step …

demisto-sdk release 1.19.0

---

CHANGELOG.md
pyproject.toml

demisto-sdk release changes
* Fixed an issue where **unify** failed on integrations using an API a module, when not called from the content root.
* Improved **update-release-notes** logs when changes in dependent API modules are detected.
* Reverted changes released in version 1.19.0 in lint, lint will not fail on `demisto.results`, `return_outputs` and `LOG`.
* Updated the **generate-docs** command to use the content graph instead of the id_set file.
* Added the '--all' input option for the **prepare-content** command, to support running on all content packs.
* Updated the '-i' input option of the **prepare-content** command to support multiple inputs as a comma-separated list.

demisto-sdk release 1.19.1

---

.circleci/config.yml
CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/commands/common/logger.py
demisto_sdk/commands/content_graph/README.md
demisto_sdk/commands/generate_modeling_rules/README.md
demisto_sdk/commands/generate_unit_tests/README.md
demisto_sdk/commands/lint/README.md

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8034
sdk logging file size & rotation
Content PR - https://github.com/demisto/content/pull/29144

sdk logging file size & rotation

---

.pre-commit-hooks.yaml
demisto_sdk/scripts/update_additional_dependencies.py

fixes:
Instead of checking if `poetry.lock` has changed in the code, we can provide `files` argument in the hook itself. This simplifies things.

Update additional dependencies: use files in pre-commit instead of code

---

CHANGELOG.md
demisto_sdk/commands/content_graph/objects/pack_metadata.py

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-27601
Fixed an issue where uploading private content the command `demisto-sdk upload` fails on fileNotFound on landing_page.json.

Fixed FileNotFound: landing_page.json error

---

CHANGELOG.md
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py
demisto_sdk/tests/integration_tests/update_release_notes_integration_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5152
Updated the use of the `force` flag. 
Now when running the following command: `demisto-sdk update-release-notes -i Packs/PackName --force --text "testing"
The results will look like the following:
```
- testing
```

force flag update

---

CHANGELOG.md
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/correlation_rule.py
demisto_sdk/commands/common/schemas/correlationrule.yml
demisto_sdk/commands/common/tests/correlation_rules_test.py
demisto_sdk/commands/common/tests/test_files/invalid_correlation_rule_execution_mode.yml

fixes:https://jira-hq.paloaltonetworks.local/browse/CIAC-7254
Added a **validate** check in correlation rule files making sure that if `execution_mode` is set to `SCHEDULED`, `search_window` cannot be empty.
On the other hand, when `execution_mode` is set to `REAL_TIME`, `search_window` can be empty.

New Validation Correlation rules - Missing search window

---

CHANGELOG.md
demisto_sdk/commands/common/tests/docker_test.py
demisto_sdk/commands/format/tests/test_formatting_generic_test.py
demisto_sdk/commands/format/update_generic.py

fixes: [now support script yml](https://jira-hq.paloaltonetworks.local/browse/CIAC-8308)
fixed: [added a new line with a period](https://jira-hq.paloaltonetworks.local/browse/CIAC-8281)
fixed an issue where the format  added a new line with a period
when the description start with pipe `|`
```
comment: |-
The test
```

[Format] add period suffix to comment field and fix issue

---

CHANGELOG.md
demisto_sdk/commands/common/tools.py

fixes:
Fix validate support for svg images so the image name can end with the theme

Support themes for svg images in validate

---

CHANGELOG.md
demisto_sdk/commands/common/hook_validations/release_notes.py
demisto_sdk/commands/common/tests/release_notes_test.py
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8262
1. Updated the release notes validation to support the new force flag template
2. Fixed an issue where the new force template showed the pack ID instead of the pack display name
3. Fixed an issue in regex that missed some wrong first-level header
4. When creating a new release notes file, it will be added to git automatically

Updated validation to support force flag + some fixes

---

CHANGELOG.md
demisto_sdk/commands/common/schemas/list.yml
demisto_sdk/commands/common/tests/tools_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/content_graph/objects/list.py
demisto_sdk/tests/constants_test.py
demisto_sdk/tests/integration_tests/upload_integration_test.py
demisto_sdk/tests/test_files/list-valid.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-27578, https://jira-hq.paloaltonetworks.local/browse/CIAC-8354
on this situation downloading lists would be skipped
1. it is not true that in order to identify list we should use `allRead` key, is is not always part of the `List` structure.
2. `data` key on the other hand **always appear at any list in any variation** and also the `truncated` key.

[upload, download] - fix bugs with lists

---

CHANGELOG.md
demisto_sdk/commands/common/constants.py
demisto_sdk/commands/common/tests/tools_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/validate/tests/validators_test.py
demisto_sdk/commands/validate/validate_manager.py
demisto_sdk/tests/constants_test.py

fixes: [xsoar-prepare-testing-bucket](https://code.pan.run/xsoar/content/-/jobs/32846327) - collect_tests of vulture_whitelist file
For `collect_tests` to skip `.vulture_whitelist.py` files it is added to `FileType`.

[tools] Add FileType - VULTURE_WHITELIST

---

demisto_sdk/commands/validate/tests/validators_test.py

Following [this PR](https://github.com/demisto/demisto-sdk/pull/3633):
Improving the `test_skipped_file_types` unit test.

[validators_test] Improving the test_skipped_file_types unit test

---

CHANGELOG.md
demisto_sdk/commands/common/content/objects/pack_objects/modeling_rule/modeling_rule.py
demisto_sdk/commands/test_content/test_modeling_rule/tests/test_modeling_rule_test.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8443
Updated the call rule regex patern from `r"call\s*(?P<rule_name>\w+)"` to `r"call\s+(?P<rule_name>\w+)"` in order to avoid something like this `callblabla`

Updated the call rule regex to require a space

---

CHANGELOG.md
demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py

Fixed an issue where **modeling-rule test** command failed to properly render the comparison table when boolean value were printed.
related to bug in tabulate: https://github.com/astanin/python-tabulate/issues/189

removing the maxcolwidths from tabulate

---

CHANGELOG.md
demisto_sdk/__main__.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8508
According to [click’s official doc](https://click.palletsprojects.com/en/8.1.x/options/):
`To get the Python argument name, the chosen name is converted to lower case, up to two dashes are removed as the prefix, and other dashes are converted to underscores.`

Kebab arguments fix

---

conftest.py
demisto_sdk/commands/doc_reviewer/tests/doc_reviewer_test.py

Remove the fixture as we do not support any python versions which are below python 3.8.

remove are_mock_calls_supported_in_python_version fixture

---

CHANGELOG.md
demisto_sdk/commands/content_graph/neo4j_service.py

If the there connection issues with the graph, we stop the container and clean the data folder and try again. However, we should clean the plugins folder as well, as this folder in some cases should be recreated by the container.
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8539

[Content graph] fix cleaning environment

---

CHANGELOG.md
README.md

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-28552?filter=63809
demisto-sdk does not support autocompletion of commands, updated the docs to reflect that.

Removed autocomplete from docs

---

CHANGELOG.md
demisto_sdk/commands/format/README.md
demisto_sdk/commands/format/format_module.py

This will contiinue the formatting of the files even if graph can not be created.
This is necessary as the format fixes the files so they will be able to be parsed using the graph.
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8621

[Format] Continue formatting if graph creation fails

---

CHANGELOG.md
demisto_sdk/commands/common/tools.py

This PR adds a few changes to the `tools` module made originally in the [download-rewrite PR](https://github.com/demisto/demisto-sdk/pull/3295).
This PR adds the `safe_write_unicode` function, which is needed for the new `download` rewrite, since we open files in memory and can't use the previous `_read_file` function (which opens files from disk).
It also adds support for using `pathlib.Path` on the `get_yml_paths_in_dir` and `get_child_directories` functions, and a few other minor fixes & changes.

Add `safe_write_unicode` function to tools

---

CHANGELOG.md
demisto_sdk/commands/pre_commit/hooks/hook.py
demisto_sdk/commands/pre_commit/hooks/validate_format.py

Because `run-unit-tests` hook sometimes generates temporary files, and currently they are not deleted, then `validate` hook fails because it does not recognize these files, so `validate` needs to run before `run-unit-tests`.

[pre-commit] Fix validate hook will run before run-unit-tests hook

---

CHANGELOG.md
demisto_sdk/commands/split/tests/ymlsplitter_test.py
demisto_sdk/commands/split/ymlsplitter.py

Added support for using preloaded data when using the `YmlSplitter`, to avoid having to re-parse the file for no reason.
Used by the WIP download command rewrite.

Add pre-loaded data support for `YmlSplitter`

---

CHANGELOG.md
demisto_sdk/commands/pre_commit/pre_commit_command.py
demisto_sdk/commands/pre_commit/tests/pre_commit_test.py

fixes:https://jira-dc.paloaltonetworks.com/browse/CIAC-8303
For example, when running `demisto-sdk pre-commit -i Packs/Discord/Integrations/Discord/Discord.yml`, pre-commit will run on the files Packs/Discord/Integrations/Discord/Discord.py and Packs/Discord/Integrations/Discord/Discord.yml.

Collect the python file along with the yml file in demisto-sdk pre-commit

---

CHANGELOG.md
demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py

Fixed an issue where the **modeling-rules test** command failed report and error when test data didn't exist.

Fixed an issue where the **modeling-rules test** command failed report and error when test data didn't exist.

---

CHANGELOG.md
demisto_sdk/commands/lint/linter.py
demisto_sdk/commands/lint/tests/test_linter/docker_runner_test.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-6015
Lint container names are not unique per image, this causes errors when running lint in parallel on a few different images (like we do with the native image and its candidates). In this PR I make the docker container name include the image name and therefore make it unique per image.

Make lint container name unique

---

demisto_sdk/commands/common/clients/configs.py
demisto_sdk/commands/common/clients/tests/configs_test.py

* Fixed an issue where *auth_id* was not tested properly when initializing `ClientConfig`
* Added UTs for initializing `ClientConfigs` to avoid breaking the functionality there

clients: add uts + fix auth id bug

---

demisto_sdk/commands/common/clients/tests/get_client_test.py
demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py

Validates that the `DEMISTO_BASE_URL` is indeed a valid api url and its not by mistake a reference for the base URL.

[clients] - validate that base-api-url is indeed the api-url

---

CHANGELOG.md
demisto_sdk/commands/common/tools.py

Add a debug-level (will only appear in logfile) if there is an error fetching server's version (which is the first step for the `upload` command).
Makes it easier to debug issues which currently only log:
```
[INFO] You are using demisto-sdk 1.23.0.
Could not parse server version, please make sure the environment is properly configured.
[INFO] Could not connect to the server. Try checking your connection configurations.
```

Add debug level log if version fetch failed

---

CHANGELOG.md
demisto_sdk/commands/coverage_analyze/coverage_report.py

If running coverage-analyze to a report dir which doesn't exist locally it fails.
This PR creates the report dir if it doesn't exists.

[Coverage report] Create the report dir if not exists

---

.pre-commit-hooks.yaml
demisto_sdk/commands/pre_commit/pre_commit_command.py
demisto_sdk/commands/pre_commit/tests/pre_commit_test.py
demisto_sdk/scripts/merge_pytest_reports.py
pyproject.toml

We currently have a script to merge the coverge reports.
Changing the script to merge both pytest and coverage reports.
related: https://jira-dc.paloaltonetworks.com/browse/CIAC-7962

Merge pytest and coverage reports script

---

demisto_sdk/commands/pre_commit/pre_commit_command.py

this pr (https://github.com/demisto/demisto-sdk/pull/3824) intorduced a bug when removing skipped hooks while iterating.

[Pre-Commit] fix get hooks with skip

---

.circleci/config.yml
demisto_sdk/commands/generate_unit_tests/tests/generate_unit_tests_test.py

Move the import of `klara` modules inside the test functions so it will not be loaded in test collection

fix test collection in generate-unit-tests

---

.circleci/config.yml

Install specific version of neo4j which consists the APOC version
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9209

install specific version of neo4j in ci

---

demisto_sdk/commands/test_content/IntegrationsLock.py

https://github.com/demisto/content/pull/30983
Replaced CI_BUILD_ID with CI_JOB_ID, as the predefined CI/CD variables that start with CI_BUILD_* were deprecated in GitLab 9.0, and were removed in GitLab 16.0.
https://docs.gitlab.com/ee/update/deprecations.html?removal_milestone=16.0#ci_build_-predefined-variables

Updated deprecated env vars 

---

CHANGELOG.md
demisto_sdk/__main__.py
demisto_sdk/commands/setup_env/README.md
demisto_sdk/commands/setup_env/settings.json
demisto_sdk/commands/setup_env/setup_environment.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9241
* fix MYPYPATH and `extrapath` not to include site packages to search dependencies which are installed in site-packages
* set the setting to search the coverage file to `coverage_report`.
* Don't create `__init__.py` files in the test_data, as it's not needed after we removed all of them from the repo
* add clean flag to delete temp files

[Setup env] Fix issues with environment setup

---

demisto_sdk/scripts/update_demisto_sdk_version.sh

fixes:
run `git stash pop` only if we stash something in the begging of the script.

Add validation for non stash in demisto-sdk update script

---

demisto_sdk/scripts/merge_pytest_reports.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9294
This will combine the coverage files from the pre-commit temp folder which we will save the coverage files.

fix merge pytest coverage reports

---

demisto_sdk/scripts/merge_pytest_reports.py

`coverage.xml` file is generated in `coverage analyze` hook. No need to generate it in the `merge-pytest-reports` anymore.

dont generate coverage xml

---

CHANGELOG.md
demisto_sdk/commands/prepare_content/preparers/marketplace_incident_to_alert_playbooks_prepare.py
demisto_sdk/commands/prepare_content/tests/marketplace_incident_to_alert_playbooks_prepare_test.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9419
Fix a bug where 'incident to Alert' doesn't run for an xsiam-only Playbook

fix bug incident to alert playbook intended only xsiam

---

.github/actions/setup_environment/action.yml
.github/actions/setup_test_environment/action.yml
.github/actions/test_summary/action.yml
.github/actions/upload_artifacts/action.yml
.github/workflows/on-push.yml
demisto_sdk/commands/common/docker/tests/docker_image_test.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9220
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9466
* Move the `test-update-graph` to Github Actions
* Fail the step when unit-tests are running to make it red.
* Each job will upload its artifacts within a single directory
* jobs that tests commands will have logs inside the artifact folders too. (also unit/graph/integration jobs)
* Fixed an issue where the step of running the tests didn't fail when pytest failed.

Test Graph Commands Github Action

---

.changelog/3971.yml
CHANGELOG.md
demisto_sdk/commands/validate/old_validate_manager.py
demisto_sdk/scripts/changelog/changelog.py

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32391
Fixed a bug in validate command, where it failed with the data json list in Lists folder
fixed a bug with validating pack lists

fix validate failing on list data.json

---

.changelog/3970.yml
demisto_sdk/commands/common/tests/update_id_set_test.py
demisto_sdk/commands/common/update_id_set.py

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-31260
- When a user uses the upload command to upload a playbook that contains a task with a field name "CustomFields", if the value of that field has been retrieved from the context data using the explicit method - **${}**, the command will fail and raise an error. In this PR that will be fixed.
- Found a bug in the _get_fields_by_script_argument function regarding handling JSON input and fixed it.

Fix upload to handle approaching value in explicit way- e.g ${}

---

demisto_sdk/scripts/merge_pytest_reports.py

This fixes a typo in pytest report script so the coverage report genreated by pre-commit will be merged sucessfully.

Fix merge pytest report script

---

.changelog/3999.yml
demisto_sdk/commands/pre_commit/pre_commit_context.py

fix running individual hooks in pre-commit. The condition was reversed
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9608

[pre-commit] fix running individual hooks

---

.changelog/3995.yml
demisto_sdk/commands/init/initiator.py
demisto_sdk/commands/init/tests/initiator_test.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9391
Fixed the handling of event collectors in the init command. The command was looking for files in content master that do not exist and when did not find them it failed the entire pulling action.

Fixed wrong handling for event collector

---

.changelog/3998.yml
demisto_sdk/commands/pre_commit/hooks/pycln.py

Fixing an issue where the pycln hook won't work in a repo when the repo name contains a hypen (`-`)
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9601

Fix Pycln in repos with hypen in their name

---

.changelog/4021.yml
demisto_sdk/commands/prepare_content/integration_script_unifier.py

Fixed an issue where partner collectors that are supported by PANW show in their display a suffix of (Partner Contribution).
In that PR we remove the (Partner Contribution) addition to those kinds

[prepare-content] - fix issue with partner collectors

---

.changelog/4023.yml
demisto_sdk/commands/common/tests/readme_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/validate/tests/old_validators_test.py
demisto_sdk/tests/test_files/valid-beta-integration.yml

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9681
Fixes an issue where we have flaky validation unit-tests.
We have a few tests failing: 
https://github.com/demisto/demisto-sdk/actions/runs/7812214569?pr=3945
That happens because we query all the yml files that are in the `demisto_sdk/tests/test_files/` dir. 
Some of the yml actually have the `script: ''` key in the schema, leading to this error. 
Those yml files are being collected differently each time making those tests flaky.

fix flaky validation tests

---

TestSuite/repo.py

In new git versions, if not specifying initial branch when initializing git, it will create the repository with the `main` branch by default, we want the git to be created with `master` branch. 
when running tests that are based on `git` locally on new git versions, some of them fail as we commit all `TestSuite` changes into the `main` branch rather than the `master` branch. That doesn't fail in our CI because we use there a git version which by default initialize the git with the master branch even when not specifying it directly.

[TestSuite] - init git with master branch

---

.changelog/4027.yml
demisto_sdk/__main__.py

Add a deprecation note to the `update-content-graph` command, which is replaced by the `graph update` command.

Add A Deprecation Notice To The `update-content-graph` Command

---

.changelog/4020.yml
.changelog/4027.yml
demisto_sdk/__main__.py
demisto_sdk/commands/content_graph/objects/integration.py
demisto_sdk/commands/content_graph/objects/integration_script.py
demisto_sdk/commands/content_graph/tests/parsers_and_models_test.py

relates: https://jira-dc.paloaltonetworks.com/browse/XSUP-33213
Fixed an issue where **upload** failed when trying to upload a content item that was missing a description or type field, by giving those fields a default value.

Fixed an issue where upload failed when trying to upload a content item that was missing a description or type field/ XSUP-33213

---

.changelog/4029.yml
demisto_sdk/__main__.py
demisto_sdk/commands/setup_env/setup_environment.py
demisto_sdk/commands/setup_env/tests/setup_environment_test.py

fixes:
1. loads the env in the module scope, as the clients are loaded before the `main` function starts.
2. Removes PYTHONPATH and MYPYPATH from the .env since the VSCode Docker extension now loads the dotenv file into the docker debugging, and it contradicts the file system in the container (and we don't need it since we configure it in VSCode settings)

Fix issues with .env file support

---

.github/workflows/on-push.yml

Do not run the `coverage` job in master, should be done only each on-push which isn't master

[CI] - do not run coverage in master

---

.changelog/4044.yml
demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py
demisto_sdk/commands/setup_env/setup_environment.py

* Fixed an issue where **setup-env** crashed when trying to upload an instance of an integration into xsoar.

[setup-env] - fix an issue with the client

---

conftest.py
demisto_sdk/commands/common/files/file.py
demisto_sdk/commands/common/files/tests/binary_file_test.py
demisto_sdk/commands/common/files/tests/ini_file_test.py
demisto_sdk/commands/common/files/tests/json5_file_test.py
demisto_sdk/commands/common/files/tests/json_file_test.py
demisto_sdk/commands/common/files/tests/text_file_test.py
demisto_sdk/commands/common/files/tests/yml_file_test.py

Because the `git_util` is a class member for `File` object it gets read during tests only once, and that causes bugs as the same `git_util` object is shared between all the tests which can work on different repos.
that happens **only** in tests because there are multiple repositories created for each test using `TestSuite`.
When running in production we only have a single repository.

[File Management] - fix an issue with git_util in tests 

---

pyproject.toml

instead running "python <path to script" simply run `init-validation"

add init validation script 

---

.changelog/4060.yml
demisto_sdk/commands/common/files/file.py
demisto_sdk/commands/common/git_util.py

When sending absolute files when reading from git in the `File` object, reading it fails as it concatenates the string twice by mistake messing up the path

[File] - fix issue where reading files from git failed when sending absolute paths

---

.changelog/4088.yml
demisto_sdk/commands/common/files/file.py
demisto_sdk/commands/common/files/tests/file_test.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9790
Fixes issue where SDK would crash when running on repositories which are not git.

[SDK] - do not fail if repo isn't git

---

demisto_sdk/scripts/validate_deleted_files.py

Add logging setup to validate-deleted-files hook.

[validate-deleted-files-hook] - add logging setup

---

demisto_sdk/commands/common/docker_helper.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9851
We currently print the same error for all Docker exceptions, even though there can be different errors.
This causes a lot of confusion when debugging errors.
This PR resolves it by raising the original error.

Update Docker Error Message To Reflect Different Issues

---

.circleci/config.yml

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9876
Circle-CI do not support docker version `20.10.12` anymore, need to update it.

[cirlce-ci] - update docker version

---

.changelog/4119.yml
demisto_sdk/commands/common/hook_validations/docker.py
demisto_sdk/commands/validate/tests/DO_validators_test.py
demisto_sdk/commands/validate/validators/DO_validators/DO106_docker_image_is_latest_tag.py

primary focus on this validation should no longer be that the image youre using is the latest, it should be that your image isnt outdated. Outdated is > 3 months 
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9920

change to months

---

.changelog/4129.yml
demisto_sdk/commands/common/hook_validations/readme.py
demisto_sdk/commands/common/tests/readme_test.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9945
fixed an issue where Validation RM100 failed silently when the error was ignored and the README.md was faulted.

Fix error handeling readme validation

---

.changelog/4133.yml
demisto_sdk/commands/content_graph/objects/integration_script.py
demisto_sdk/commands/content_graph/parsers/integration_script.py
demisto_sdk/commands/content_graph/tests/parsers_and_models_test.py

add auto_update_docker_image

---

.changelog/4162.yml
demisto_sdk/commands/generate_docs/generate_integration_doc.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10048
Fixes an issue when a new integration exists in the local filesystem is considered an existing integration.

Fix Generate Docs for new Integration in Existing Pack

---

demisto_sdk/commands/common/tools.py
demisto_sdk/commands/validate/initializer.py
demisto_sdk/commands/validate/validators/base_validator.py

- Fixed an issue where validate failed due to failure with relative and abs paths formatting.
- Fixed an issue where validate failed when didn't manage to create a reference to old content object.
- Fixed an issue where validate failed when receiving both -g & -i flags.

several validate infra failures fixes

---

.changelog/4177.yml
demisto_sdk/__main__.py
demisto_sdk/commands/common/git_util.py
demisto_sdk/commands/pre_commit/pre_commit_command.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10038

add prev version argument to pre-commit

---

Utils/github_workflow_scripts/slack_notifier_master/slack_notifier.py
Utils/pytest_junit_parser.py

* Fixed an issue where slack-notifier sent duplicated tests in case the same tests failed on master for every python version.
If the same test failed for each python version, it will be reported into slack notifier just once.

[slack-notifier] - avoid sending duplicated tests

---

.changelog/4196.yml
demisto_sdk/commands/pre_commit/pre_commit_command.py

The pre-commit context stores a bit amount of memory. Once we write it to a file, we don't need to store this object and we can simply delete it, so the pre-commit checks will run with more free memory
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10173

free up resources when running pre-commit

---

.changelog/4205.yml
demisto_sdk/commands/content_graph/parsers/repository.py

This fixes an issue where a pack was deleted and the SDK tried to parse the deleted pack when updating the graph
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10236

skip deleted packs when parsing packs in the graph

---

.changelog/4213.yml
pyproject.toml

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9429
Exclude test files from package build.

Exclude Test Files from Package Build

---

.changelog/4208.yml
demisto_sdk/commands/common/content/tests/objects/pack_objects/pack_metadata/pack_metadata_test.py
demisto_sdk/commands/content_graph/objects/pack_metadata.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9853
Update to latest metadata which is applicable to the current marketplace

Update to highest toversion applicable to the current marketplace

---

.changelog/4215.yml
demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
demisto_sdk/commands/content_graph/interface/neo4j/queries/nodes.py
demisto_sdk/commands/content_graph/interface/neo4j/queries/relationships.py
demisto_sdk/commands/content_graph/neo4j_service.py

Sometimes cleaning the graph with a query doesn't clean all the data and it fails to create a graph after it.
Instead, we can delete the neo4j data folder

clean graph with cleaning data folder

---

.changelog/4219.yml
demisto_sdk/commands/setup_env/setup_environment.py
demisto_sdk/commands/setup_env/tests/setup_environment_test.py

fixes the following:
* This will create a seperate .env for the docker run. We have to use it because the path are different between the host and container
* Change to use `debugpy` in luanch since `python` debugging is deprecated.
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10277

Fix setup env test collection

---

.changelog/4227.yml
demisto_sdk/commands/common/docker/dockerhub_client.py
demisto_sdk/commands/common/docker/tests/dockerhub_client_test.py

Fixes and issue where dockerhub client failed when receiving errors of rate-limits when authenticating with username:password.

[dockerhub-client] - handle 429 errors with username:password

---

demisto_sdk/commands/pre_commit/hooks/docker.py
demisto_sdk/commands/pre_commit/pre_commit_command.py

When proccesing a large amount of images (in `docker` hook), in rare cases we get memory issues. This will use batches of the dictionary of images to proccess

use batches in docker hook multiprocessing

---

.changelog/4238.yml
demisto_sdk/commands/pre_commit/hooks/utils.py

The `get_property` didn't work corrrectly in this use case:
`property`: true
`property:<mode>`: false

fix get property in  pre-commit

---

demisto_sdk/commands/pre_commit/hooks/docker.py

Due to memory issues, we sometimes have memory issues in GitLab when proccesing the docker images in pre commit.
Here is a try to lower the images batch and to create an seperate thread executor for each batch

Docker Hook: lower images batch to 50

---

.pre-commit-config.yaml

- following https://github.com/demisto/demisto-sdk/pull/4225, `poetry-export` is no longer necessary.
- `poetry-check` hook with with `--lock` has been deprecated. Replacing with `poetry-lock --check`
related (similar): https://github.com/demisto/content/pull/34092

remove `poetry-export`, replace `poetry-lock` hook with `poetry-check --lock`

---

poetry.lock
pyproject.toml

Removed types-setuptools, for https://github.com/demisto/content/pull/33388 to pass (before merging https://github.com/demisto/demisto-sdk/pull/2801/)

remove `types-setuptools`

---

.github/workflows/on-push.yml

Generate validate docs always, not only when validate-related files are changed.

always generate valdiate docs

---

.changelog/4320.yml
demisto_sdk/commands/generate_docs/common.py
demisto_sdk/commands/generate_docs/generate_integration_doc.py
demisto_sdk/commands/generate_docs/tests/generate_docs_test.py
demisto_sdk/commands/generate_docs/tests/test_files/test_missing_cmd_description/FTP.yml

fixes:https://jira-dc.paloaltonetworks.com/browse/CIAC-10587
When generating an integration documentation where the integration YML had a command with missing argument descriptions, the SDK would crash:
```bash
INFO:demisto-sdk:[red]Error: 'NoneType' object has no attribute 'replace'[/red]
--- Logging error ---
Traceback (most recent call last):
File "/home/runner/.local/share/virtualenvs/actions-adXIK6GM/lib/python3.8/site-packages/demisto_sdk/commands/init/contribution_converter.py", line 496, in convert_contribution_to_pack
generated_readmes = self.generate_readmes_for_new_content_pack(
File "/home/runner/.local/share/virtualenvs/actions-adXIK6GM/lib/python3.8/site-packages/demisto_sdk/commands/init/contribution_converter.py", line 401, in generate_readmes_for_new_content_pack
readme = …
```

Fix Generate Docs Missing Argument Descriptions

---

.changelog/4337.yml
demisto_sdk/scripts/validate_content_path.py
demisto_sdk/tests/validate_content_path_test.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10842

allow all suffixes in doc files

---

.changelog/4332.yml
demisto_sdk/commands/format/tests/test_formatting_yml_test.py
demisto_sdk/commands/format/update_generic_yml.py

fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-10531)
Fixed an issue using the **format** command with the **--deprecate** flag would not properly work on beta integrations.

[Format --deprecated] Deprecated Beta Integration

---

.changelog/4341.yml
demisto_sdk/commands/common/tests/tools_test.py
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/validate/validators/BA_validators/BA119_is_py_file_contain_copy_right_section.py
demisto_sdk/commands/validate/validators/DS_validators/DS107_is_description_contains_demisto_word.py
demisto_sdk/commands/validate/validators/RM_validators/RM106_is_contain_demisto_word.py
demisto_sdk/commands/validate/validators/RM_validators/RM113_is_contain_copy_right_section.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10860

add optional exceptions to `search_substrings_by_line`

---

.changelog/4398.yml
demisto_sdk/commands/common/hook_validations/integration.py
demisto_sdk/commands/validate/validators/IN_validators/IN121_is_valid_fetch.py

fixes: [CIAC-11031](https://jira-dc.paloaltonetworks.com/browse/CIAC-11031)
Fixed an issue where IN121 in the new validate flow and IN148 in the old validate flow failed when running on content items with XSOAR on prem and XSOAR SAAS Marketplaces.

Add support for all xsoar mps in IN121 validation

---

.changelog/4427.yml
demisto_sdk/commands/common/git_util.py

Added the verbose=False parameter to the fetch method call to minimize unnecessary output messages.

git_util - update fetch logs

---

.changelog/4432.yml
demisto_sdk/commands/common/hook_validations/playbook.py
poetry.lock

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-39367
currently, when running in a private repo we allow to ignore errors which aren't allowed to be ignored in `content` repo
`PB103` as example
`demisto-sdk validate --skip-new-validate --run-old-validate -i THE_PACK`
but, in case of ignored `PB103` in a private repo, due to a bug - the the error message not display but the result are invalid.
**_before fix:_**
**_after fix:_**

Old validate PB103 fix

---

.changelog/4434.yml
demisto_sdk/scripts/tests/validate_file_permission_changes_test.py
demisto_sdk/scripts/validate_file_permission_changes.py

fixes:https://jira-dc.paloaltonetworks.com/browse/CIAC-11178
As seen in https://github.com/demisto/content/actions/runs/9960003744/job/27518173799?pr=35457#step:8:796, when attempting to find if a file permission has changed, we're unable to find the upstream branch in contribution/external PRs.
Since the `validate_changed_files_permissions` hook runs only on files inside the `Packs` directory, there's no reason ever to have an executable file there. Therefore, this PR introduces a few changes to how `validate_changed_files_permissions` works:
- We use `os.stat` to check for file permissions for owner, group and world scopes instead of relying on `git_util.has_file_permissions_changed` and `git diff --summary` output parsing.
- Removed check whether we're in a CI environment as it's …

Fix Validate File Permissions

---

.changelog/4436.yml
.pre-commit-hooks.yaml

fixes:https://jira-dc.paloaltonetworks.com/browse/CIAC-3448
Remove the `validate-file-permission-changes` from pre-commit conf. Will be readded once https://github.com/demisto/demisto-sdk/pull/4434 is released.

Remove `validate-file-permission-changes` hook from Pre-Commit conf

---

.changelog/4472.yml
demisto_sdk/commands/common/schemas/xsiamreport.yml

related: https://jira-dc.paloaltonetworks.com/browse/CIAC-10677
Add a missing key (as optional) in the schema.

add `metadata` field to XSIAM report schema

---

.changelog/4480.yml
demisto_sdk/commands/test_content/TestContentClasses.py
demisto_sdk/commands/test_content/tests/build_context_test.py

related: https://github.com/demisto/demisto-sdk/pull/4442
Started supporting only the a dict value for "cloud_servers_api_keys" file provided.

Fix API Key Access 

---

.changelog/4487.yml
demisto_sdk/commands/test_content/ParallelLoggingManager.py
demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py

Split the testing of modeling rules on XSIAM to multiple machines fixing logger threading
fixes: [CIAC-11145](https://jira-dc.paloaltonetworks.com/browse/CIAC-11145)
fix parallel logger

CIAC-11145 - Split the testing of modeling rules on XSIAM to multiple machines fixing logger threading

---

.changelog/4495.yml
demisto_sdk/commands/content_graph/neo4j_service.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11519
fixing the way we try to remove old containers by adding "all=True" to when we search for the old container in order to remove him.

Fixing the way we try to remove old containers

---

.changelog/4497.yml
demisto_sdk/commands/common/content/objects/pack_objects/pack.py
demisto_sdk/commands/common/hook_validations/pack_unique_files.py
demisto_sdk/commands/validate/tests/PA_validators_test.py
demisto_sdk/commands/validate/validators/PA_validators/PA102_should_pack_be_deprecated.py

fixes: [CIAC-11542](https://jira-dc.paloaltonetworks.com/browse/CIAC-11542)
Fixed validation PA102 (and PA132 old validate) that failed when there were valid modeling rules in a pack, therefore the entire pack should not be deprecated. 
Example PR: https://github.com/demisto/content/pull/35922

Fixed PA102 for modeling_rules

---

.changelog/4483.yml
demisto_sdk/commands/common/schemas/releasenotesconfig.yml
demisto_sdk/commands/update_release_notes/update_rn.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11021
Braking changes release notes message on items related to specific marketplace, will not appear in other marketplaces.
This introduces the marketplaces new field in the BC RN JSON file.
The field is a list, its default value is all marketplaces. It supports aggregated RN and editing RN backwards.

Support Breaking Changes Marketplace

---

CHANGELOG.md

* The `--ignore` flag in the **validate** command no longer requires error codes to be listed under `ignorable_errors` in the config file. [#4509](https://github.com/demisto/demisto-sdk/pull/4509)
* Fixed an issue where the DS107 validation (descriptions shouldn't contain the phrase `demisto`) failed when the `Demisto Bot` was mentioned. [#4517](https://github.com/demisto/demisto-sdk/pull/4517)

v1.31.10 - post-release

---

.changelog/4519.yml
demisto_sdk/commands/content_graph/parsers/modeling_rule.py
demisto_sdk/commands/content_graph/strict_objects/assets_modeling_rule_schema.py
demisto_sdk/commands/validate/tests/ST_validators_test.py

Add StrictAssetsModelingRuleSchema pydantic object for ST110 validation

ST110 - StrictAssetsModelingRuleSchema

---

.changelog/4549.yml
demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py
demisto_sdk/commands/content_graph/interface/neo4j/queries/validations.py
demisto_sdk/commands/validate/tests/GR_validators_test.py
demisto_sdk/commands/validate/validators/GR_validators/GR106_is_testplaybook_in_use.py
demisto_sdk/tests/test_files/conf.json

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11761
This validation 
```
Checks that every test playbook is linked to at least one content item.
(the content item has a 'tests:' key with the id of the test playbook)
```
But the the collect test for reputation playbooks checks the r`eputation_tests` field in conf.json and not the `tests` key in the yml so we need to ignore reputation test

[GR106] reputation_tests

---

.changelog/4587.yml
demisto_sdk/commands/common/errors.py
demisto_sdk/commands/common/hook_validations/release_notes.py
demisto_sdk/tests/integration_tests/create_id_set_integration_test.py

> [!NOTE]  
> Fix a repeated typo in demisto-sdk: "duo to" --> "due to".

Fix repeated typo in demisto-sdk

---

.changelog/4597.yml
demisto_sdk/commands/common/clients/xsiam/xsiam_api_client.py

fixes:  https://jira-dc.paloaltonetworks.com/browse/CIAC-11907
`Fixed an issue where debug-logging in **setup-env** failed.`
*demisto-sdk version:* 1.32.1
```
raise ValueError('Closing tag "%s" has no corresponding opening tag' % markup)
```

[setup-env] Fix  logging

---

demisto_sdk/commands/common/docker_helper.py

fixes:
We improved the Docker logs in #4500.
These changes caused the build to fail with the following error: 
```
docker.errors.DockerException: local variable 'docker_push_output' referenced before assignment
```

Fix Docker Logs

---

.changelog/4639.yml
demisto_sdk/commands/common/tests/update_id_set_test.py
demisto_sdk/commands/common/update_id_set.py
demisto_sdk/commands/content_graph/parsers/classifier.py
demisto_sdk/commands/content_graph/parsers/mapper.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12087
Fixed an issue where the validate and create-id-set commands would fail to process correctly when encountering null values in the filters or transformers fields.

[validate] empty filters and transformers fields

---

.changelog/4648.yml
demisto_sdk/commands/common/docker_helper.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12137
- description: Fixed an issue where logging would fail when creating a Docker image.
```
File "content/.venv/lib/python3.10/site-packages/demisto_sdk/commands/common/docker_helper.py", line 479, in get_or_create_test_image
logger.critical(f"{log_prompt} - Build errors occurred: {errors}")
File "content/.venv/lib/python3.10/site-packages/loguru/_logger.py", line 2060, in critical
__self._log("CRITICAL", False, __self._options, __message, args, kwargs)
File "content/.venv/lib/python3.10/site-packages/loguru/_logger.py", line 2017, in _log
colored_message = Colorizer.prepare_simple_message(str(message))
File "content/.venv/lib/python3.10/site-packages/loguru/_colorizer.py", line 368, in prepare_simple_message
parser.feed(string) …
```

Logging Failure During Docker Creation

---

.changelog/4649.yml
Utils/github_workflow_scripts/jira_integration_scripts/link_pr_to_jira_issue.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12138
```
File "/home/runner/work/demisto-sdk/demisto-sdk/Utils/github_workflow_scripts/jira_integration_scripts/./link_pr_to_jira_issue.py", line 85, in trigger_generic_webhook
logger.info(f"Detected Pr: {pr_title=}, {pr_link=}, {pr_body=}")
File "/home/runner/work/demisto-sdk/demisto-sdk/.venv/lib/python3.9/site-packages/loguru/_logger.py", line 2044, in info
__self._log("INFO", False, __self._options, __message, args, kwargs)
File "/home/runner/work/demisto-sdk/demisto-sdk/.venv/lib/python3.9/site-packages/loguru/_logger.py", line 2017, in _log
colored_message = Colorizer.prepare_simple_message(str(message))
File "/home/runner/work/demisto-sdk/demisto-sdk/.venv/lib/python3.9/site-packages/loguru/_colorizer.py", line …
```

[Github Workflow] Logging Failure During `Add PR link to Related Jira Issue`

---

.changelog/4625.yml
.changelog/4635.yml
.changelog/4638.yml
.changelog/4639.yml
.changelog/4640.yml
.changelog/4646.yml
CHANGELOG.md
pyproject.toml

* The following commands will be deprecated and removed entirely in the next SDK release in two weeks: convert, create-content-artifacts, create-id-set, extract-code and lint.
* Moved CJ102 to the new validate format. The validation's error number is now BA103 and it ensure that the tests section is either a non-empty list or "No tests".
* Fixed an issue where getting a malformed file raised an non-indicative error.
* Fixed an issue where the **validate** and **create-id-set** commands would fail to process correctly when encountering null values in the filters or transformers fields.
* Moved RN113 to the new validate format. The validation ensures that all the first level headers in the release note are valid content types.
* Moved RN115 to the new validate format. The validation ensure …

Manual Release 1.32.4

---

.changelog/4657.yml
demisto_sdk/__init__.py
demisto_sdk/commands/common/logger.py

fixes: [CIAC-12159](https://jira-dc.paloaltonetworks.com/browse/CIAC-12159)
When using 'demisto-sdk' as a library within content scripts/integrations, the new logging setup/initialization conflicts with existing logger and causes the container to crash when initialized statically.
Additionally, logs does not show up on default python's logging which is used in content scripts/integration.
- Excluding sdk's logging initialization logic when imported as a library.
- Propagating log entries to default logging system when flagged.

Fix logger setup

---

.changelog/4666.yml
poetry.lock
pyproject.toml

Add a `setuptools` dependency, solving an issue where SDK commands would fail in some systems.

add `setuptools`

---

.changelog/4668.yml
demisto_sdk/commands/pre_commit/pre_commit_command.py

fixes:
Fixed an issue where `pre-commit` inadvertently skipped all files when executed with the `--all-files` flag.

[pre-commit] Fixed an issue with running on all files

---

tests_end_to_end/xsoar/test_e2e_demisto_sdk_flow_playbook_xsoar.py

fixes:
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/10666861/raw
```
E       TypeError: LocalPath.mkdir() got an unexpected keyword argument 'exist_ok'
```

use tmp_path in e2e tests

---

.changelog/4674.yml
demisto_sdk/commands/common/docker_helper.py

fixes: [XSUP-43593](https://jira-dc.paloaltonetworks.com/browse/XSUP-43593)
Add support for non-default ports when parsing docker image values. i.e: `image.registry:5000/repo/some-image:main`, where default docker image values looked like this: `registry/some-image:main`

[demisto-sdk] Add support for non-default ports when parsing docker image values

---

.changelog/4690.yml
demisto_sdk/commands/setup_env/setup_env_setup.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12289
fixes an issue where the `-i` flag was missing from the **setup-env** command following the`typer` update (#4637).
In the VSCode extension, we are using the `-i` flag instead of the `--input` flag.
To reproduce the issue, follow these steps:
1. Install the demisto-sdk from your local demisto-sdk project by running the command:
```
pip install -e '~/dev/demisto/demisto-sdk/'
```
2. Attempt to execute the VSCode extension command: `setup integration/script environment`.
You should encounter the following error:

[setup-env] Missing The `-i` Flag

---

.changelog/4687.yml
demisto_sdk/__main__.py

`demisto-sdk --release-notes` command will now print a much nicer markdown representation of the currently installed demisto-sdk version (using the newly added typer library support in demisto-sdk).

[demisto-sdk] Upgrade release-notes flag output

---

.changelog/4698.yml
demisto_sdk/__main__.py

Related: [CIAC-12263](https://jira-dc.paloaltonetworks.com/browse/CIAC-12263)
Adds a warning message when using the SDK with python 3.9.xx installed

Warn about upcoming python 3.9 support removal

---

.changelog/4589.yml
.changelog/4637.yml
.changelog/4659.yml
.changelog/4667.yml
.changelog/4680.yml
.changelog/4685.yml
.changelog/4686.yml
.changelog/4687.yml
.changelog/4689.yml
.changelog/4690.yml
.changelog/4691.yml
.changelog/4694.yml
.changelog/4695.yml
.changelog/4696.yml
.changelog/4698.yml
.changelog/4699.yml
.changelog/4700.yml
CHANGELOG.md
pyproject.toml

* Modified the ***demisto-sdk --release-notes*** command to print a markdown representation of the currently installed demisto-sdk changelog. [#4687](https://github.com/demisto/demisto-sdk/pull/4687)
* Added support for a new pack version_config.json file. [#4699](https://github.com/demisto/demisto-sdk/pull/4699)
* Updated the ***prepare-content*** command to replace all occurrences of an incorrect marketplace reference in the content. [#4659](https://github.com/demisto/demisto-sdk/pull/4659)
* The Demisto-SDK CLI has been upgraded to use Typer for command-line interface (CLI) management. [#4637](https://github.com/demisto/demisto-sdk/pull/4637)
* Added an isSilent key to the Playbook and Trigger schemas. [#4689](https://github.com/demisto/demisto-sdk/pull/4689)
* Updated the GR107 …

Demisto-sdk release 1.33.0

---

.changelog/4720.yml
demisto_sdk/commands/validate/tests/RN_validators_test.py
demisto_sdk/commands/validate/tools.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12157

Exclude silent items from release notes validation

---

.changelog/4736.yml
demisto_sdk/commands/content_graph/common.py
demisto_sdk/commands/content_graph/objects/content_item.py
demisto_sdk/commands/content_graph/objects/content_item_xsiam.py
demisto_sdk/commands/content_graph/objects/pack.py
demisto_sdk/commands/content_graph/tests/common_test.py

relates: https://jira-dc.paloaltonetworks.com/browse/CRTX-145079
Simplified the `replace_incorrect_marketplace` function to modify the input data directly, addressing the issue where "incident to alert" was not applied. This occurred because a copy of the data was inadvertently created, leading to unexpected behavior in downstream processes.
For the record:  
Here are two versions of the Phishing pack that went through the **prepare content** command, one with and one without my `replace_marketplace_references` function.  
https://drive.google.com/drive/folders/10m6dv0MSBTUpdAFZ1vhUIKnb_D7CVZBs
I compared them using [this tool](https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-diff)
The only change is the expected update to "Cortex XSOAR."  
The "incident to alert" …

Fix incident to alert issue /CRTX-145079

---

.changelog/4735.yml
demisto_sdk/commands/update_release_notes/tests/update_rn_test.py
demisto_sdk/commands/update_release_notes/update_rn.py

fixes: [CIAC-11960](https://jira-dc.paloaltonetworks.com/browse/CIAC-11960)

Format Playbook RN

---

.changelog/4761.yml
demisto_sdk/commands/pre_commit/pre_commit_command.py

fixes: [CIAC-12128](https://jira-dc.paloaltonetworks.com/browse/CIAC-12128)
Modifying tests collection to collect all tests located in the same directory of a changed script file, rather than collecting tests matching the script file name.
This puts us on the safe side when working on a content item and seeking its tests to be executed in CI/CD without concerning about file names discrepancies.

modify tests collection

---

.changelog/4763.yml
demisto_sdk/commands/content_graph/strict_objects/case_layout.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12595
blocks: https://github.com/demisto/content/pull/37625
Fixed an issue where **ST110** validation failed on unexpected value when adding the marketplace key to the CaseLayout content item.
```
Packs/Core/CaseLayouts/layoutscontainer-Default_XSIAM_Case.json: [ST110] - Structure error (value_error.const) in field marketplaces of layoutscontainer-Default_XSIAM_Case.json: unexpected value; permitted: <MarketplaceVersions.MarketplaceV2: 'marketplacev2'>
```

Case Layout Structure

---

.changelog/4765.yml
demisto_sdk/commands/update_release_notes/update_release_notes_setup.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12598
Fixed an issue where the update-release-notes delete the version from the pack metadata when using the -u flag with an invalid value
After the fix:

Enum Validation for --update-type Flag in update-release-notes Command

---

.changelog/4781.yml
demisto_sdk/commands/validate/validators/RN_validators/RN111_is_docker_entry_match_yml.py

fixed an issue where used name not displayname

fix rn111 displayname

---

.changelog/4791.yml
demisto_sdk/commands/setup_env/README.md
demisto_sdk/commands/setup_env/setup_env_setup.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12692
Fixed an issue where this error appeared:
```
╭─ Error ──────────────────────────────────────────────────────────────────────╮
4392  │ Invalid value for '[FILE_PATHS]...': 2 values are required, but 0 were       │
4393  │ given.                                                                       │
4394  ╰──────────────────────────────────────────────────────────────────────────────╯
```

[setup-env] fix empty var issue

---

.changelog/4798.yml
demisto_sdk/commands/content_graph/common.py
demisto_sdk/commands/content_graph/tests/common_test.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12759
relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-10198
- Updated the regex for replacing incorrect marketplace versions to remove the entire version following "XSOAR."
For example:
"Cortex XSOAR V6.5.3 example" → "Cortex example"
- Additionally, added an exception to preserve references that point to unique documentation specific to a product/version—no replacement occurs in such cases.

Fix the "replace_marketplace_references" regex / CIAC-12759

---

.changelog/4806.yml
.changelog/4812.yml
demisto_sdk/commands/lint/resources/python3_requirements/dev-requirements.txt

Related: https://jira-dc.paloaltonetworks.com/browse/CIAC-12856
https://github.com/demisto/demisto-sdk/pull/4806
Because of this error, we are going to lock on 1.14.1

Lock mypy on 1.14.1

---

.changelog/4814.yml
demisto_sdk/commands/content_graph/common.py
demisto_sdk/commands/content_graph/tests/parsers_and_models_test.py
demisto_sdk/commands/validate/validators/RN_validators/RN107_missing_release_notes_entry.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12754
content PR: https://github.com/demisto/content/pull/38605

Fix CaseLayouts

---

.changelog/4803.yml
demisto_sdk/commands/test_content/TestContentClasses.py
demisto_sdk/commands/test_content/tests/build_context_test.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12734
Fixed an issue where setting the marketplace entry to xsoar_on_prem in the configuration also caused the test to run on xsoar_saas.

CIAC-12734

---

.changelog/4825.yml
demisto_sdk/commands/common/docker_helper.py
demisto_sdk/commands/pre_commit/hooks/docker.py

Fixed an issue where pushing a Docker image to a Docker registry incorrectly returned a success message despite the operation failing.

[docker] Fix issue with push images

---

.changelog/4823.yml
demisto_sdk/commands/common/schemas/integration.yml
demisto_sdk/commands/common/schemas/script.yml
demisto_sdk/commands/content_graph/strict_objects/base_strict_model.py
demisto_sdk/commands/content_graph/strict_objects/integration.py
demisto_sdk/commands/content_graph/strict_objects/script.py

fixes:https://jira-dc.paloaltonetworks.com/browse/CIAC-12740
Done as part of: [Cortex Platform Content Marketplace Support](https://jira-dc.paloaltonetworks.com/browse/CIAC-12736)
update parser to supporting:
- `prettyPredefined`
- `prettyname`
- `quickaction`
- `supportsquickactions`

Platform MP: update parsers with the required fields

---

.changelog/4834.yml
demisto_sdk/commands/validate/tests/PA_validators_test.py
demisto_sdk/commands/validate/tests/PB_validators_test.py
demisto_sdk/commands/validate/validators/BA_validators/BA126_content_item_is_deprecated_correctly.py
demisto_sdk/commands/validate/validators/DS_validators/DS101_is_valid_beta_description.py
demisto_sdk/commands/validate/validators/IT_validators/IT102_is_auto_extract_fields_valid.py
demisto_sdk/commands/validate/validators/PA_validators/PA102_should_pack_be_deprecated.py
demisto_sdk/commands/validate/validators/PB_validators/PB104_deprecated_description.py

fixed cases where validate mistake <> in msgs for colors

---

.changelog/4836.yml
demisto_sdk/commands/common/tools.py
demisto_sdk/commands/content_graph/objects/integration.py
demisto_sdk/commands/content_graph/parsers/integration.py
demisto_sdk/commands/validate/validators/RM_validators/RM110_is_commands_in_readme.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12957
added support for `hidden` commands in the SDK

MP `platform`: added support for `hidden` commands

---

.changelog/4829.yml
demisto_sdk/commands/secrets/secrets.py
demisto_sdk/commands/validate/initializer.py
demisto_sdk/commands/validate/tests/validators_test.py

fixes: [CIAC-12482](https://jira-dc.paloaltonetworks.com/browse/CIAC-12482)
rn108 used to failed due to mismatch classifying git statuses of files.
The fix ensures that the number of fetched files matches the number of files in the contribution_files_relative_paths.txt file. If a discrepancy is found, indicating untracked files, it halt execution due to a mismatch in file counts.

Fix imported files git status

---

.changelog/4855.yml
demisto_sdk/commands/pre_commit/pre_commit_command.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13074
When deleting a folder with a file inside it in content.
When we are collecting test for the deleted file it try to iterate over the files in the parent (also deleted folder). 
Failing with file not found error due to the fact the folder does not exists any more.

checking if parent folder exists before iterating on it

---

.changelog/4904.yml
demisto_sdk/commands/upload/tests/upload_test.py
demisto_sdk/commands/upload/tests/uploader_test.py
demisto_sdk/commands/upload/upload_setup.py
demisto_sdk/commands/upload/uploader.py

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-49160
Fixed an issue where regression was made in the upload command, causing users to fail uploading more than one input file/pack/

XSUP-49160

---

.changelog/4909.yml
demisto_sdk/commands/common/clients/xsiam/xsiam_api_client.py

fixes: [link to issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13075)
Add a new `XsiamClient.search_alerts_by_name` method and fix an issue in the `XsiamClient.search_alerts_by_uuid` method that caused the logic to iterate over the first 100 results only.

Add search_alerts_by_name and fix search_alerts_by_uuid in XsiamClient

---

.changelog/4910.yml
demisto_sdk/commands/common/clients/xsiam/xsiam_api_client.py
demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py
demisto_sdk/commands/common/constants.py

fixes: [link to issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13077)
Add a new `XsiamClient.poll_alert_state` method that polls a Cortex XSIAM alert until it reaches any of the expected states.

Add poll_alert_state to XsiamClient

---

.changelog/4932.yml
demisto_sdk/scripts/changelog/changelog.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12713
- Ignored the info logging _Please run demisto-sdk in a content repository_ for the SDK-changelog command
- Added logging for the content repo, now it will say that this command should run only from sdk

Fixed logging for sdk-changelog command.

---

.changelog/4921.yml
demisto_sdk/commands/content_graph/objects/base_content.py

fixes:
This PR fixes an intermittent JSON serialization issue in the BaseContent.to_dict() method that was causing validation failures in GitHub Actions. The issue occurred when trying to serialize complex objects like RNRelatedFile that don't have JSON serialization methods defined.
Solution
Changed to_dict() to use self.dict() directly instead of using self.json() followed by json.loads(), avoiding the serialization step that was failing with complex objects.

Fix intermittent JSON serialization issue in BaseContent.to_dict() method

---

.changelog/5014.yml
CHANGELOG.md
demisto_sdk/commands/common/schemas/layoutscontainer.yml
demisto_sdk/commands/content_graph/strict_objects/layout.py

fixes: [XSUP-53187](https://jira-dc.paloaltonetworks.com/browse/XSUP-53187).
- As described in this ticket - [XSUP-53187](https://jira-dc.paloaltonetworks.com/browse/XSUP-53187), the ST110 validation is failing for `layouts` that include `display filters` at the layout `section` level. 
It appears that the layout schemas allowed display filters only for the `section field` level, but not for the `section` level. 
- Added the filters schema to:
1. The Graph - strict objects layout schema (used in the validate command). 
2. The old layout container schema (used by the format command).

Fixed Layouts Schemas

---

.changelog/5034.yml
demisto_sdk/commands/common/schemas/integration.yml
demisto_sdk/commands/content_graph/strict_objects/integration.py
demisto_sdk/commands/validate/tests/ST_validators_test.py

We have a structure validation for our integration structure. in the new "triggers" fetcher the name of the allowed key was wrong (The decided name was different than the actual name being used on front-end side), fixing it now.

Fix wrong operator name in ST110 structure validation
